### ISSUE TITLE
cannot build on osx due to pthread

### ISSUE THREAD

**Issue by Hardcore-fs** [madMAx43v3r/chia-plotter#1]
/Volumes/null/chia-plotter/chia-plotter/include/chia/Thread.h:91:4: error: no matching function for call to 'pthread_setname_np'
                        pthread_setname_np(pthread_self(), thread_name.c_str());
                        ^~~~~~~~~~~~~~~~~~
/usr/include/pthread.h:500:5: note: candidate function not viable: requires 1 argument, but 2 were provided
int     pthread_setname_np(const char*);
        ^

**Comment by Hardcore-fs** [comment]
strangely your latest version built first time...
thanks

**Comment by madMAx43v3r** [comment]
Yeah I put a `#ifdef` around it like you should
