### ISSUE TITLE
Can't compile since Blake 3 modification on M1 apple device

### ISSUE THREAD

**Issue by AndyRPH** [madMAx43v3r/chia-plotter#103]
Zillions of compile errors all around Blake 3 on my MacBook Pro M1. 

In the back of my head I thought I read that blake3 support on apple arm M1 chips was experimental, but I can't find any proof of that to reference here. 

Can we conditionalize blake3 to not compile if the chip doesn't support it?

**Comment by AndyRPH** [comment]
Hmm b3sum installs and runs fine for me from here: https://github.com/BLAKE3-team/BLAKE3

but compiling this chia plotter yields things like below, I'm guessing it is only looking to use the x86 version of blake3? 


```
   ^
/Applications/Chia-arm/maxplotter/chia-plotter/lib/BLAKE3/c/blake3_avx512_x86-64_unix.S:2424:9: error: unrecognized instruction mnemonic
        vpxord xmm1, xmm1, xmm2
        ^

```
```
/Applications/Chia-arm/maxplotter/chia-plotter/lib/BLAKE3/c/blake3_sse2_x86-64_unix.S:2145:9: error: /Applications/Chia-arm/maxplotter/chia-plotter/lib/BLAKE3/c/blake3_avx512_x86-64_unix.S:2091:9: unrecognized instruction mnemonic, did you mean: mov, movz?
error:         movzx eax, r8b
        ^
unrecognized instruction mnemonic

```

**Comment by AndyRPH** [comment]
```

-- Configured operating system: MACOSX
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Configured GMP: /opt/homebrew/lib/libgmp.dylib
-- Compiler flags:  -Wall   -O3 -funroll-loops -fomit-frame-pointer -pthread
-- Linker flags: -L/Applications/Chia-arm/maxplotter/chia-plotter/build/_deps/relic-src/src/low/gmp/ 
-- Configured /Applications/Chia-arm/maxplotter/chia-plotter/build/_deps/relic-src/include/relic_conf.h.in
SODIUM_FOUND in src/CMakeLists.txt
-- Configuring done
-- Generating done
-- Build files have been written to: /Applications/Chia-arm/maxplotter/chia-plotter/build
Scanning dependencies of target arith_objs
Scanning dependencies of target fse
Scanning dependencies of target blstmp
Scanning dependencies of target blake3
[  0%] Built target arith_objs
[  0%] Building C object CMakeFiles/fse.dir/lib/FSE/lib/fse_decompress.c.o
[  1%] Building C object CMakeFiles/fse.dir/lib/FSE/lib/entropy_common.c.o
[  1%] Building C object CMakeFiles/blake3.dir/lib/BLAKE3/c/blake3.c.o
[  2%] Building C object CMakeFiles/fse.dir/lib/FSE/lib/fse_compress.c.o
[  2%] Building C object CMakeFiles/blake3.dir/lib/BLAKE3/c/blake3_portable.c.o
[  2%] Building C object CMakeFiles/fse.dir/lib/FSE/lib/hist.c.o
[  3%] Building C object CMakeFiles/blake3.dir/lib/BLAKE3/c/blake3_dispatch.c.o
[  3%] Building CXX object lib/bls-signatures/src/CMakeFiles/blstmp.dir/privatekey.cpp.o
clang: warning: argument unused during compilation: '-fmax-errors=1' [-Wunused-command-line-argument]
[  3%] Building ASM object CMakeFiles/blake3.dir/lib/BLAKE3/c/blake3_avx2_x86-64_unix.S.o
[  3%] Linking C static library libfse.a
[  3%] Building ASM object CMakeFiles/blake3.dir/lib/BLAKE3/c/blake3_avx512_x86-64_unix.S.o
[  4%] Building CXX object lib/bls-signatures/src/CMakeFiles/blstmp.dir/bls.cpp.o
Scanning dependencies of target relic_s
clang: warning: argument unused during compilation: '-fmax-errors=1' [-Wunused-command-line-argument]
/Applications/Chia-arm/maxplotter/chia-plotter/lib/BLAKE3/c/blake3_avx2_x86-64_unix.S:15:1: error: unknown directive
.intel_syntax noprefix
^
/Applications/Chia-arm/maxplotter/chia-plotter/lib/BLAKE3/c/blake3_avx2_x86-64_unix.S:27:9: error: unrecognized instruction mnemonic, did you mean: ushl, ushr?
        push r15
        ^

```

**Comment by PeratX** [comment]
You should just compile neon on Apple M1 which does not have AVX features.

**Comment by madMAx43v3r** [comment]
yeah that's wrong, it shouldn't try to use `blake3_avx2_x86-64_unix.S` in that case...

**Comment by madMAx43v3r** [comment]
you can edit `CMakeLists.txt` to hardcode the following:
```
set(BLAKE3_SRC
            ${BLAKE3_PATH}/blake3.c
            ${BLAKE3_PATH}/blake3_portable.c
            ${BLAKE3_PATH}/blake3_dispatch.c
        )
```

**Comment by AndyRPH** [comment]
Can do- if it's not properly detecting that I'm arm64, are there other compile adjustments it's not optimizing for?  Not sure how to troubleshoot why it's not detecting the system type right.

**Comment by madMAx43v3r** [comment]
`ELSEIF(OSX_NATIVE_ARCHITECTURE STREQUAL "arm64")`

Seems like that's not working for you. As for other cases, I think BLAKE3 is the only lib with assembly code.

**Comment by Hardcore-fs** [comment]
its wrong.......
the way the libraries work:
Compile EVERYTHING!!!
at runtime try to detect the chipset.
and switch the relvant libraries.

only problem is....... that when the apple compiler tries to compile "everything", it breaks.

so you need to comment out the bad calls so that the code is not even compiled.
then exclude the stuff in  "CMakeLists.txt"

it's in:
${BLAKE3_PATH}/blake3_portable.c

had to do the same on the old intel apple chips that dont have the 512 instructions.
the "clang" still tries to compile the libraries, even they are excluded....

**Comment by AndyRPH** [comment]
Just editing the CMakeLists.txt was enough to get it to compile, didn't have to change anything in blake3_portable.c

**Comment by Hardcore-fs** [comment]
wow.... you lucky guy.....
i mess about for over an hour getting it to work....

**Comment by stingray072** [comment]
> Just editing the CMakeLists.txt was enough to get it to compile, didn't have to change anything in blake3_portable.c

What kind of times are you getting on the M1?

**Comment by AndyRPH** [comment]
Let's move time discussion to a discussion not an issue.
