### ISSUE TITLE
There was no movement

### ISSUE THREAD

**Issue by liuxx007** [madMAx43v3r/chia-plotter#108]
![QQ图片20210610111041](https://user-images.githubusercontent.com/79682836/121459072-2889b180-c9dd-11eb-969c-db9ae8c9c369.png)

**Comment by tylerpuig** [comment]
Getting the same issue, did you solve this?

**Comment by VertiHydro** [comment]
He moved his question to here: #74, but as delucca points out at the bottom of that thread, running it in Docker is _way_ easier.

**Comment by liuxx007** [comment]
> Getting the same issue, did you solve this?

NO
