### ISSUE TITLE
[Aborted (core dumped)] commit 3b553d3548f44708e4fa9ddd80b45bae2ba756e3

### ISSUE THREAD

**Issue by Dartellum** [madMAx43v3r/chia-plotter#109]
New build - Ubuntu 20.04.2 Server. Fresh compile.

```[P1] Table 1 took 199.42 sec
[P1] Table 2 took 1060.64 sec, found 4294961225 matches
[P1] Table 3 took 1639.5 sec, found 4294933574 matches
[P1] Table 4 took 2379.71 sec, found 4294894330 matches
terminate called after throwing an instance of 'std::runtime_error'
  what():  thread failed with: input not sorted
Aborted (core dumped)```

**Comment by grayfallstown** [comment]
#46

**Comment by madMAx43v3r** [comment]
hm that fix from #46 is already in commit 3b553d3548f44708e4fa9ddd80b45bae2ba756e3

could be unstable RAM

**Comment by Dartellum** [comment]
> could be unstable RAM

The RAM is not overclocked or underclocked. I will run a memtest later today.

**Comment by Dartellum** [comment]
I went in front of the server this morning, as I could not ssh after the reboot last night. Anyway, bunch of I/O errors on /dev/sdb. I will check the drives for bad sectors.

**Comment by madMAx43v3r** [comment]
that could be the cause indeed, if you don't use ramdisk

**Comment by cojarbi** [comment]
I'm getting a similar error, is it related?

[P1] Table 1 took 199.239 sec
terminate called after throwing an instance of 'std::runtime_error'
  what():  thread failed with: thread failed with: thread failed with: thread failed with: fwrite() failed
Aborted (core dumped)

**Comment by madMAx43v3r** [comment]
`fwrite() failed` => probably ran out of disk space? It failed to write data to tmpdir essentially.

**Comment by Dartellum** [comment]
Closing this issue.
