### ISSUE TITLE
make on the macos 11.4 ,the file "sodium.h" not found

### ISSUE THREAD

**Issue by wxysystem32** [madMAx43v3r/chia-plotter#121]
make on the macos 11.4 ,the file "sodium.h" not found

[ 99%] Built target bls
[ 99%] Building CXX object CMakeFiles/chia_plot.dir/src/chia_plot.cpp.o
[ 99%] Linking CXX executable test_phase_2
clang: warning: argument unused during compilation: '-fmax-errors=1' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-fmax-errors=1' [-Wunused-command-line-argument]
[ 99%] Built target test_phase_2
/Users/a1/chia-plotter-master/src/chia_plot.cpp:16:10: fatal error: 'sodium.h' file not found
#include <sodium.h>
         ^~~~~~~~~~

**Comment by wxysystem32** [comment]
brew install libsodium

**Comment by juslex** [comment]
.c.o) has no symbols
[ 99%] Built target combined_custom
Consolidate compiler generated dependencies of target bls
[100%] Built target bls
Consolidate compiler generated dependencies of target chia_plot
[100%] Linking CXX executable chia_plot
clang: warning: argument unused during compilation: '-fmax-errors=1' [-Wunused-command-line-argument]
ld: library not found for -lsodium
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [chia_plot] Error 1
make[1]: *** [CMakeFiles/chia_plot.dir/all] Error 2
make: *** [all] Error 2

i was previous installed the lib sodium using the brew but I can't compile the binary
