### ISSUE TITLE
required space for ramdisk plotting only?

### ISSUE THREAD

**Issue by stubmirror** [madMAx43v3r/chia-plotter#123]
would i need 330gib ramdisk or is 220gib enough if i wanna test ram only?

**Comment by madMAx43v3r** [comment]
more like 330, not sure about the exact peak amount..

**Comment by msg7086** [comment]
I ran with 288GiB of memory with no swap, and plotting ends without issue. You can probably squeeze it further, down to about 265GiB area.

**Comment by madMAx43v3r** [comment]
ah yeah, that's because max disk usage of `tmpdir` and `tmpdir2` are not at the same time. `tmpdir2` has max usage at phase 1 tables 4 and 5, whereas `tmpdir` has max usage at end of phase 2.

**Comment by msg7086** [comment]
I was fully ramdisk, no SSD involved. In other words, tmpdir and tmpdir2 point to the same place.

The ramdisk was mounted by

```
mount -t tmpfs -o size=256G,nr_inodes=10000,mode=0755 tmpfs /root/mnt
```

And plotting command line is

```
/root/chia_plot --threads $cpu --tmpdir /root/mnt/chiya/ ...
```

Hope this clarifies.

**Comment by msg7086** [comment]
Actually, since I only allocate 256GiB on ramdisk mount, the actual disk usage is at or less than 256GiB. A bit more memory was needed to run the process, so I have to assign a bit more than 256GiB memory to make it work.

**Comment by madMAx43v3r** [comment]
Makes sense, good info to know.
