### ISSUE TITLE
  Given G1 non-infinity element must start with 0b10 Aborted (core dumped)

### ISSUE THREAD

**Issue by Exzellenz** [madMAx43v3r/chia-plotter#125]
I tried to run the plotter but i always get this message : 
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Given G1 non-infinity element must start with 0b10
Aborted (core dumped)
Can maybe someone give me a hint what is wrong there?  

Thank you

**Comment by madMAx43v3r** [comment]
pool key or farmer key wrong

**Comment by madMAx43v3r** [comment]
check `chia_plot --help`

**Comment by Exzellenz** [comment]
Yes aweseome thank you had a copy paste error in a key
