### ISSUE TITLE
Help - How To Run & Setup In Windows 

### ISSUE THREAD

**Issue by HPMSGEN8** [madMAx43v3r/chia-plotter#128]
Hi All

I need some help please on how to compile this in Windows and run on Windows.

Any help please.

Thanks

**Comment by MadCoderOne332** [comment]
same thanks

**Comment by winkee01** [comment]
Maybe you can try download enable WSL in windows, and download ubuntu from Windows Store

**Comment by HPMSGEN8** [comment]
Hi @winkee01 

Thanks alot so "https://docs.microsoft.com/en-us/windows/wsl/install-win10" ok will give this a try.

**Comment by HPMSGEN8** [comment]
Seems this does not work on Server 2012 R2.

Since i have a DL360 G7

**Comment by delucca** [comment]
Take a look at https://github.com/madMAx43v3r/chia-plotter/pull/102

You can try running it on Docker. But don't forget to setup proper RAM and CPU usage to your Docker config

**Comment by HPMSGEN8** [comment]
Hi @delucca 

Sorry but where is the IMG File and how is this all done as i do not see a ReadMe etc...

When it comes to Linux, Docker etc... I need alot of help :)

**Comment by delucca** [comment]
> Hi @delucca
> 
> Sorry but where is the IMG File and how is this all done as i do not see a ReadMe etc...
> 
> When it comes to Linux, Docker etc... I need alot of help :)

Sure

First you need to install Docker: https://docs.docker.com/docker-for-windows/install/

Them you just need to run:
```sh
docker run \
  -v <path-to-your-tmp-dir>:/mnt/harvester \
  -v <path-to-your-final-dir>:/mnt/farm \
  odelucca/chia-plotter \
    -t /mnt/harvester/ \
    -d /mnt/farm/ \
    -p <pool-key> \
    -f <farm-key>
```

In a terminal Window

**Comment by reducespeednow** [comment]
Thanks for the Docker image @delucca - all seems to be running well.

If this is of any use to anyone, this is what I plugged into powershell (all on one line and replacing mypoolkey and myfarmerkey with my actual keys):
`PS C:\Users\User\Desktop\plotter> docker run -m 30g -v E:\A\:/mnt/harvester -v E:\B\:/mnt/farm odelucca/chia-plotter -t /mnt/harvester/ -d /mnt/farm/ p mypoolkey -f myfarmerkey`

**Comment by delucca** [comment]
> Thanks for the Docker image @delucca - all seems to be running well.
> 
> If this is of any use to anyone, this is what I plugged into powershell (all on one line and replacing mypoolkey and myfarmerkey with my actual keys):
> `PS C:\Users\User\Desktop\plotter> docker run -m 30g -v E:\A\:/mnt/harvester -v E:\B\:/mnt/farm odelucca/chia-plotter -t /mnt/harvester/ -d /mnt/farm/ p mypoolkey -f myfarmerkey`

Just an update, if your Windows contain your CPU usage to Docker to 1 CPU you can use the `--cpus` to increase that!

**Comment by blueforever89** [comment]
Can I Use Option under with command docker run -m 30g -v E:\A\:/mnt/harvester -v E:\B\:/mnt/farm odelucca/chia-plotter -t /mnt/harvester/ -d /mnt/farm/ p mypoolkey -f myfarmerkey 
If they have different Option, Please guide me! Thanks you!



chia_plot [OPTION...]

  -n, --count arg      Number of plots to create (default = 1, -1 = infinite)
  -r, --threads arg    Number of threads (default = 4)
  -u, --buckets arg    Number of buckets (default = 128)
  -t, --tmpdir arg     Temporary directory, needs ~220 GiB (default = $PWD)
  -2, --tmpdir2 arg    Temporary directory 2, needs ~110 GiB [RAM] (default = <tmpdir>)
  -d, --finaldir arg   Final directory (default = <tmpdir>)
  -p, --poolkey arg    Pool Public Key (48 bytes)
  -f, --farmerkey arg  Farmer Public Key (48 bytes)
      --help           Print help

**Comment by reducespeednow** [comment]
As far as I'm aware, options for the plotter can go anywhere after `odelucca/chia-plotter` with options for docker going before that.

**Comment by blueforever89** [comment]
If i want -1 = infinite plot and 2 nd temp, and my command is 
docker run -n -1 -m 30g -v E:\A\:/mnt/harvester -v E:\B\:/mnt/temp2 -v E:\C\:/mnt/farm odelucca/chia-plotter -t /mnt/harvester/ -2 /mnt/temp2 -d /mnt/farm/ p mypoolkey -f myfarmerkey

what does this mean?  "-m 30g "

Thanks you!

**Comment by reducespeednow** [comment]
I'm currently plotting on a Poweredge R610 with 32GB of memory so `-m 30g` gives it 30GB of ram to use. Probably too much though as it hasn't really gone over 12GB.

**Comment by delucca** [comment]
Here is a quick overview of the docker run syntax:

`docker run <run-args> odelucca/chia-plotter <plotter-args>`

Anything before `odelucca/chia-plotter` (the Docker image name) goes as a `docker run` argument, everything after it goes as a `chia-plotter` argument

**Comment by blueforever89** [comment]
And final How I can stop command in powershell ? @reducespeednow , @delucca Thanks!

**Comment by delucca** [comment]
> And final How I can stop command in powershell ? @reducespeednow , @delucca Thanks!

`Ctrl + C`

**Comment by blueforever89** [comment]
I am running Phase 2, How i can stop it? Ctrl + C not stop.

**Comment by delucca** [comment]
> I am running Phase 2, How i can stop it? Ctrl + C not stop.

Strange 🤔 probably If you just close the Terminal window it will stop.

**Comment by delucca** [comment]
> HI @delucca
> 
> Since i am running Windows Server 2012 R2 & 2016 I cannot seem to get docker installed :(

:( that's sad

Well, probably in the near future they're going to create a Windows executable, or even Chia will merge with this plotter!

**Comment by HPMSGEN8** [comment]
Well i will just install Hyper-V and an Windows 10 OS and then give this a Try :) 

If it comes to it even make an ESXI Host and Windows 10 will see how i get on :)

**Comment by blueforever89** [comment]
docker run -m 30g -v A:\A\:/mnt/harvester -v B:\B\:/mnt/harvester1 -v G:\G\:/mnt/farm odelucca/chia-plotter -t /mnt/harvester/ -2 /mnt/harvester1 -d /mnt/farm/ -p  -f  -n -1 -r 12      
Run error (needs trailing '/' or '\'), How i fix it? Thanks!

**Comment by delucca** [comment]
> docker run -m 30g -v A:\A:/mnt/harvester -v B:\B:/mnt/harvester1 -v G:\G:/mnt/farm odelucca/chia-plotter -t /mnt/harvester/ -2 /mnt/harvester1 -d /mnt/farm/ -p -f -n -1 -r 12
> Run error (needs trailing '/' or '\ '), How i fix it? Thanks!

```
docker run -m 30g -v A:\A:/mnt/harvester -v B:\B:/mnt/harvester1 -v G:\G:/mnt/farm odelucca/chia-plotter -t /mnt/harvester/ -2 /mnt/harvester1/ -d /mnt/farm/ -p -f -n -1 -r 12
```

The `-2` command needs a `/` in the end.

@madMAx43v3r IMHO we should address this scenario to automatically add a trailing slash

**Comment by leegee333** [comment]
So the 'odelucca/chia-plotter' part runs the madMAx43v3r plotter?

**Comment by madMAx43v3r** [comment]
> IMHO we should address this scenario to automatically add a trailing slash

Well not every OS uses the same slash... that's why I don't add it

**Comment by delucca** [comment]
> Ahh. So I'm running your (odelucca) docker image (chia-plotter) on my server

Exactly, Docker is just a container structure. You're basically adding a box inside your server that runs madmax chia-plotter.

That "box" being named `odelucca/chia-plotter` has nothing to do with it's content. It could be named `strawberry` and would have the same effect.

**Comment by leegee333** [comment]
Thanks delucca

**Comment by delucca** [comment]
Glad to help!

**Comment by winkee01** [comment]
maybe you can try this compiled version, run it on Powershell or cmd, don't just click it to run.
https://mega.nz/file/5RkDQYDA#C_KtwODwe7Ki7HieBb1ALx6PMPfapjmPegSQbVmsEV4

**Comment by HPMSGEN8** [comment]
Hi @delucca 

Ok so let me start off and say thanks :)

I installed Windows 10 Pro on my Server and followed the steps where i got it working. 1 thing i do notice is that it does not show how to get your keys. 

So open cmd or powershell. Change 1.1.6 -> To Your Version

cd" C:\Users\YOUR-NAME\AppData\Local\chia-blockchain\app-1.1.6\resources\app.asar.unpacked\daemon

chia.exe keys show

OUTPUT .....

I have it running with 80GB RAM & 4 Threads. How do i get this to use 8 Threads as this is what i have now. I will have 24 next week i hope :) 

Thanks

**Comment by delucca** [comment]
> Hi @delucca
> 
> Ok so let me start off and say thanks :)
> 
> I installed Windows 10 Pro on my Server and followed the steps where i got it working. 1 thing i do notice is that it does not show how to get your keys.
> 
> So open cmd or powershell. Change 1.1.6 -> To Your Version
> 
> cd" C:\Users\YOUR-NAME\AppData\Local\chia-blockchain\app-1.1.6\resources\app.asar.unpacked\daemon
> 
> chia.exe keys show
> 
> OUTPUT .....
> 
> I have it running with 80GB RAM & 4 Threads. How do i get this to use 8 Threads as this is what i have now. I will have 24 next week i hope :)
> 
> Thanks

Docker doesn't contain your CPU/memory usage unless you told it specifically to do so. So, in theory, you need to do nothing to use all cores.

But, you need to double-check, since you could accidentally apply a config that can constraint the amount of CPU/memory. You could easily check that inside Docker settings

Some folks are complaining regarding WSL IO bottleneck. While installing Docker you can run the WSL2 backend or the HyperV backend. You need to follow the steps to use the HyperV backend and be sure to deactivate the WSL2 backend inside the Docker settings.

If you don't do that, the WSL2 will limit your SSD throughput.

Some other users are reporting that even HyperV limits the SSD speed (but less than WSL2) and they're trying to tweak Docker to use WSL1 (which does not limit SSD speed). But I have no idea how to do it

**Comment by HPMSGEN8** [comment]
Thanks alot will go and setup the Hyper-V Backend and see what happens.

Right now i am not using an SSD i am using SAS Disks as an test to see what will work as i have seen some good results with SAS 10K & 15K Disks.

Are you going to make an Docker Image where it can Auto Update on changes or pull it like you get with Synology & Docker ? 

Thanks again for all your help and support on this :)

**Comment by delucca** [comment]
> Thanks alot will go and setup the Hyper-V Backend and see what happens.
> 
> Right now i am not using an SSD i am using SAS Disks as an test to see what will work as i have seen some good results with SAS 10K & 15K Disks.
> 
> Are you going to make an Docker Image where it can Auto Update on changes or pull it like you get with Synology & Docker ?
> 
> Thanks again for all your help and support on this :)

I'm planning to create a simple script where you could add your harvester configs and it would automatically start plotting for you!

**Comment by HPMSGEN8** [comment]
Hi @delucca 

I do not know what is going on. I removed WSL 2 in Docker to test with Hyper-V.

I have the commands setup to use my SSD for Temp1 and How do i get my RAM to get used for TEMP2 or my 10K SAS Disks.

I think i am doing something wrong as i have -m 80g --cpus 4 even thou i have 8 threads and it is not using this. 

Any help on this please :) 

Thanks

**Comment by delucca** [comment]
> Hi @delucca
> 
> I do not know what is going on. I removed WSL 2 in Docker to test with Hyper-V.
> 
> I have the commands setup to use my SSD for Temp1 and How do i get my RAM to get used for TEMP2 or my 10K SAS Disks.
> 
> I think i am doing something wrong as i have -m 80g --cpus 4 even thou i have 8 threads and it is not using this.
> 
> Any help on this please :)
> 
> Thanks

Hey!

Yesterday after some digging I found out that even with HyperV Docker in Windows still has IO boundaries =/

You would need to find a way to run inside WSL1, that has no IO bound. Or you could use @stotiks binary directory: https://github.com/stotiks/chia-plotter/releases/tag/v0.0.4

**Comment by HPMSGEN8** [comment]
Thanks let me check

**Comment by HPMSGEN8** [comment]
All Solved :)
