### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by Phlexx0** [madMAx43v3r/chia-plotter#14]
Is it possible to use this on windows?

**Comment by RamonRobben** [comment]
@Phlexx0 you can use this on Windows if you have WSL2 installed.

**Comment by Phlexx0** [comment]
> @Phlexx0 you can use this on Windows if you have WSL2 installed.

Thanks, i managed to istall WSL2 and cmake/make pacages however now i get "No CMAKE_CXX_COMPILER could be found."

**Comment by RamonRobben** [comment]
@Phlexx0 Please check issue #10 for a solution

**Comment by Phlexx0** [comment]
`git submodule update --init`

Fixed the issue
