### ISSUE TITLE
Installation of deps

### ISSUE THREAD

**Issue by mist0706** [madMAx43v3r/chia-plotter#15]
I'm guessing the binary needs a bunch of libraries seeing as i can't launch this from the commandline. Can we have a make install file so that it can be launched from anywhere?

Actually i moved the chia_plot binary and launching it alone is fine. It just can't be launched with a path. Then you get the following error:

> mist@fp-plotty5:~/chia-plotter$ ./build/chia_plot 80ee566ed528d0909a3d6ff700d64360ee10408afaf032355fffa51af740cb7525e304ddd7749d5e61d1e01a1cd328db a9409b401b4ffcb066cc80d96d869593526d636cdcf22d970e242b3498ed02ca04a13b7e16d1e90f863bd1d917d70ea4 /drive1/ /tmp/ramdisk/ 8
> Number of Threads: 8
> Number of Sort Buckets: 2^7 (128)
> Pool Public Key:   80ee566ed528d0909a3d6ff700d64360ee10408afaf032355fffa51af740cb7525e304ddd7749d5e61d1e01a1cd328db
> Farmer Public Key: a9409b401b4ffcb066cc80d96d869593526d636cdcf22d970e242b3498ed02ca04a13b7e16d1e90f863bd1d917d70ea4
> Working Directory:   /drive1/
> Working Directory 2: /tmp/ramdisk/
> Plot Name: plot-k32-2021-06-07-12-50-3a922a4e1416ea8b062c23b17315e72034714bbe8f429c1afe87bb362c4e859a
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  thread failed with: thread failed with: fwrite() failed
> Aborted

**Comment by Hardcore-fs** [comment]
yep.. it needs some llvm multi processing libraries

**Comment by mist0706** [comment]
Solved
