### ISSUE TITLE
is the loss of so many due to overflow correct?

### ISSUE THREAD

**Issue by Hardcore-fs** [madMAx43v3r/chia-plotter#17]
using the base code and running P1
procuces losses due to over flow
![p1](https://user-images.githubusercontent.com/1309004/121012698-927e3d00-c7ca-11eb-81e3-d45d59015efc.png)

is this correct or is there a "cast" missing?

**Comment by madMAx43v3r** [comment]
It's normal, nothing to worry about. The final plot will be a tiny bit smaller but thats it. Sometimes there is losses, sometimes not, depends on plot id.

**Comment by HomeLH** [comment]
@madMAx43v3r Is this a bug?

**Comment by madMAx43v3r** [comment]
No it's intentional, I would have to store an additional bit (and thus one more byte) to avoid it. A lot of cost for almost nothing. It's not defined how big exactly a plot has to be, it varies with plot id anyways due to the random nature of the hash functions.

**Comment by madMAx43v3r** [comment]
100e+3 compared to 4.3e+9 is nothing, like ~0.02%.

**Comment by Hardcore-fs** [comment]
by the end of the process.
it looks like this...
never mind the ppeed , its on a really slow drive

![p2](https://user-images.githubusercontent.com/1309004/121087131-9cc62880-c816-11eb-84d4-164a63bfe2c8.png)

**Comment by madMAx43v3r** [comment]
looks fine to me, but why are you using test_phase_x? that was just for development, check out `chia_plot` binary.

**Comment by Hardcore-fs** [comment]
baby steps...... baby steps...
that was from yesterday, i'm going thru the latest now.....
