### ISSUE TITLE
std:invalid_argument

### ISSUE THREAD

**Issue by jonaspt1** [madMAx43v3r/chia-plotter#170]
Hello,
i am having problems starting the chia_plot.

Code: ./chia_plot -p xxx -f xxx -t /media/user/m.2/ -2 /mnt/ramdisk/ -d /media/user/Final/

Error: Terminate called after throwing an instance of "std:invalid_argument"
what(): G1 element is invalid
aborted (core dumped)

can someone help me?

thank you
![Unbenannt](https://user-images.githubusercontent.com/85516274/121571938-f0599180-ca23-11eb-9fca-36eeba47eb27.png)

**Comment by madMAx43v3r** [comment]
your keys are invalid, make sure you copy the right ones, from `chia keys show`, pool public + farmer public

**Comment by jonaspt1** [comment]
Thank you for your fast answer.

i already did that and it doesn't work
![Unbenanasdasdnt](https://user-images.githubusercontent.com/85516274/121574988-1fbdcd80-ca27-11eb-8ef4-296406f616cb.png)



![Unbenan231nt](https://user-images.githubusercontent.com/85516274/121574637-c2c21780-ca26-11eb-9d6d-c9be23c2842b.png)

**Comment by jonaspt1** [comment]
Omg wasting your time guys sorry :(

Thanks for the help
