### ISSUE TITLE
Close solved issues

### ISSUE THREAD

**Issue by HitLuca** [madMAx43v3r/chia-plotter#173]
Sorry if I need to open an issue, but it seems the most straightforward way to do it: I started using this plotter and it's a-ma-zing. I was sure there had to be a better way to make plots, and this just shows what people can achieve (from 16 plots a day up to 24 baby!)

Anyway, the first time I checked this repo I noticed 50+ open issues, and this got me a bit worried about the compatibility and stability of this plotter. Since most of the open issues are already solved (like [this one](https://github.com/madMAx43v3r/chia-plotter/issues/151)), closing them would avoid new potential users having to read through each issue to make sure there isn't a game breaking bug or similar!

Again, awesome work

**Comment by madMAx43v3r** [comment]
yeah it's more of a discussion and support forum over here

**Comment by HitLuca** [comment]
You may add a pointer in the Readme to the discussions section, since that page is also crowded looks like.
