### ISSUE TITLE
Request: Add option to stop after current plot

### ISSUE THREAD

**Issue by devedse** [madMAx43v3r/chia-plotter#183]
Would it be possible to add an option to automatically stop after the current plot creation + copy to destination directory has been completed?

E.g. if you type "e" + enter or something?

**Comment by madMAx43v3r** [comment]
it's possible yes, I take it as a todo

**Comment by devedse** [comment]
Thnx :)

**Comment by cyperbg** [comment]
Why not use Ctrl+C?

**Comment by VertiHydro** [comment]
> Why not use Ctrl+C?

Because you don't want to ruin the currently running plot, you don't want to let it start a new plot and put hundreds of temp files everywhere cluttering your drive, and you don't want to sit in front of your computer waiting for the precise moment when one plot finishes and the other starts. This is not an essential feature, but it may be useful.

**Comment by F1DNA** [comment]
It also doesn't work that way, there is never a time for a clean break as running "-n -1", a new plot process will start before the copy job finishes.  I also noticed that if there are 2 copy jobs in queue, it will pause before starting another plot until you only have 1 copy job waiting.  This was a pleasant surprise for me as my bottleneck is moving things across my the network and I was concerned that I would run into issues with finished plots piling up while they wait to get transferred.  The way he set this up, it's almost like you have a built in plotman running.

**Comment by madMAx43v3r** [comment]
> I was concerned that I would run into issues with finished plots piling up while they wait to get transferred

Exactly, that's why it's waiting

**Comment by fermosan** [comment]
it's done. we can cllose this

**Comment by kacperapi** [comment]
It would be cool if there would be still possibitily to shut it down "hard" way. Right now if the software bugs and gets stuck - you can't stop it at all as it will wait until plot is finished ( infinity )

**Comment by cyperbg** [comment]
> It would be cool if there would be still possibitily to shut it down "hard" way. Right now if the software bugs and gets stuck - you can't stop it at all as it will wait until plot is finished ( infinity )

Just kill chia_plot in System Monitor/Task Manager

**Comment by kacperapi** [comment]
> > It would be cool if there would be still possibitily to shut it down "hard" way. Right now if the software bugs and gets stuck - you can't stop it at all as it will wait until plot is finished ( infinity )
> 
> Just kill chia_plot in System Monitor/Task Manager

Would be handy if you wouldn't have to constantly close around 60 processes :) since it starts to open new threads. This issue shouldn't be closed without emergency shutdown.

**Comment by Forusim** [comment]
> > > It would be cool if there would be still possibitily to shut it down "hard" way. Right now if the software bugs and gets stuck - you can't stop it at all as it will wait until plot is finished ( infinity )
> > 
> > 
> > Just kill chia_plot in System Monitor/Task Manager
> 
> Would be handy if you wouldn't have to constantly close around 60 processes :) since it tries to open new threads - it's almost impossible to close without reboot. This issue shouldn't be closed without emergency shutdown.

What OS are you running? In Ubuntu `top` I see only 1 process chia_plot with multiple threads. Just kill the PID and you are done.

**Comment by kacperapi** [comment]
> > > > It would be cool if there would be still possibitily to shut it down "hard" way. Right now if the software bugs and gets stuck - you can't stop it at all as it will wait until plot is finished ( infinity )
> > > 
> > > 
> > > Just kill chia_plot in System Monitor/Task Manager
> > 
> > 
> > Would be handy if you wouldn't have to constantly close around 60 processes :) since it tries to open new threads - it's almost impossible to close without reboot. This issue shouldn't be closed without emergency shutdown.
> 
> What OS are you running? In Ubuntu `top` I see only 1 process chia_plot with multiple threads. Just kill the PID and you are done.

You are comparing your situation where everything works to some type of bug situation that is completely uncontrolled.
But here you are:
![image](https://user-images.githubusercontent.com/32944015/121815784-6c4c1780-cc78-11eb-89f4-378ac9276215.png)

And killing PID 24180 doesn't stop the process or making new ones. It's just impossible to kill.

**Comment by Forusim** [comment]
Looks like an issue with your plotting manager /script, but would not `killall chia_plot` be sufficient?

**Comment by kacperapi** [comment]
> Looks like an issue with your plotting manager /script, but would not `killall chia_plot` be sufficient?
This is normal build directly from git not any plotting manager/script. and no killall chia_plot doesnt fix it. It's just perma stuck after this Issue has been "resolved" by @madMAx43v3r
