### ISSUE TITLE
Continue plotting while copying

### ISSUE THREAD

**Issue by PuppyLover101** [madMAx43v3r/chia-plotter#187]
Seems like some of my plotters [aren't doing anything ](https://i.imgur.com/ojpePi9.png) as they are [busy copying ](https://i.imgur.com/XzWBHZq.png) over the completed plot to the destination drive.

Considering that there is just one plot being made at a time (generally), can we continue plotting away while moving it to the destination drive?

**Comment by GTANAdam** [comment]
This can be solved by using a plotting manager and a fast buffer storage such as an SSD

**Comment by madMAx43v3r** [comment]
check the `-n` parameter

**Comment by PuppyLover101** [comment]
-n is set to -1 (infinite), and yeah fast buffer storage is used, however via network. seems like my gigabit lines are clogged due to the amount of transfers. atm taking an average of 3 hours to copy plots, will look into staggering them in order to reduce concurrent load, was just being hopeful here though.

thanks!

**Comment by madMAx43v3r** [comment]
ah I see, yeah if the copy takes longer than plot creation time it will wait before the previous copy is done, otherwise you'll run out of disk space quick.

**Comment by PuppyLover101** [comment]
gotcha, thanks.
