### ISSUE TITLE
Issue on the Installation - Ubuntu

### ISSUE THREAD

**Issue by canaltuncu** [madMAx43v3r/chia-plotter#199]
Hi guys, anyone having issues running this command on ubuntu?  That is suggested on the installation part.

git submodule update --init

I tried it on two computers but one of them does not seem to run the command even though it doesn't give any error and jumps onto the next command line which is not the right output. Then the two other commands don't run / give errors.

./make_devel.sh
./build/chia_plot  --help

If there are any other ways to install, that would also be appreciated as well.

Thanks.

$ sudo apt install  -y libsodium-dev  libgmp3-dev  cmake g++ git
[sudo] password for ja1: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
git is already the newest version (1:2.25.1-1ubuntu3.1).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 g++ : Depends: g++-9 (>= 9.3.0-3~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by VertiHydro** [comment]
`sudo apt-get install build-essential`

**Comment by canaltuncu** [comment]
> `sudo apt-get install build-essential`

I think I'm following the same route, finding similar topics about this but, here's the output I received after running.

sudo apt-get install build-essential
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 build-essential : Depends: libc6-dev but it is not going to be installed or
                            libc-dev
                   Depends: g++ (>= 4:9.2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by VertiHydro** [comment]
Try the following:
`sudo apt-get clean
sudo apt update
sudo apt upgrade
sudo apt install libc6-dev g++
sudo apt install build-essential`

**Comment by canaltuncu** [comment]
> Try the following:
> `sudo apt-get clean`
> `sudo apt update`
> `sudo apt upgrade`
> `sudo apt install libc6-dev g++`
> `sudo apt install build-essential`

All good until the 4th command

ja1@ja1-PowerEdge-R820:~$ sudo apt install libc6-dev g++
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libc6-dev : Depends: libc6 (= 2.31-0ubuntu9) but 2.31-0ubuntu9.2 is to be installed

**Comment by msg7086** [comment]
Sounds like you have a problem with your mirrors list or system. This is more of a Ubuntu related issue, and has nothing to do with this project. You can try `apt policy libc6 libc6-dev` and see if you observe strange result. Sounds like you have issues installing packages from `focal-update` repo.

**Comment by canaltuncu** [comment]
> Sounds like you have a problem with your mirrors list or system. This is more of a Ubuntu related issue, and has nothing to do with this project. You can try `apt policy libc6 libc6-dev` and see if you observe strange result. Sounds like you have issues installing packages from `focal-updates` repo.

I'm guessing it's an Ubuntu related issue as well but the system is recently installed. I can't see what the issue can be.
Here's the output of the command:
I guess, I'll try to find how I can install libc6-dev

ja1@ja1-PowerEdge-R820:~$ apt policy libc6 libc6-dev
libc6:
  Installed: 2.31-0ubuntu9.2
  Candidate: 2.31-0ubuntu9.2
  Version table:
 *** 2.31-0ubuntu9.2 100
        100 /var/lib/dpkg/status
     2.31-0ubuntu9 500
        500 http://us.archive.ubuntu.com/ubuntu focal/main amd64 Packages
libc6-dev:
  Installed: (none)
  Candidate: 2.31-0ubuntu9
  Version table:
     2.31-0ubuntu9 500
        500 http://us.archive.ubuntu.com/ubuntu focal/main amd64 Packages

**Comment by canaltuncu** [comment]
It worked out after I was able to downgrade one of the packages.
Then I was able to run all the lines shown under the code section for maxplotter.
Thanks all.

R820:~$ sudo aptitude install g++
The following NEW packages will be installed:
  g++ g++-9{a} libc-dev-bin{a} libc6-dev{ab} libcrypt-dev{a} libstdc++-9-dev{a} linux-libc-dev{a} 
0 packages upgraded, 7 newly installed, 0 to remove and 0 not upgraded.
Need to get 14.0 MB of archives. After unpacking 73.1 MB will be used.
The following packages have unmet dependencies:
 libc6-dev : Depends: libc6 (= 2.31-0ubuntu9) but 2.31-0ubuntu9.2 is installed
The following actions will resolve these dependencies:

     Keep the following packages at their current version:
1)     g++ [Not Installed]                                
2)     g++-9 [Not Installed]                              
3)     libc6-dev [Not Installed]                          
4)     libstdc++-9-dev [Not Installed]                    



Accept this solution? [Y/n/q/?] n
The following actions will resolve these dependencies:

     Downgrade the following packages:                           
1)     libc6 [2.31-0ubuntu9.2 (now) -> 2.31-0ubuntu9 (focal)]    
2)     libc6-dbg [2.31-0ubuntu9.2 (now) -> 2.31-0ubuntu9 (focal)]



Accept this solution? [Y/n/q/?] 1
Action "1": Installing libc6 2.31-0ubuntu9 (focal)

Package: libc6
Version: 2.31-0ubuntu9
State: installed (2.31-0ubuntu9.2), upgrade available (2.31-0ubuntu9)
Automatically installed: no
Multi-Arch: same
Priority: required
Section: libs
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Uncompressed Size: 13.6 M
Depends: libgcc-s1, libcrypt1 (>= 1:4.4.10-10ubuntu4)
Recommends: libidn2-0 (>= 2.0.5~)
Suggests: glibc-doc, debconf | debconf-2.0, locales
Conflicts: openrc (< 0.27-2~)
Breaks: hurd (< 1:0.9.git20170910-1), iraf-fitsutil (< 2018.07.06-4), libtirpc1 (< 0.2.3), locales (< 2.31), locales-all (< 2.31), nocache (< 1.1-1~), nscd (< 2.31),
        r-cran-later (< 0.7.5+dfsg-2), wcc (< 0.0.2+dfsg-3), locales:i386 (< 2.31), libc6:i386 (!= 2.31-0ubuntu9), locales-all:i386 (< 2.31), nscd:i386 (< 2.31)
Replaces: libc6-amd64, libc6-amd64:i386, libc6:i386 (< 2.31-0ubuntu9), libc6-amd64:x32, libc6-amd64:x32-i386-cross, libc6-amd64:i386-x32-cross
Description: GNU C Library: Shared libraries
 Contains the standard libraries that are used by nearly all programs on the system. This package includes shared versions of the standard C library and the standard
 math library, as well as many others.
Homepage: https://www.gnu.org/software/libc/libc.html


This action was selected because libc6-dev depends upon libc6 (= 2.31-0ubuntu9).

Enter "r 1" to prevent this action from appearing in new solutions.
Enter "a 1" to require that new solutions include this action if possible.

Accept this solution? [Y/n/q/?] y
The following packages will be DOWNGRADED:
  libc6 libc6-dbg 
The following NEW packages will be installed:
  g++ g++-9{a} libc-dev-bin{a} libc6-dev{a} libcrypt-dev{a} libstdc++-9-dev{a} linux-libc-dev{a} 
0 packages upgraded, 7 newly installed, 2 downgraded, 0 to remove and 0 not upgraded.
Need to get 22.3 MB of archives. After unpacking 41.8 MB will be used.
Do you want to continue? [Y/n/?] y

**Comment by pranshu-taneja** [comment]
@canaltuncu  Thank you so much!! Finally I resolved the issue.
