### ISSUE TITLE
CentOS 7: missing word in command line

### ISSUE THREAD

**Issue by hardhub** [madMAx43v3r/chia-plotter#200]
`sudo yum centos-release-scl -y`

`sudo yum install centos-release-scl -y`

**Comment by hardhub** [comment]
Also I had to manually change cmake to cmake3 inside sh building scripts.

**Comment by madMAx43v3r** [comment]
first issue fixed, cmake3 cannot be hardcoded...

**Comment by hardhub** [comment]
> 
> 
> first issue fixed, cmake3 cannot be hardcoded...

But cmake is not found even if I do all exactly as in instruction.

**Comment by madMAx43v3r** [comment]
this is fixed right? check latest readme

**Comment by hardhub** [comment]
Yes, think so.
