### ISSUE TITLE
Spreading the word…

### ISSUE THREAD

**Issue by Dartellum** [madMAx43v3r/chia-plotter#21]
I have only compiled, yesterday's version, as my hardware is old except my ETH rigs. Anyway, not an issue but letting you know I have spread your GitHub to a few Discord channels. Lots of testing is going on with various hardware. I plan on joining this testing to and your program may have changed what I purchase. 

How many instances can we run in parallel? Or, should run? Even at 2 hrs a complete plot, running sequentially will only yield 12 plots. I was going with HP DL380, 128 GB RAM, and 25x SAS 15k 300 GB drives for temp drives. This would yield 40 to 50 plots (based on what others have done with simply setup). Suggestions?

**Comment by madMAx43v3r** [comment]
I can recommend 256 GB RAM + 2 NVMe/SATA SSD, running two plots in parallel each with a 110G RAM drive as `tmp_dir2`, staggered to overlap phase 1 and 3 (roughly). All those 15k drives will only draw power for no good reason.

I have a Dell R720 with that setup (dual 8-core E5v2) and it looks like I'm getting about 40 plots/day.

**Comment by madMAx43v3r** [comment]
Essentially, focus on CPU power + RAM. SSD requirements are quite low if you use RAM for `tmp_dir2`.

**Comment by Dartellum** [comment]
I will revise my quote requirements. 😀

**Comment by Dartellum** [comment]
Okay, RFQ revised and now onward to ordering. 

Anyway, I believe I have converted many to your plotter. 😀 Thanks for doing this!

**Comment by Hardcore-fs** [comment]
all you are doing is destroying your own ability to farm.....
the  faster people fill drives with plots, the more you have to compete....
once the mainlanders see this , it will be game over..., their only current constraint is plotting...
storage is "free" if it's not being used..., whereas CPU time is  monitored.

**Comment by dipique** [comment]
> all you are doing is destroying your own ability to farm.....
> the faster people fill drives with plots, the more you have to compete....
> once the mainlanders see this , it will be game over..., their only current constraint is plotting...
> storage is "free" if it's not being used..., whereas CPU time is monitored.

“Mainlanders” yeah okay

**Comment by digitalscream** [comment]
Alternatively, it's a bit complex, but you can put together a non-ramdisk, non-SSD solution which also works very well.

Using 6 x SAS 10k 300GB drives in two RAID0 arrays, I can run two in parallel using half the cores in my dual E5-2450 machine (four cores for each process, forced using taskset), with tmp1 and tmp2 on different arrays for each process. This results in sub-3hr plots, and should scale almost exactly to four parallel processes, thus hitting 32+ plots per day on a machine that could only manage 12-14 plots per day using plotman and the official plotter.

**Comment by Dartellum** [comment]
Closing. :smile:
