### ISSUE TITLE
Running plotter locks up server

### ISSUE THREAD

**Issue by Spektre99** [madMAx43v3r/chia-plotter#212]
System specification:  2xE5-2690v1, 64G, plotting to RAID0 array SAS drives, Ubuntu Desktop 20.0.4

How to reproduce:  run plotter  with any number of threads specified(1-32)

Outcome:  Plotter runs and completes Table 1.   Shortly following this, all disk IO stops and the GUI freezes.  Server requires a hard power reboot.

**Comment by madMAx43v3r** [comment]
do you use a ramdisk? if yes you probably running out of RAM

**Comment by Spektre99** [comment]
I do not.  I only have 64G.  I am plotting on 2 10k SAS drives.  one for temp1 and destination 1 for temp2

**Comment by madMAx43v3r** [comment]
after table 1, cpu load will spike, maybe unstable RAM, power supply, CPU issue?

**Comment by Spektre99** [comment]
This appears to have been caused by a faulty RAID0 array.
