### ISSUE TITLE
Write to tmpdir and docker memory limit errors

### ISSUE THREAD

**Issue by EnderElement** [madMAx43v3r/chia-plotter#219]
I'm using docker on windows 10. I'm using this command (with keys ofc), and after pulling the image I get the following error: 
docker run -v P:/mnt/harvester -v D:/mnt/farm --cpus 8 odelucca/chia-plotter -t /mnt/harvester/ -d /mnt/farm/ -p {pool key} -f {farm key} -r 8
Failed to write to <tmpdir> directory: '/mnt/harvester/'

If I add -m 64000 (as I have 64GB RAM) to the command after docker run, I get this error:
docker: Error response from daemon: Minimum memory limit allowed is 6MB.

I'm fairly new to this stuff and I'm not sure if what I'm doing is right. I assume as I'm on windows I could skip the install section and just use docker.

**Comment by VertiHydro** [comment]
> I'm using docker on windows 10. I'm using this command (with keys ofc), and after pulling the image I get the following error:
> docker run -v P:/mnt/harvester -v D:/mnt/farm --cpus 8 odelucca/chia-plotter -t /mnt/harvester/ -d /mnt/farm/ -p {pool key} -f {farm key} -r 8
> Failed to write to directory: '/mnt/harvester/'
> 
> If I add -m 64000 (as I have 64GB RAM) to the command after docker run, I get this error:
> docker: Error response from daemon: Minimum memory limit allowed is 6MB.
> 
> I'm fairly new to this stuff and I'm not sure if what I'm doing is right. I assume as I'm on windows I could skip the install section and just use docker.

Are you using the HyperV or WSL2 backend for docker?

**Comment by djdd87** [comment]
I think -m needs "m" on the end of the value to specify it's MB:

```-m 64000m```

See [docs](https://docs.docker.com/config/containers/resource_constraints/#limit-a-containers-access-to-memory).

**Comment by EnderElement** [comment]
> I think -m needs "m" on the end of the value to specify it's MB:
> 
> `-m 64000m`
> 
> See [docs](https://docs.docker.com/config/containers/resource_constraints/#limit-a-containers-access-to-memory). This got it working for me as I had the same error.

This fixed it, thanks!

**Comment by EnderElement** [comment]
> > I'm using docker on windows 10. I'm using this command (with keys ofc), and after pulling the image I get the following error:
> > docker run -v P:/mnt/harvester -v D:/mnt/farm --cpus 8 odelucca/chia-plotter -t /mnt/harvester/ -d /mnt/farm/ -p {pool key} -f {farm key} -r 8
> > Failed to write to directory: '/mnt/harvester/'
> > If I add -m 64000 (as I have 64GB RAM) to the command after docker run, I get this error:
> > docker: Error response from daemon: Minimum memory limit allowed is 6MB.
> > I'm fairly new to this stuff and I'm not sure if what I'm doing is right. I assume as I'm on windows I could skip the install section and just use docker.
> 
> Are you using the HyperV or WSL2 backend for docker?

Im using both HyperV and WSL2 since docker says HyperV won't work if I disable WSL2
![image](https://user-images.githubusercontent.com/29475587/121683749-26b90e80-cb01-11eb-9b13-2b49ee51a0ab.png)

**Comment by EnderElement** [comment]
I solved this by fixing the slashes for directorys to the correct windows format. Basically changing "/" to "\". New working and correct command is:

docker run -v P:\mnt\harvester -v D:\mnt\farm --cpus 8 odelucca/chia-plotter -t \mnt\harvester\ -d \mnt\farm\ -p {pool key} -f {farm key} -r 8

With this the plotter now works.
