### ISSUE TITLE
a fatal error: sodium.h

### ISSUE THREAD

**Issue by rongyuv** [madMAx43v3r/chia-plotter#220]
When i ran 'make_devel.sh ',got: chia_plot.cpp:16:10: fatal error: sodium.h: No such file or directory
 #include <sodium.h>

**Comment by ChrisScheffler** [comment]
> When i ran 'make_devel.sh ',got: chia_plot.cpp:16:10: fatal error: sodium.h: No such file or directory
> #include <sodium.h>

Did you install **libsodium-dev** (see [Dependencies](https://github.com/madMAx43v3r/chia-plotter#dependencies))?

**Comment by rongyuv** [comment]
I see, thx.
