### ISSUE TITLE
thread failed with: input not sorted

### ISSUE THREAD

**Issue by Soullnik** [madMAx43v3r/chia-plotter#225]
## i have ryzen 3600 and run plotter with 4 thread on plot
![image](https://user-images.githubusercontent.com/52292226/121660008-87b5f780-caab-11eb-8ffb-ac654ac6cb54.png)

**Comment by VertiHydro** [comment]
Hmmm... Are you sure you on the latest version? This should have been fixed in https://github.com/madMAx43v3r/chia-plotter/commit/3b553d3548f44708e4fa9ddd80b45bae2ba756e3

**Comment by madMAx43v3r** [comment]
3b553d3548f44708e4fa9ddd80b45bae2ba756e3 is something else, that error could be caused by unstable RAM or drive failure

**Comment by Soullnik** [comment]
i update repo and create new build. thx for help
