### ISSUE TITLE
Can't complie plotter on Windows

### ISSUE THREAD

**Issue by Sonit90** [madMAx43v3r/chia-plotter#23]
```
mkdir -p build

cd build

cmake -D CMAKE_CXX_FLAGS="-g -O3 -fmax-errors=1" -DBUILD_BLS_PYTHON_BINDINGS=false ..
```

Everything works fine with the above code, but my comand line can't handle 

```
make -j8 $@
```
i am getting 
```
make: *** No rule to make target '$@'.  Stop.
```

if it try to make an app using a make file, I am getting following error:
```
$ make -f ./cmake_install.cmake
cmake_install.cmake:4: *** missing separator.  Stop.
```

**Comment by ArtrixTech** [comment]
Same here.

**Comment by Sonit90** [comment]
So i resolved the issue by installing WSL 2 for windows.
Basically i installed Ubuntu on my K:\ drive, then i launched ubuntu, builded the project, and then mounted my windows drive to /mnt/k and since then everything works.

**Comment by never-afk** [comment]
> So i resolved the issue by installing WSL 2 for windows.
> Basically i installed Ubuntu on my K:\ drive, then i launched ubuntu, builded the project, and then mounted my windows drive to /mnt/k and since then everything works.

in fact,that's not a win32 program

**Comment by VertiHydro** [comment]
> So i resolved the issue by installing WSL 2 for windows.
> Basically i installed Ubuntu on my K:\ drive, then i launched ubuntu, builded the project, and then mounted my windows drive to /mnt/k and since then everything works.

Your performance will be much worse than if you use the Docker container that @delucca made - https://github.com/madMAx43v3r/chia-plotter/pull/102

**Comment by ArtrixTech** [comment]
> So i resolved the issue by installing WSL 2 for windows.
> Basically i installed Ubuntu on my K:\ drive, then i launched ubuntu, builded the project, and then mounted my windows drive to /mnt/k and since then everything works.
So bro, I think most of request of "compiling on Windows" means they wanna a win32 version of this program to plot their disk on Windows straightforwardly, but by this way can only produce a Linux bin file, though it does to be compiled "on Windows".

**Comment by ArtrixTech** [comment]
> So i resolved the issue by installing WSL 2 for windows.
> Basically i installed Ubuntu on my K:\ drive, then i launched ubuntu, builded the project, and then mounted my windows drive to /mnt/k and since then everything works.

So bro, I think most of request of "compiling on Windows" means they wanna a win32 version of this program to plot their disk on Windows straightforwardly, but by this way can only produce a Linux bin file, though it does to be compiled "on Windows".

**Comment by Sonit90** [comment]
You can use this release : https://github.com/stotiks/chia-plotter/releases/tag/v0.0.3-alpha

**Comment by ArtrixTech** [comment]
> You can use this release : https://github.com/stotiks/chia-plotter/releases/tag/v0.0.3-alpha

Thanks a lot!
