### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by Krokodealer** [madMAx43v3r/chia-plotter#24]
Hi! Got this problem:
![Screenshot_3](https://user-images.githubusercontent.com/29544432/121070873-e7748000-c7d7-11eb-9bb7-90bc0777647f.jpg)

**Comment by MarcusArthur** [comment]
I had the same problem when I put the log num buckets at 128 - just leave it blank and it should run fine!

**Comment by Krokodealer** [comment]
> I had the same problem when I put the log num buckets at 128 - just leave it blank and it should run fine!

lol really works, thanks.

**Comment by Damme** [comment]
for 128 buckets specify 7

**Comment by Krokodealer** [comment]
> for 128 buckets specify 7
> 2^128 = 3.40282366921e+38

Oh, really, this was stupid failure XD
