### ISSUE TITLE
How to increase RAM in command . Is there is any variable 

### ISSUE THREAD

**Issue by obulisaravanan** [madMAx43v3r/chia-plotter#248]

**Comment by madMAx43v3r** [comment]
RAM usage depends on number of threads and buckets, there is no manual RAM setting like in official plotter

**Comment by obulisaravanan** [comment]
Chia official plotter we can specif RAM.

**Comment by madMAx43v3r** [comment]
yes but with this plotter it doesn't make sense, I use a different way of sorting
