### ISSUE TITLE
Are Madmax plots working on Hpool?

### ISSUE THREAD

**Issue by vvavepacket** [madMAx43v3r/chia-plotter#252]
I see reports of madmax plots not working in Hpool such as this..

https://twitter.com/sourabhs701/status/1403210660448641026?s=20

Does anyone here have success in making these madmax plots work in Hpool?

**Comment by qwazzzzzz** [comment]
work

**Comment by madMAx43v3r** [comment]
maybe he set the wrong keys, he should double check if the plots are accepted by official client

**Comment by vvavepacket** [comment]
Thanks.. ticket closed.
