### ISSUE TITLE
Invalid <tmpdir>: /selim/ffmpeg/chia-plotter/temp (needs trailing '/' or '\') error in ubuntu

### ISSUE THREAD

**Issue by karads** [madMAx43v3r/chia-plotter#255]
Hello guys , I tried too many variations but I couldn't fix this .. anyone who faced this and fixed it ?

**Comment by VertiHydro** [comment]
Try /selim/ffmpeg/chia-plotter/temp/ (note the extra slash at the end)

**Comment by Dartellum** [comment]
/selim/ffmpeg/chia-plotter/temp/

**Comment by karads** [comment]
Thank you , it is working , I just didn't try that one :)
