### ISSUE TITLE
can't build?

### ISSUE THREAD

**Issue by krowve** [madMAx43v3r/chia-plotter#258]
fresh git clone
cd chia-plotter
./make_release.sh
-- Found Git: /usr/bin/git (found version "2.30.2") 
-- The C compiler identification is GNU 10.3.0
-- The CXX compiler identification is GNU 10.3.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Architecture: x86_64
CMake Error at CMakeLists.txt:17 (add_subdirectory):
  The source directory

    /home/kro/chia-plotter/lib/bls-signatures

  does not contain a CMakeLists.txt file.

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring incomplete, errors occurred!
See also "/home/kro/chia-plotter/build/CMakeFiles/CMakeOutput.log".
See also "/home/kro/chia-plotter/build/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.

**Comment by rhernaus** [comment]
The README contains the answer to your question.
`git submodule update --init`

**Comment by krowve** [comment]
my bad.  thanks.
