### ISSUE TITLE
Incompleted copy to destination drive

### ISSUE THREAD

**Issue by diegotanel** [madMAx43v3r/chia-plotter#267]
Hello everybody.

I have this problem, I have tested the mad max plotter. I plotted all the phases without problems, but the copy to the destination drive did not complete.
I have a SO Ubuntu 20.04
32 Gb mem
Intel I5 10400 (6c/12Th)
Tmp drive: 2x1 TB NVMe WD 750 black (RAID 0)
Dst drive: HDD 10 TB Seagate

TMP Drive
ls -lh /mnt/ssdtemp/
total 102G 
-rw-rw-r-- 1 dtanel dtanel **102G** Jun 11 12:41 plot-k32-2021-06-11-11-54-09f2ddb22a5afb2297a202c8d6761e27ff280ab88f7b7cec22efc6a5428574c9.plot

DST Drive
ls -lh /media/dtanel/hdd1plot/
total 90G
-rw-rw-r-- 1 dtanel dtanel **90G** Jun 11 12:47 plot-k32-2021-06-11-11-54-09f2ddb22a5afb2297a202c8d6761e27ff280ab88f7b7cec22efc6a5428574c9.plot.tmp

Log plot
Multi-threaded pipelined Chia k32 plotter - a75f2b3
Final Directory: /media/dtanel/hdd1plot/
Number of Plots: 1
Process ID: 23210
Number of Threads: 12
Number of Buckets: 2^7 (128)
Pool Public Key:   928a308d319b9144c66258e504afc5513e0af5da995b4a805fe1a2dca092e37d162d4402e95ac9cf06701d1dfc2654a6
Farmer Public Key: 8f81d7a136514c4e2445573387623c3bf13c7610d963e39815ecb0bda98c5ffc95e627ab3e642f155d0f85c4ca12e1f8
Working Directory:   /mnt/ssdtemp/
Working Directory 2: /mnt/ssdtemp/
Plot Name: plot-k32-2021-06-11-11-54-09f2ddb22a5afb2297a202c8d6761e27ff280ab88f7b7cec22efc6a5428574c9
[P1] Table 1 took 22.6755 sec
[P1] Table 2 took 194.611 sec, found 4294939878 matches
[P1] Table 3 took 226.645 sec, found 4294910826 matches
[P1] Table 4 took 277.144 sec, found 4294843957 matches
[P1] Table 5 took 272.3 sec, found 4294659242 matches
[P1] Table 6 took 261.374 sec, found 4294407416 matches
[P1] Table 7 took 200.384 sec, found 4293885023 matches
Phase 1 took 1455.15 sec
[P2] max_table_size = 4294967296
[P2] Table 7 scan took 15.8862 sec
[P2] Table 7 rewrite took 31.5876 sec, dropped 0 entries (0 %)
[P2] Table 6 scan took 46.9775 sec
[P2] Table 6 rewrite took 72.0085 sec, dropped 581323951 entries (13.5368 %)
[P2] Table 5 scan took 45.2337 sec
[P2] Table 5 rewrite took 69.105 sec, dropped 762055776 entries (17.7443 %)
[P2] Table 4 scan took 44.564 sec
[P2] Table 4 rewrite took 68.0175 sec, dropped 828874387 entries (19.2993 %)
[P2] Table 3 scan took 44.2719 sec
[P2] Table 3 rewrite took 67.5064 sec, dropped 855043784 entries (19.9083 %)
[P2] Table 2 scan took 44.1058 sec
[P2] Table 2 rewrite took 67.3264 sec, dropped 865567187 entries (20.1532 %)
Phase 2 took 623.373 sec
Wrote plot header with 268 bytes
[P3-1] Table 2 took 53.0664 sec, wrote 3429372691 right entries
[P3-2] Table 2 took 47.4078 sec, wrote 3429372691 left entries, 3429372691 final
[P3-1] Table 3 took 67.2131 sec, wrote 3439867042 right entries
[P3-2] Table 3 took 49.8141 sec, wrote 3439867042 left entries, 3439867042 final
[P3-1] Table 4 took 67.579 sec, wrote 3465969570 right entries
[P3-2] Table 4 took 50.1526 sec, wrote 3465969570 left entries, 3465969570 final
[P3-1] Table 5 took 68.728 sec, wrote 3532603466 right entries
[P3-2] Table 5 took 51.1536 sec, wrote 3532603466 left entries, 3532603466 final
[P3-1] Table 6 took 71.8238 sec, wrote 3713083465 right entries
[P3-2] Table 6 took 53.9046 sec, wrote 3713083465 left entries, 3713083465 final
[P3-1] Table 7 took 59.4985 sec, wrote 4293885023 right entries
[P3-2] Table 7 took 62.4516 sec, wrote 4293885023 left entries, 4293885023 final
Phase 3 took 704.305 sec, wrote 21874781257 entries to final plot
[P4] Starting to write C1 and C3 tables
[P4] Finished writing C1 and C3 tables
[P4] Writing C2 table
[P4] Finished writing C2 table
Phase 4 took 63.9863 sec, final plot size is 108821103444 bytes
Total plot creation time was 2846.85 sec
Started copy to /media/dtanel/hdd1plot/plot-k32-2021-06-11-11-54-09f2ddb22a5afb2297a202c8d6761e27ff280ab88f7b7cec22efc6a5428574c9.plot

The copy to the destination drive was never completed.
Can you help me?
Thank you.

**Comment by madMAx43v3r** [comment]
slow drive?

**Comment by madMAx43v3r** [comment]
did you wait for process to finish?

**Comment by diegotanel** [comment]
In the initial test use this command and the copy failed:
./build/chia_plot -p $$$ -f $$$ -n 1 -r 12 -t /mnt/ssdtemp/ -d /media/dtanel/hdd1plot/ >> $(date '+%Y-%m-%d_%H_%M_%S').log &

Now, I tested with 3 plots and it works fine. Complete copy finished.
./build/chia_plot -p $$$ -f $$$ -n 3 -r 12 -t /mnt/ssdtemp/ -d /media/dtanel/hdd1plot/ >> $(date '+%Y-%m-%d_%H_%M_%S').log &

I don't know why it failed with 1 plot.
Thank you.

**Comment by madMAx43v3r** [comment]
hard to say what caused it now..

**Comment by diegotanel** [comment]
Hello everybody.

Yesterday I have a new problem in my 3 plotting PCs.

I execute chia-plotter with this parameters:
./build/chia_plot -p  $$$ -f $$$ -n -1 -r 12 -t /mnt/ssdtemp/ -d /media/dtanel/hdd1plot/ >> $(date '+%Y-%m-%d_%H_%M_%S').log &


PC1 Chia-rig1
In my tmp drive I have two completed plots:
plot-k32-2021-06-13-03-45-0bbb733e706a27dd4341630c869cfa5950498e69e8fb824d72251fdc09df142a.plot
plot-k32-2021-06-13-04-29-00196bd4c2087ec5ec2743a425666e44e1b158668dc7ed49b00229843be2cd82.plot

In my dst drive I have 1 tmp copy plot:
plot-k32-2021-06-13-03-45-0bbb733e706a27dd4341630c869cfa5950498e69e8fb824d72251fdc09df142a.plot.tmp

Log
Copy to /media/dtanel/hdd1plot/plot-k32-2021-06-13-03-45-0bbb733e706a27dd4341630c869cfa5950498e69e8fb824d72251fdc09df142a.plot failed with: fwrite() failed

PC2 Chia-rig2
In my tmp drive I have a lot of tmp plot.

In my destination I have five finished plot.

Log:
[P4] Starting to write C1 and C3 tables
[P4] Finished writing C1 and C3 tables
[P4] Writing C2 table
[P4] Finished writing C2 table
Phase 4 took 67.5566 sec, final plot size is 108814253851 bytes
Total plot creation time was 2665.42 sec
Started copy to /media/dtanel/hdd1plot/plot-k32-2021-06-13-06-36-45a69c082a1d81d574367272839e9958dc93903e5a577dc5f82083f03d3bb89c.plot
Crafting plot 6 out of -1
Process ID: 2505393
Number of Threads: 12
Number of Buckets: 2^8 (256)
Pool Public Key:   928a308d319b9144c66258e504afc5513e0af5da995b4a805fe1a2dca092e37d162d4402e95ac9cf06701d1dfc2654a6
Farmer Public Key: 8f81d7a136514c4e2445573387623c3bf13c7610d963e39815ecb0bda98c5ffc95e627ab3e642f155d0f85c4ca12e1f8
Working Directory:   /mnt/ssdtemp/
Working Directory 2: /mnt/ssdtemp/
Plot Name: plot-k32-2021-06-13-07-20-31528aa4c28eec0399f0350c03859dee8bd7b2f452a0c2012da23ac5f1cf5b34
[P1] Table 1 took 23.0707 sec
[P1] Table 2 took 191.008 sec, found 4295066068 matches
[P1] Table 3 took 219.563 sec, found 4295045758 matches
Copy to /media/dtanel/hdd1plot/plot-k32-2021-06-13-06-36-45a69c082a1d81d574367272839e9958dc93903e5a577dc5f82083f03d3bb89c.plot finished, took 453.479 sec, 228.838 MB/s avg.
[P1] Table 4 took 252.086 sec, found 4294947566 matches
[P1] Table 5 took 245.407 sec, found 4294914087 matches
[P1] Table 6 took 239.395 sec, found 4294790770 matches
[P1] Table 7 took 187.277 sec, found 4294685729 matches
Phase 1 took 1357.84 sec
[P2] max_table_size = 4295066068
[P2] Table 7 scan took 16.5879 sec
[P2] Table 7 rewrite took 32.108 sec, dropped 0 entries (0 %)
[P2] Table 6 scan took 39.8226 sec
[P2] Table 6 rewrite took 67.3877 sec, dropped 581240858 entries (13.5336 %)
[P2] Table 5 scan took 38.521 sec
[P2] Table 5 rewrite took 65.1205 sec, dropped 762006260 entries (17.7421 %)
[P2] Table 4 scan took 38.0791 sec
[P2] Table 4 rewrite took 63.6104 sec, dropped 828860632 entries (19.2985 %)
[P2] Table 3 scan took 37.6976 sec
[P2] Table 3 rewrite took 63.0329 sec, dropped 855132754 entries (19.9097 %)

PC3 Chia-rig3
In my tmp drive I have a lot of tmp plot.

In my destination I have five finished plots.

Log:
Phase 3 took 709.825 sec, wrote 21876856365 entries to final plot
[P4] Starting to write C1 and C3 tables
[P4] Finished writing C1 and C3 tables
[P4] Writing C2 table
[P4] Finished writing C2 table
Phase 4 took 64.4214 sec, final plot size is 108833809336 bytes
Total plot creation time was 2887.24 sec
Started copy to /media/dtanel/hdd1plot/plot-k32-2021-06-13-06-29-6a7291d6bd5e1bc3c617ca2a0396f0fc5f884e5c8e460321963022dcc7625b0c.plot
Process ID: 33432
Number of Threads: 12
Number of Buckets: 2^7 (128)
Pool Public Key:   928a308d319b9144c66258e504afc5513e0af5da995b4a805fe1a2dca092e37d162d4402e95ac9cf06701d1dfc2654a6
Farmer Public Key: 8f81d7a136514c4e2445573387623c3bf13c7610d963e39815ecb0bda98c5ffc95e627ab3e642f155d0f85c4ca12e1f8
Working Directory:   /mnt/ssdtemp/
Working Directory 2: /mnt/ssdtemp/
Plot Name: plot-k32-2021-06-13-07-17-3c67c16e452d366d7ff8991b57ac5bdaf3dcd63b2029c4ae4fa5b191c47dbda6
[P1] Table 1 took 25.0174 sec
[P1] Table 2 took 203.805 sec, found 4294996333 matches
Copy to /media/dtanel/hdd1plot/plot-k32-2021-06-13-06-29-6a7291d6bd5e1bc3c617ca2a0396f0fc5f884e5c8e460321963022dcc7625b0c.plot finished, took 457.088 sec, 227.072 MB/s avg.
[P1] Table 3 took 239.325 sec, found 4295027437 matches
[P1] Table 4 took 278.849 sec, found 4295050274 matches
[P1] Table 5 took 274.319 sec, found 4295054038 matches
[P1] Table 6 took 262.886 sec, found 4295090802 matches
[P1] Table 7 took 201.373 sec, found 4295096699 matches
Phase 1 took 1485.61 sec
[P2] max_table_size = 4295096699
[P2] Table 7 scan took 16.317 sec
[P2] Table 7 rewrite took 33.8206 sec, dropped 0 entries (0 %)
[P2] Table 6 scan took 47.076 sec


Thank you
