### ISSUE TITLE
missing library

### ISSUE THREAD

**Issue by Hardcore-fs** [madMAx43v3r/chia-plotter#27]
`clang-12: warning: argument unused during compilation: '-L/usr/local/opt/llvm/lib' [-Wunused-command-line-argument]
In file included from /Volumes/empty9/chia-plotter/src/chia_plot.cpp:12:
/Volumes/empty9/chia-plotter/include/chia/chia_filesystem.hpp:20:10: fatal error: 'filesystem.hpp' file not found
#include "filesystem.hpp"
         ^~~~~~~~~~~~~~~~
1 error generated.`

**Comment by madMAx43v3r** [comment]
I was wondering how that worked...

**Comment by madMAx43v3r** [comment]
You can comment that out in `chia_plot.cpp` for the time being, it's just a sanity check if the tmp dirs exist.

**Comment by Hardcore-fs** [comment]
I think it picks up the "filesystem.hpp" from the compiler & llvm libraries

I hacked around it by making mods to the "make" files & CMakeLists.txt
plus I also got it running on osx 10.13.6

Yep.... it was the code in the temp dirs..., I think there are better methods of detection, without pulling all these additional libraries & binaries just to see if a directory exists.

Because I think there are a load of other library dependencies that are only satisfied becasue i built "chia" on the same machine, so the libraries are already in place..., but this  "FS" is a difficult one for osx apparently
