### ISSUE TITLE
Input not sorted

### ISSUE THREAD

**Issue by Amplificator** [madMAx43v3r/chia-plotter#273]
I just built a new version of the software and I'm getting "input not sorted" now. It was working fine before I updated.

What gives?

Output looks like this: http://paste.ubuntu.com/p/rtScd7zKG2/

**Comment by xhaizeiwang** [comment]
I have the same problem as you
I use the old version two days ago and everything is ok
For this I have to use the old version to continue working

**Comment by Dstack86** [comment]
im getting the same error

**Comment by madMAx43v3r** [comment]
which commit was working before?

**Comment by madMAx43v3r** [comment]
check with `git reflog`

**Comment by Dstack86** [comment]
This is the first and only version I've used so I'm not sure what commit was working. I noticed if I lower the core count it will work fine without error. I just can't use more than 20 of my 24 threads

**Comment by Amplificator** [comment]
3b553d3548f44708e4fa9ddd80b45bae2ba756e3 works for me but not the latest one.

**Comment by xhaizeiwang** [comment]
2712c1a is valid for me

**Comment by madMAx43v3r** [comment]
this is all on linux? I cannot see a code change which could cause this...

**Comment by Dstack86** [comment]
Yes I'm on Ubuntu server with the GUI installed on a Dell power edge server.

**Comment by Dstack86** [comment]
![image](https://user-images.githubusercontent.com/59490709/121759349-4812fe00-caf3-11eb-9589-97dd07b6cc88.jpeg)

**Comment by Amplificator** [comment]
I’m running latest Debian Buster with XanMod-Cacule kernel.

**Comment by madMAx43v3r** [comment]
well the difference is that P3-2 has been optimized, so it's hammering your hardware more than before, that could be it

**Comment by Amplificator** [comment]
Is P3-2 heavy on the RAM og CPU?

**Comment by xhaizeiwang** [comment]
> well the difference is that P3-2 has been optimized, so it's hammering your hardware more than before, that could be it

I use the latest version
It will stay at P3-2 and cannot continue
How can I check the problem?

**Comment by Amplificator** [comment]
I upped the voltage a bit on the memory and it's stable now.

Kinda weird, as I've been able to run stress tests with the previous settings but this plotter required more voltage for some reason.

Anyway, others can see if this is the same issue they were having.

**Comment by pangchia** [comment]
same issue ，still not fix
