### ISSUE TITLE
Is the way blake3 implemented here preventing using the arm optimized NEON version of it?

### ISSUE THREAD

**Issue by AndyRPH** [madMAx43v3r/chia-plotter#287]
Does this take into account the blake3 version that uses NEON for ARM cpus that support it like the apple M1?  I don't see it listed in the CMakeLists.txt .

_Originally posted by @AndyRPH in https://github.com/madMAx43v3r/chia-plotter/issues/59#issuecomment-859567749_

**Comment by madMAx43v3r** [comment]
no I guess not

**Comment by AndyRPH** [comment]
Will this help better ID M1 apple build env to properly setup the Cmake stuff?

https://discourse.cmake.org/t/how-to-determine-which-architectures-are-available-apple-m1/2401/12

**Comment by Hardcore-fs** [comment]
the place for this discussion is on the BLAKE3 site....
since this app pull directly from the BLAKE3 code.

The real BLAKE3 compile experts will be in that group.

**Comment by AndyRPH** [comment]
I don't think it's a Blake3 issue, it looks like the correct version can be pulled in via the right cmake setup, which is far more likely to happen quickly than the blake3 group making large changes to how they have their end setup...

**Comment by madMAx43v3r** [comment]
you can try to make it work, just edit your CMake file

**Comment by AndyRPH** [comment]
Will do!

**Comment by madMAx43v3r** [comment]
actually all the SIMD optimizations will never be used for chia, for that the input size would have to be more than 1 kB, but in chia the max is 64 bytes...

**Comment by AndyRPH** [comment]
Thanks for the follow up!
