### ISSUE TITLE
std:: runtime error (thread failed with: thread failed with: small_delta >= 256 (416640308))

### ISSUE THREAD

**Issue by farchord** [madMAx43v3r/chia-plotter#289]
OS: Ubuntu 20.04 (x64)
CPU: AMD Ryzen 7 3700x
RAM: 128gb DDR4 3600Mhz
Plotting on a PCIe 4 2tb nvme for tmp1, and a 110G ramdisk on tmp2

Output:

Working Directory:   /mnt/nvme0/
Working Directory 2: /mnt/ramdisk/
Plot Name: plot-k32-2021-06-11-14-22-(REMOVED)
[P1] Table 1 took 14.7672 sec
[P1] Table 2 took 143.04 sec, found 4294896520 matches
[P1] Table 3 took 172.892 sec, found 4294788212 matches
[P1] Table 4 took 204.995 sec, found 4294639151 matches
[P1] Table 5 took 200.858 sec, found 4294211356 matches
[P1] Table 6 took 200.256 sec, found 4293449901 matches
[P1] Table 7 took 156.345 sec, found 4291983736 matches
Phase 1 took 1093.16 sec
[P2] max_table_size = 4294967296
Copy to /media/cheekclapper/Elements2/plot-k32-2021-06-11-13-47-REMOVED.plot finished, took 1096.12 sec, 94.6653 MB/s avg.
[P2] Table 7 scan took 12.2029 sec
[P2] Table 7 rewrite took 27.324 sec, dropped 0 entries (0 %)
[P2] Table 6 scan took 31.6388 sec
[P2] Table 6 rewrite took 66.2166 sec, dropped 581461043 entries (13.543 %)
[P2] Table 5 scan took 34.5038 sec
[P2] Table 5 rewrite took 63.5751 sec, dropped 762170568 entries (17.7488 %)
[P2] Table 4 scan took 33.3859 sec
[P2] Table 4 rewrite took 62.842 sec, dropped 829061630 entries (19.3046 %)
[P2] Table 3 scan took 34.9586 sec
[P2] Table 3 rewrite took 62.5067 sec, dropped 855146106 entries (19.9113 %)
[P2] Table 2 scan took 33.8477 sec
[P2] Table 2 rewrite took 62.2351 sec, dropped 865668903 entries (20.1558 %)
Phase 2 took 537.984 sec
Wrote plot header with 268 bytes
[P3-1] Table 2 took 40.9796 sec, wrote 3429227617 right entries
[P3-2] Table 2 took 30.6327 sec, wrote 3429227617 left entries, 3429227617 final
[P3-1] Table 3 took 44.498 sec, wrote 3439642106 right entries
terminate called after throwing an instance of 'std::runtime_error'
  what():  thread failed with: thread failed with: small_delta >= 256 (416640308)
Aborted
cheekclapper@plotter1:~/

**Comment by madMAx43v3r** [comment]
could be unstable RAM

**Comment by farchord** [comment]
Strange, ran fine for most of the night last night and now it's crashing every couple hours. I'll run the official plotter this weekend so I don't have to keep restarting it.

**Comment by farchord** [comment]
Just an update, it is indeed a (or more) bad stick(s) of ram. Thank you.
