### ISSUE TITLE
Ran 27ebfcb and it finnished in 5289s

### ISSUE THREAD

**Issue by Damme** [madMAx43v3r/chia-plotter#3]
Just wanted let you know! Nice work! 
The server was rather busy at the time too so I guess I can get around 10% better time. Plotted on raid5 with 6 x 800gb enterprise sas ssd's. got nvme too but didn't run on them now.

I'm not sure how to put in the pool key etc yet but I suppose that's coming :) 
In testnet its apparently possible to plot for pools now, I'm going to replot at soon as it get released and hopefully with your code instead.

I was able to stack the original plotter and get one every 1h, I think I should be able to stack this 2 maybe 3 times :)

(27ebfcbf0a47ee3f57ad48811e50d64db72676db)

```
Phase 1 took 2176.96 sec
real    36m17.068s
user    344m11.493s
sys     27m20.482s

Phase 2 took 1610.95 sec
real    26m51.067s
user    105m8.773s
sys     8m52.344s

Phase 3 took 1371.42 sec, wrote 21877156374 entries to final plot
real    22m51.629s
user    137m53.501s
sys     20m29.217s

Phase 4 took 129.688 sec, final plot size is 108835549588 bytes
real    2m9.796s
user    9m27.843s
sys     0m37.823s
```

**Comment by RamonRobben** [comment]
Hey how are you able to run all 4 phases when Phase 3 and 4 are still in development? I'm just curious as I am eagerly waiting to try this chia plotter.

**Comment by madMAx43v3r** [comment]
The readme is not up to date, been too busy coding... There is a new binary `chia_plot` which does all phases in one. I'm still working on being able to set the public keys, so no usable plots yet.

**Comment by RamonRobben** [comment]
> The readme is not up to date, been too busy coding... There is a new binary `chia_plot` which does all phases in one. I'm still working on being able to set the public keys, so no usable plots yet.

Oh well no worries I'm subscribed to the repo so once its ready I'll probably receive a notification :) Can't wait for this looks so cool and promising.

**Comment by Damme** [comment]
I was just about to test the latest commits but I ran into some trouble:
```
[ 14%] Building C object _deps/relic-build/src/CMakeFiles/relic_s.dir/md/relic_md_sha256.c.o
In file included from /opt/chia-plotter/build/_deps/relic-src/src/md/blake2s-ref.c:18:
/opt/chia-plotter/build/_deps/relic-src/src/md/blake2.h:101:5: error: size of array element is not a multiple of its alignment
  101 |     blake2s_state S[8][1];
      |     ^~~~~~~~~~~~~
/opt/chia-plotter/build/_deps/relic-src/src/md/blake2.h:102:5: error: size of array element is not a multiple of its alignment
  102 |     blake2s_state R[1];
      |     ^~~~~~~~~~~~~
/opt/chia-plotter/build/_deps/relic-src/src/md/blake2.h:109:5: error: size of array element is not a multiple of its alignment
  109 |     blake2b_state S[4][1];
      |     ^~~~~~~~~~~~~
/opt/chia-plotter/build/_deps/relic-src/src/md/blake2.h:110:5: error: size of array element is not a multiple of its alignment
  110 |     blake2b_state R[1];
      |     ^~~~~~~~~~~~~
/opt/chia-plotter/build/_deps/relic-src/src/md/blake2s-ref.c: In function ‘blake2s’:
/opt/chia-plotter/build/_deps/relic-src/src/md/blake2s-ref.c:329:3: error: size of array element is not a multiple of its alignment
  329 |   blake2s_state S[1];
      |   ^~~~~~~~~~~~~
make[2]: *** [_deps/relic-build/src/CMakeFiles/relic_s.dir/build.make:2834: _deps/relic-build/src/CMakeFiles/relic_s.dir/md/blake2s-ref.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /opt/chia-plotter/build/_deps/relic-src/src/md/relic_md_blake2s.c:38:
/opt/chia-plotter/build/_deps/relic-src/src/md/blake2.h:101:5: error: size of array element is not a multiple of its alignment
  101 |     blake2s_state S[8][1];
      |     ^~~~~~~~~~~~~
/opt/chia-plotter/build/_deps/relic-src/src/md/blake2.h:102:5: error: size of array element is not a multiple of its alignment
  102 |     blake2s_state R[1];
      |     ^~~~~~~~~~~~~
/opt/chia-plotter/build/_deps/relic-src/src/md/blake2.h:109:5: error: size of array element is not a multiple of its alignment
  109 |     blake2b_state S[4][1];
      |     ^~~~~~~~~~~~~
/opt/chia-plotter/build/_deps/relic-src/src/md/blake2.h:110:5: error: size of array element is not a multiple of its alignment
  110 |     blake2b_state R[1];
      |     ^~~~~~~~~~~~~
make[2]: *** [_deps/relic-build/src/CMakeFiles/relic_s.dir/build.make:2848: _deps/relic-build/src/CMakeFiles/relic_s.dir/md/relic_md_blake2s.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:581: _deps/relic-build/src/CMakeFiles/relic_s.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by madMAx43v3r** [comment]
Ah dang it, that's from `bls-signatures` submodule from chia, I need that for the keys...
What kind of machine are you compiling on? Also try `clean_all.sh`.

**Comment by Damme** [comment]
Its a linux container in linux, I don't think I am missing any packages but its certainly a possibility I am missing some lib.
I ran `git clone --recurse-submodules https://github.com/madMAx43v3r/chia-plotter.git` and I tried a fresh pull and tried make debug, devel and release. Same on all.

**Comment by madMAx43v3r** [comment]
It's a know issue:
https://www.bountysource.com/issues/97976746-build-fails-on-fedora-34
https://www.bountysource.com/issues/97624932-bug-build-fails-on-fedora-based-system-blake2-h-error-size-of-array-element-is-not-a-multiple-of-its-alignment

**Comment by madMAx43v3r** [comment]
It's caused by gcc-11 being more strict than before.

**Comment by Damme** [comment]
I do run GCC 11 in this container, easily changed though. Thanks for looking it up!

**Comment by Hardcore-fs** [comment]
Just be careful... chia have already said if people  defeat the plot speed they will go to  k=33

**Comment by madMAx43v3r** [comment]
Even if, it wouldn't be economical, by far not.

**Comment by Hardcore-fs** [comment]
I think  their "leader" has some sort of master plan......
Besides.. China will dominate again.... i've already seen  "staff" who work in massive .. massive data centers
using "work" resources....

**Comment by fermosan** [comment]
Regarding the K32 plot size Chia claims that now the only reason to plot K33 is to optimize space. They consider "safe" for K32 a total plot time of at least 1 hour and a Phase 1 plot of at least 10 mins. Now it seems we are at 20mins but this will be of course lower with cutting edge hardware and overclocked cpus/memories.  If GPU cores are utilized for the task it's another story :). Anyway, this work is amazing. Well done one more time madMAx43v3r.

**Comment by madMAx43v3r** [comment]
`Phase 1 took 1127.25 sec`
That's on a ~8 year old server with just 16 cores.

**Comment by Hardcore-fs** [comment]
there is a "myth" that newer kit is always better.
but when you look into the actual specs of modern cpu, you find that it is all bullshit.
many new intel cpu CANNOT span the full processing & freq across all the cores.
they clearly state that it is ONLY across 1-2 cores & the rest get throttled

the real advantage is in the AVX  stuff.
you *might* want to have a look at the actual "blake" code, not the nobbled shit on chia.....

**Comment by fermosan** [comment]
Check this out: [https://www.youtube.com/watch?v=cXVrW_b_iEE&t=308s](url)
"Total time = 9472.122 seconds. CPU (201.330%) Sat May 15 06:02:19 2021" 
This is supposed to be the current 🌐  record. He is not using the optimized chia-pos from [https://github.com/pechy/chiapos/tree/combined](url) 🎉

**Comment by Damme** [comment]
Closed to remove clutter :) Thanks!
