### ISSUE TITLE
Runtime error on windows 10, compiled by Cygwin

### ISSUE THREAD

**Issue by niconiconi** [madMAx43v3r/chia-plotter#305]
My setting is the following:

Cygwin 2.908 (64bit)

libgmp (libgmp-devel 6.2.1-1), libsodium (libsodium-devel 1.0.18-1), and compiler toolchain are provided by Cygwin package manager

build command:

`mkdir -p build`

`cd build`

`cmake -D CMAKE_CXX_FLAGS="-O3 -fmax-errors=1" -DBUILD_BLS_PYTHON_BINDINGS=fals`

`make -j10 $@`

running command:

`./chia_plot.exe -t E:\plotting\ -d J:\plots\ -p my_pool_public_key -f my_farm_public_key -r 12  -n 5`

PC configuration:
`Ryzen 3800x, 64GB RAM, Disk E has 2TB free space, Disk J has 10 TB free space`

**Comment by niconiconi** [comment]
Error message:

Number of Plots: 5
Process ID: -1
Number of Threads: 12
Number of Buckets: 2^7 (128)
Pool Public Key:   xxxxxxx
Farmer Public Key: xxxxxxx
Working Directory:   E:\plotting\
Working Directory 2: E:\plotting\
Plot Name: plot-k32-2021-06-11-05-10-xxxxxxx
[P1] Table 1 took 34.7818 sec
      0 [chia_plot] chia_plot 1594 cygwin_exception::open_stackdumpfile: Dumping stack trace to chia_plot.exe.stackdump

**Comment by niconiconi** [comment]
Exception: STATUS_ACCESS_VIOLATION at rip=0010041F480
rax=00000000F91FBCD8 rbx=0000000000000000 rcx=00000000F91FBCB0

**Comment by never-afk** [comment]
me too
