### ISSUE TITLE
Public pool key error

### ISSUE THREAD

**Issue by MarcelodeFA** [madMAx43v3r/chia-plotter#311]
![Screenshot_1](https://user-images.githubusercontent.com/85201643/121762351-b6fc5100-cb0b-11eb-9f24-9d24042678d1.png)
Getting the same error, over and over again, that's the right public pool key....
Already looked for any spaces I could have added, but it's not there.

**Comment by whitetechnologies** [comment]
On windows need to update to 1.1.7 to generate a 48 byte key. For some reason earlier version does not generate correct key size

**Comment by MarcelodeFA** [comment]
> On windows need to update to 1.1.7 to generate a 48 byte key. For some reason earlier version does not generate correct key size

You are the best. Thank you very much!
