### ISSUE TITLE
Plots are unsigned in H Pool

### ISSUE THREAD

**Issue by karads** [madMAx43v3r/chia-plotter#324]
Plots are which I created with mad max looking unsigned in H Pool , how can I fix this ?

**Comment by kacperapi** [comment]
use hpool plotter

**Comment by karads** [comment]
with mad max ?

**Comment by draven-chen** [comment]
I having no problem using hpool

**Comment by kentgran** [comment]
It will sort itself out after a few hours. Unless you used the wrong keys when you created the plots.

**Comment by karads** [comment]
> It will sort itself out after a few hours. Unless you used the wrong keys when you created the plots.

actually when I was used hp plotter fpk was starting with :0xaf , and ppk : 0xb3 . But madmax didn't accept it . I took another numbers from chia keys show which start with : a7ebc , and af610 . Someone told me , this chia keys show is my real keys . It's same , it will accept both . Maybe this is the problem ?

**Comment by karads** [comment]
it's looking like this in H pool ;

0xb38a064f8c0d7b90***   668          66.15 TiB             Signed
0xa7ebc45c841ae482***    19               1.88 TiB           Unsigned

**Comment by kentgran** [comment]
If you have generated new keys with Chia, you will probably have to bind the new keys with HPool.

It should be the ones that says "Pool public key" and "Farmer public key", not the "Master public key"

**Comment by karads** [comment]
but when I put my mnemonic  , Hpool plotter application gives me same signature as before.

**Comment by karads** [comment]
When I created the plots I used " Master public key (m) " and " Farmer public key (m/12381/8444/0/0)"  this one was the mistake ? 

I have to use  "Pool public key" and "Farmer public key" ?

So now I have to change it and run again ? and delete those plots ?

**Comment by stotiks** [comment]
Yes

**Comment by guilhermeg2020** [comment]
to get the keys, get the log files in the app da chia, in the first line of the log file has the keys, follow the directory below:
C:\Users\YOU_USER\.chia\mainnet\plotter

**Comment by guilhermeg2020** [comment]
use "Pool public key" and "Farmer public key"
