### ISSUE TITLE
make: *** No targets specified and no makefile found.  Stop.

### ISSUE THREAD

**Issue by haruhituki** [madMAx43v3r/chia-plotter#33]
I have an issue,it seens no makefile
OS:ubuntu18.04
cmake version:3.20.3
,this is CLI print:
-
- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:3 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "/chia-plotter/build/CMakeFiles/CMakeOutput.log".
See also "/chia-plotter/build/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.
root@yui-virtual-machine:/chia-plotter# 

cmake error log:

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: CMAKE_CXX_COMPILER-NOTFOUND 
Build flags: 
Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3 

The output was:
No such file or directory

Can anyone solved it?

regards!

**Comment by haruhituki** [comment]
> Do you have cmake installed?

no, which directory should I run cmake？

**Comment by VertiHydro** [comment]
Try installing build-essential if you haven't already.

**Comment by hdlxb** [comment]
The same problem, looking forward to solving

**Comment by grayfallstown** [comment]
Same problem here, earlier version compiled just fine

**Comment by haruhituki** [comment]
> Try installing build-essential if you haven't already.

Thx,but it still not work

**Comment by madMAx43v3r** [comment]
`Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3`
Are you compiling on a RPI?

**Comment by VertiHydro** [comment]
Try making sure g++ is installed: it should be included in build-essential, but just in case,
`apt-get install g++
`
Then do `gcc --version` and post its output here.

**Comment by haruhituki** [comment]
> `Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3`
> Are you compiling on a RPI?

No,compiling on X86 ubuntu 20.04,

Dependencies:
libsodium-dev/focal,now 1.0.18-1 amd64
libgmp3-dev/focal,now 2:6.2.0+dfsg-4 amd64
cmake version 3.16.3

**Comment by grayfallstown** [comment]
calling `make -j8 $@` manually seems to work.

**Comment by madMAx43v3r** [comment]
It seems that something with your cmake/gcc installation is messed up. Basically cmake cannot even compile a test program to figure out if your compiler works...

**Comment by VertiHydro** [comment]
Maybe reinstall cmake if it continues to not work? [This post](https://askubuntu.com/questions/1203635/installing-latest-cmake-on-ubuntu-18-04-3-lts-run-via-wsl-openssl-error) is linked in the readme if that helps at all. I had to make some tweaks to get my cmake to install on 20.04 - let me know if you need them.

**Comment by haruhituki** [comment]
> calling `make -j8 $@` manually seems to work.

make: *** No targets specified and no makefile found.  Stop.
the makefile doesn't found

**Comment by we-sell-bags** [comment]
you cross compiling?

because that's not intel:

Build flags:
Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3


run a ./clean_all.sh

**Comment by haruhituki** [comment]
> It seems that something with your cmake/gcc installation is messed up. Basically cmake cannot even compile a test program to figure out if your compiler works...

I run cmake it out out put :make: *** No targets specified and no makefile found. Stop.maybe is not cmake/gcc problem

**Comment by haruhituki** [comment]
> you cross compiling?
> 
> because that's not intel:
> 
> Build flags:
> Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3
> 
> run a ./clean_all.sh

**Comment by haruhituki** [comment]
> you cross compiling?
> 
> because that's not intel:
> 
> Build flags:
> Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3
> 
> run a ./clean_all.sh

My CPU is I5 7400 running ubuntu in VMware workstation 14, and how do I  build this flag?

**Comment by Dartellum** [comment]
This: `sudo apt-get install libssl-dev `and `sudo apt-get install build-essentials` fixed it for me. Fresh Ubuntu 20.04 server install in VirtualBox.

**Comment by haruhituki** [comment]
> This: `sudo apt-get install libssl-dev `and `sudo apt-get install build-essentials` fixed it for me. Fresh Ubuntu 20.04 server install in VirtualBox.

Thx a lot I gonna try it later~

**Comment by haruhituki** [comment]
Hi all! I solve the issue, is the command"git submodule update --init" doesn't get makefile into my directory /chia-plotter/lib/bls-signatures, I have this command "rerun git submodule update --init" redownload the make files,  The compiling working~
Maybe this information can help someone else! By the way, thx guys all!
