### ISSUE TITLE
32-bit overflow

### ISSUE THREAD

**Issue by MarcusArthur** [madMAx43v3r/chia-plotter#34]
Currently running 4x instances at 4T each and started noticing the below, not sure if it is an issue or not though!

[P1] Table 2 took 523.978 sec, found 4294969812 matches
[P1] Lost 2299 matches due to 32-bit overflow.

**Comment by VertiHydro** [comment]
@MarcusArthur feel free to close this issue whenever you get a chance - provided this answers your question.

**Comment by MarcusArthur** [comment]
Thanks!

**Comment by VertiHydro** [comment]
No worries!
