### ISSUE TITLE
how to make madmax, to start a new plot before copying to last dir

### ISSUE THREAD

**Issue by dmontes46** [madMAx43v3r/chia-plotter#359]
Hi, 
thanks for this app, i have done some test and managed to reduce time by 7h.
How can i get the chia-plotter to start a new plot before the copy to the last dir, can anyone help?
I have this on  linux, and i am not a expert in bash scripting.
thanks

**Comment by fabitom** [comment]
when you will set final dir the same as tmp dir then plotter will skip moving to final dir, you will have your plots in tmp dir. You can move them by own script.

**Comment by konkersgg** [comment]
> Hi,
> thanks for this app, i have done some test and managed to reduce time by 7h.
> How can i get the chia-plotter to start a new plot before the copy to the last dir, can anyone help?
> I have this on linux, and i am not a expert in bash scripting.
> thanks

if you set to run multiple plots, it should do that automatically.

![image](https://user-images.githubusercontent.com/4704759/121789069-283e1180-cba9-11eb-9d3f-52537651bb80.png)

this is my command line (for windows):
```
@ECHO OFF
SET maxDATE=%DATE:/=-%
SET maxTIME=%TIME:~0,2%-%TIME:~3,2%-%TIME:~6,2%
IF NOT EXIST logs MKDIR logs
powershell ".\chia_plot.exe -n -1 -t X:\ -2 Y:\ -d K:\ -r 6 -u 256 -p POOL_PKEY -f FARMER_PKEY | tee 'logs/%maxDATE%%maxTIME%.log'"
pause
```

**Comment by VertiHydro** [comment]
The final copy functionality runs in the background, so a new plot will start as soon as the old one finishes - it does not wait for the copy to complete.

**Comment by dmontes46** [comment]
thanks all
