### ISSUE TITLE
Feature Request: Plot #X of #N

### ISSUE THREAD

**Issue by whitetechnologies** [madMAx43v3r/chia-plotter#375]
When specifying n plots. It would be helpful if each new plot would show that it is plot X of N. This way we know when the current plot series initiated. This would also help bring this more in line with official chia plotter. Should be a simple commit to display that output at each plot in the series

**Comment by thecybo** [comment]
[This commit](https://github.com/madMAx43v3r/chia-plotter/commit/8112e5dfd9f1eb45427ea5476acafa2a6247f9bb) that was merged earlier does just that

**Comment by whitetechnologies** [comment]
Thank you! Sorry did not have latest version installed
