### ISSUE TITLE
@stotiks Chia-plotter is slow on windows server

### ISSUE THREAD

**Issue by feder-cr** [madMAx43v3r/chia-plotter#378]
i tried the @stotiks  version on different swevers with windows server installed, but the plotting process is extremely slow, i think it is an incompatibility problem with windows server!

**Comment by Hardcore-fs** [comment]
it will be......
bet ur running your "windows server with a gui"?

**Comment by feder-cr** [comment]
Yes

**Comment by dmontes46** [comment]
seeing the same thing, did you try in docker?
