### ISSUE TITLE
Different bucket counts per phase

### ISSUE THREAD

**Issue by madMAx43v3r** [madMAx43v3r/chia-plotter#391]
From user TER on discord:

Spec = AMD 5950x, 64GB RAM 3200mhz, 2TB Nvme SSD

Setting 1: -r 16, 128 buckets 
Finish in 2116 seconds

Setting 2: -r 32, 128 buckets
Finish in 2162 seconds

Setting 3: -r 20, 512 buckets
Finish in 2462 seconds
But interestingly, Phase 1 down from 1000~ seconds to 654 seconds.
Phase 3 went from 650 seconds to 1576 seconds. 
So total time still the same.

Setting 4 : -r 20, 128 buckets
Finish in 2113 seconds

I was wondering, what I did wrong in my Setting 3, as the Phase 1 improved by 40%, but Phase 3 dropped by 60%, which end up with the same total time.

**Comment by therealflinchy** [comment]
My personal experience is that 128 vs 256 buckets my phase 3 stays the same

256 vs 512 it goes up a little bit but it's still faster overall, though I've left it going overnight and haven't reviewed today's logs so maybe that has changed at some point. Will report back if there's any inconsistency

**Comment by malventano** [comment]
Can confirm phase 1 scaling with bucket count even to 512, but no impact on other phases here.

@madMAx43v3r it might also be worth considering adjustable thread counts per phase as well. I'm still collecting data, but on systems that scale using all threads (HT) instead of just cores, the last few thread doublings in phase 2 has resulted in perf regressions. https://github.com/madMAx43v3r/chia-plotter/commit/22073c9db1c03719c3b84531ae8639c5798d46d1 slowed it by a little, but https://github.com/madMAx43v3r/chia-plotter/commit/13674fa7e7830b4d9de91df05cc90d1c50c34673 slowed it more noticeably. For those systems with -r set to all threads (HT), phase 2 was previously already using all resources, so those last two changes push into context switch madness.

On that same config, phase 1 and 3 still don't fully utilize all threads, so I'll need to experiment further there as well.

**Comment by therealflinchy** [comment]
> Can confirm phase 1 scaling with bucket count even to 512, but no impact on other phases here.
> 
> @madMAx43v3r it might also be worth considering adjustable thread counts per phase as well. I'm still collecting data, but on systems that scale using all threads (HT) instead of just cores, the last few thread doublings in phase 2 has resulted in perf regressions. [22073c9](https://github.com/madMAx43v3r/chia-plotter/commit/22073c9db1c03719c3b84531ae8639c5798d46d1) slowed it by a little, but [13674fa](https://github.com/madMAx43v3r/chia-plotter/commit/13674fa7e7830b4d9de91df05cc90d1c50c34673) slowed it more noticeably. For those systems with -r set to all threads (HT), phase 2 was previously already using all resources, so those last two changes push into context switch madness.
> 
> On that same config, phase 1 and 3 still don't fully utilize all threads, so I'll need to experiment further there as well.

It would be good to have more info on how -r is actually handled, how they're multiplied and when, to know what we should set -r to

I've had to tell so many people not to set -r to their max thread count and that it's probably one of the reasons it's slow for them

I'm not even sure, at this point, if 32 is right for me, but it seems ok?

**Comment by malventano** [comment]
> It would be good to have more info on how -r is actually handled, how they're multiplied and when, to know what we should set -r to
> 
> I've had to tell so many people not to set -r to their max thread count and that it's probably one of the reasons it's slow for them

The (hardcoded) defaults are great for systems that would not otherwise scale well with HT, but for some servers, and especially the newer Xeons, going to max threads gives a large boost to speed (well, expect for stage 2 on the newest code). The most recent phase 2 change just applies an x2 multiplier to thread count for that stage.

**Comment by therealflinchy** [comment]
> > It would be good to have more info on how -r is actually handled, how they're multiplied and when, to know what we should set -r to
> > I've had to tell so many people not to set -r to their max thread count and that it's probably one of the reasons it's slow for them
> 
> The (hardcoded) defaults are great for systems that would not otherwise scale well with HT, but for some servers, and especially the newer Xeons, going to max threads gives a large boost to speed (well, expect for stage 2 on the newest code). The most recent phase 2 change just applies an x2 multiplier to thread count for that stage.

I've only seen it with up to v4 xeon, newer epyc, TR, trx40/80 and other normal consumer stuff and they all seem to be hurt in a big way by cranking thread count excessively. Or at best, not hurt just no gain. I'd assume leaving not enough for OS can't be helping

**Comment by malventano** [comment]
> I've only seen it with up to v4 xeon, newer epyc, TR, trx40/80 and other normal consumer stuff and they all seem to be hurt in a big way by cranking thread count excessively. Or at best, not hurt just no gain. I'd assume leaving not enough for OS can't be helping

This is a single socket Xeon in a workstation board. 38 cores. -r 38 gets less than half utilization across the board. -r 76 gets ~60% phase 1, ~90% phase 2, ~40% phase 3. Phase 2 pushes too hard on the newer build ( https://github.com/madMAx43v3r/chia-plotter/commit/13674fa7e7830b4d9de91df05cc90d1c50c34673 ).

**Comment by madMAx43v3r** [comment]
> > It would be good to have more info on how -r is actually handled, how they're multiplied and when, to know what we should set -r to
> > I've had to tell so many people not to set -r to their max thread count and that it's probably one of the reasons it's slow for them
> 
> The (hardcoded) defaults are great for systems that would not otherwise scale well with HT, but for some servers, and especially the newer Xeons, going to max threads gives a large boost to speed (well, expect for stage 2 on the newest code). The most recent phase 2 change just applies an x2 multiplier to thread count for that stage.

I've found that phase 2 wasn't using CPU fully, compared to the other phases, that's why I doubled it. You should now not need to use CPU thread count as -r, just the core count.

**Comment by madMAx43v3r** [comment]
> > I've only seen it with up to v4 xeon, newer epyc, TR, trx40/80 and other normal consumer stuff and they all seem to be hurt in a big way by cranking thread count excessively. Or at best, not hurt just no gain. I'd assume leaving not enough for OS can't be helping
> 
> This is a single socket Xeon in a workstation board. 38 cores. -r 38 gets less than half utilization across the board. -r 76 gets ~60% phase 1, ~90% phase 2, ~40% phase 3. Phase 2 pushes too hard on the newer build ( [13674fa](https://github.com/madMAx43v3r/chia-plotter/commit/13674fa7e7830b4d9de91df05cc90d1c50c34673) ).

That's strange, with -r 38 there should be 114 threads running in phase 1, but only 38 of them at 100%, the others at 50% load or less.

**Comment by madMAx43v3r** [comment]
Ok I've reverted the 2x increase in phase 2. I had a feeling it would mess up peoples settings..

**Comment by malventano** [comment]
> I've found that phase 2 wasn't using CPU fully, compared to the other phases, that's why I doubled it. You should now not need to use CPU thread count as -r, just the core count.

It's possible that on some configurations phase 2 is underutilizing, but on others it is overutilizing. This is why it might be useful to have the various thread counts adjustable via the command line. -r 16 applies to all phases, but -r 16,32,16,16 could be an easy way to apply per-phase counts for those configs that underutilize on some phases.

**Comment by gairom** [comment]
Since people run so many different setups it's impossible to optimize for everyone...
So maybe it's best to allow custom params for each phase, combining this also with #337 so something like `-r -u -t` for each phase (threads, buckets, tmpdir), this way people can optimize for the specifics of their system.
Is that makes sense?

**Comment by malventano** [comment]
> Since people run so many different setups it's impossible to optimize for everyone...
> So maybe it's best to allow custom params for each phase, combining this also with #337 so something like `-r -u -t` for each phase (threads, buckets, tmpdir), this way people can optimize for the specifics of their system.
> Is that makes sense?

It does make sense. Perhaps -r -u set defaults for all phases, then override defaults for the desired phase with a format of -r2 xx -u1 xxx . I'm not sure phase-specific -t would work as expected (saving time) as it would have to copy to the other temp, etc.

Whatcha think @madMAx43v3r ? This would save folks from editing source to optimize for various configs.

**Comment by madMAx43v3r** [comment]
There's so many more parameters to tune... we would need a config file for that, no point adding more params to the command line..

**Comment by malventano** [comment]
> There's so many more parameters to tune... we would need a config file for that, no point adding more params to the command line..

Oddly enough, that same system that didn't see much delta with the phase 2 change, when flipped from Ubuntu 21.04 Desktop to 21.04 Server, now sees a ~20s delta in phase 2 (with your original doubling boosting speed). If not many other people reported slow downs, it might be worth re-reverting that change or just making a flag for it. No need for a config file for what could be covered by an extra flag or two.

**Comment by madMAx43v3r** [comment]
I'll add another option for different bucket count for phase 3+4

**Comment by madMAx43v3r** [comment]
done, check `-v`

**Comment by malventano** [comment]
> done, check `-v`

Any chance to get an additional toggle for your previous '[Phase 2 more threads](url=https://github.com/madMAx43v3r/chia-plotter/commit/13674fa7e7830b4d9de91df05cc90d1c50c34673)' patch that was later reverted? It does net another 10% in some cases (Xeon, possibly TR). Those configs that don't get much benefit just spin 2x CPU for <1% gain, and if running overlapping plots on servers it would be better to leave the toggle disabled anyway, hence the suggestion for a flag and not a hardcoded doubling.

This should wrap up the customizations, so should not need to go as far as a config file just for this.

**Comment by madMAx43v3r** [comment]
#611

**Comment by fiveangle** [comment]
> There's so many more parameters to tune... we would need a config file for that, no point adding more params to the command line..

please no.  why would you want to have yaycf (yet another yaml config file) ?  with it self-contained it is a drop-in replacement for all scripts we've been crafting since February by using a wrapper script.  if you move these parameters to a config, you force everyone to recreate whole new workflows.

**Comment by madMAx43v3r** [comment]
if we add a config file, any command line params will overwrite what's in the config file. but as of now, no such plans..

**Comment by fiveangle** [comment]
that sounds perfect !

btw- great job on adding the per-phase bucket switches... already realizing a 3.7% improvement in average plotting speed (!)
