### ISSUE TITLE
Unclear how to set the key

### ISSUE THREAD

**Issue by grayfallstown** [madMAx43v3r/chia-plotter#4]
I looked at chia_plot.cpp for the parameters as ./chia_plot -h or --help did not show any usage.

As far as I know each plot must be bound to a key and the contents of the plots are based on that key.

I don't see a way to set the farmer public key or the pool one tho.

**Comment by madMAx43v3r** [comment]
It's a work in progress...

**Comment by grayfallstown** [comment]
I know it is not ready for production use. The readme made it sound like phase 1 and 2 are done. I hoped I could use phase 1 and 2 from this plotter and modify chiapos to run phase 3 and 4 based on the tmp file generated by this. Would be fun to tinker around with a frankenstein plotter, maybe rebuild a plot with the same key and id and make a hash compare to see if the results make sense.

**Comment by madMAx43v3r** [comment]
The phases are all done, just need to figure out the key stuff.
