### ISSUE TITLE
Failed to write to tmpdir directory

### ISSUE THREAD

**Issue by number435398** [madMAx43v3r/chia-plotter#412]
When running this in Linux, or attempting to do so I keep getting the message
`Failed to write to tmpdir directory: '/dev/nvme0n1p2/'`
I presume this is saying it can't access this nvme drive for some reason, but that is how that drive is described in the File window.
What am I missing?

**Comment by ataa** [comment]
You should mount the nvme drive first.

**Comment by number435398** [comment]
I am able to access the drive in the files GUI.  and there is an eject image next to it that says I can unmount it. I think its already mounted but I've been wrong before.

**Comment by ataa** [comment]
If it's already mounted, use the mount point instead of /dev/nvme0n1p2/.
you can find the mount point using `lsblk` command.

**Comment by number435398** [comment]
Okay, tried that.  Problem is the mount point is "/media/a/Chia Coin 1" and apparently this program doesn't like the spaces in the last part of the mounting point.

**Comment by ataa** [comment]
Try:
`'/media/a/Chia Coin 1/'`
It may work, if not. change the mount point to something without spaces.

**Comment by number435398** [comment]
How do I do that?  I didn't mount it to begin with, it just mounted automatically.

**Comment by ataa** [comment]
I am not familiar with automount, but this is how I do it using terminal.
```
sudo umount /dev/nvme0n1p2
sudo mkdir /mnt/plottemp
sudo mount /dev/nvme0n1p2 /mnt/plottemp
```
To make it permanent, you should change the mount point in `/etc/fstab` as well or find a way to change it in automount.

**Comment by Dartellum** [comment]
Put quotes around the drive, like atta mentions: -t "/media/a/Chia Coin 1/" -2 /some/drive/ etc...

**Comment by number435398** [comment]
Thank you for your help guys, you nailed it.
