### ISSUE TITLE
Caught exception "G1 element is invalid"

### ISSUE THREAD

**Issue by gigantoq** [madMAx43v3r/chia-plotter#425]
cmd in ps1: 

for($i=1; $i -le 1; $i++)
{.\chia_plot.exe -t d:\ -2 f:\ -r 8 --buckets 7 -p "poolkey" -f "farmerkeyy"}

return in powershell:

PS C:\Users\gigan\Desktop\madmax> C:\Users\gigan\Desktop\madmax\chia_plotter.ps1
Final Directory: d:\
Number of Plots: 1
Process ID: 2444
Number of Threads: 8
Number of Buckets: 2^7 (128)
Caught exception "G1 element is invalid"

whenever i run the command i get this 9 logs in Event Viewer, logs are in time order.

Provider "Registry" is Started. 

Details: 
	ProviderName=Registry
	NewProviderState=Started

	SequenceNumber=1

	HostName=ConsoleHost
	HostVersion=5.1.19041.1023
	HostId=3f6b7ffb-965f-4501-88a1-1242aff92d76
	HostApplication=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command if((Get-ExecutionPolicy ) -ne 'AllSigned') { Set-ExecutionPolicy -Scope Process Bypass }; & 'C:\Users\gigan\Desktop\madmax\chia_plotter.ps1'
	EngineVersion=
	RunspaceId=
	PipelineId=
	CommandName=
	CommandType=
	ScriptName=
	CommandPath=
	CommandLine=

Provider "Alias" is Started. 

Details: 
	ProviderName=Alias
	NewProviderState=Started

	SequenceNumber=3

	HostName=ConsoleHost
	HostVersion=5.1.19041.1023
	HostId=3f6b7ffb-965f-4501-88a1-1242aff92d76
	HostApplication=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command if((Get-ExecutionPolicy ) -ne 'AllSigned') { Set-ExecutionPolicy -Scope Process Bypass }; & 'C:\Users\gigan\Desktop\madmax\chia_plotter.ps1'
	EngineVersion=
	RunspaceId=
	PipelineId=
	CommandName=
	CommandType=
	ScriptName=
	CommandPath=
	CommandLine=

Provider "Environment" is Started. 

Details: 
	ProviderName=Environment
	NewProviderState=Started

	SequenceNumber=5

	HostName=ConsoleHost
	HostVersion=5.1.19041.1023
	HostId=3f6b7ffb-965f-4501-88a1-1242aff92d76
	HostApplication=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command if((Get-ExecutionPolicy ) -ne 'AllSigned') { Set-ExecutionPolicy -Scope Process Bypass }; & 'C:\Users\gigan\Desktop\madmax\chia_plotter.ps1'
	EngineVersion=
	RunspaceId=
	PipelineId=
	CommandName=
	CommandType=
	ScriptName=
	CommandPath=
	CommandLine=

Provider "FileSystem" is Started. 

Details: 
	ProviderName=FileSystem
	NewProviderState=Started

	SequenceNumber=7

	HostName=ConsoleHost
	HostVersion=5.1.19041.1023
	HostId=3f6b7ffb-965f-4501-88a1-1242aff92d76
	HostApplication=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command if((Get-ExecutionPolicy ) -ne 'AllSigned') { Set-ExecutionPolicy -Scope Process Bypass }; & 'C:\Users\gigan\Desktop\madmax\chia_plotter.ps1'
	EngineVersion=
	RunspaceId=
	PipelineId=
	CommandName=
	CommandType=
	ScriptName=
	CommandPath=
	CommandLine=

Provider "Function" is Started. 

Details: 
	ProviderName=Function
	NewProviderState=Started

	SequenceNumber=9

	HostName=ConsoleHost
	HostVersion=5.1.19041.1023
	HostId=3f6b7ffb-965f-4501-88a1-1242aff92d76
	HostApplication=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command if((Get-ExecutionPolicy ) -ne 'AllSigned') { Set-ExecutionPolicy -Scope Process Bypass }; & 'C:\Users\gigan\Desktop\madmax\chia_plotter.ps1'
	EngineVersion=
	RunspaceId=
	PipelineId=
	CommandName=
	CommandType=
	ScriptName=
	CommandPath=
	CommandLine=

Provider "Variable" is Started. 

Details: 
	ProviderName=Variable
	NewProviderState=Started

	SequenceNumber=11

	HostName=ConsoleHost
	HostVersion=5.1.19041.1023
	HostId=3f6b7ffb-965f-4501-88a1-1242aff92d76
	HostApplication=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command if((Get-ExecutionPolicy ) -ne 'AllSigned') { Set-ExecutionPolicy -Scope Process Bypass }; & 'C:\Users\gigan\Desktop\madmax\chia_plotter.ps1'
	EngineVersion=
	RunspaceId=
	PipelineId=
	CommandName=
	CommandType=
	ScriptName=
	CommandPath=
	CommandLine=

Engine state is changed from None to Available. 

Details: 
	NewEngineState=Available
	PreviousEngineState=None

	SequenceNumber=13

	HostName=ConsoleHost
	HostVersion=5.1.19041.1023
	HostId=3f6b7ffb-965f-4501-88a1-1242aff92d76
	HostApplication=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command if((Get-ExecutionPolicy ) -ne 'AllSigned') { Set-ExecutionPolicy -Scope Process Bypass }; & 'C:\Users\gigan\Desktop\madmax\chia_plotter.ps1'
	EngineVersion=5.1.19041.1023
	RunspaceId=42218bcd-7adf-4396-94bf-94694682066b
	PipelineId=
	CommandName=
	CommandType=
	ScriptName=
	CommandPath=
	CommandLine=

Provider "Certificate" is Started. 

Details: 
	ProviderName=Certificate
	NewProviderState=Started

	SequenceNumber=15

	HostName=ConsoleHost
	HostVersion=5.1.19041.1023
	HostId=3f6b7ffb-965f-4501-88a1-1242aff92d76
	HostApplication=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command if((Get-ExecutionPolicy ) -ne 'AllSigned') { Set-ExecutionPolicy -Scope Process Bypass }; & 'C:\Users\gigan\Desktop\madmax\chia_plotter.ps1'
	EngineVersion=5.1.19041.1023
	RunspaceId=42218bcd-7adf-4396-94bf-94694682066b
	PipelineId=2
	CommandName=
	CommandType=
	ScriptName=
	CommandPath=
	CommandLine=

Engine state is changed from Available to Stopped. 

Details: 
	NewEngineState=Stopped
	PreviousEngineState=Available

	SequenceNumber=18

	HostName=ConsoleHost
	HostVersion=5.1.19041.1023
	HostId=3f6b7ffb-965f-4501-88a1-1242aff92d76
	HostApplication=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command if((Get-ExecutionPolicy ) -ne 'AllSigned') { Set-ExecutionPolicy -Scope Process Bypass }; & 'C:\Users\gigan\Desktop\madmax\chia_plotter.ps1'
	EngineVersion=5.1.19041.1023
	RunspaceId=42218bcd-7adf-4396-94bf-94694682066b
	PipelineId=
	CommandName=
	CommandType=
	ScriptName=
	CommandPath=
	CommandLine=

**Comment by madMAx43v3r** [comment]
one of your keys is wrong

**Comment by gigantoq** [comment]
Someone on reddit told me the same buy i checked many many times. Write It manual and Copy paste It. Same result. Tried all versions same result. I Will try create another address in Chia and see the results.

**Comment by gigantoq** [comment]
Tried with different fingerprint same error. Also tried on another computer with different fingerprint keys, same output...
 Then disabled Windows Defender redownloaded 0.0.4, when i run same command i get "the code execution cannot procede becouse VCRUNTIME140_1.DLL was not found. And same for. VCRUNTIME140.DLL
 SO this might be Windows Defender issue and VC redist 2015?

**Comment by gigantoq** [comment]
Problem solved to Caught exception "G1 element is invalid"
Whenever copy/paste from terminal or notepad into powershell ISE the paste key was different from the actual copyed. dont know why, i think a powershell problem?
