### ISSUE TITLE
terminate called after throwing an instance of 'std::runtime_error'

### ISSUE THREAD

**Issue by nerle** [madMAx43v3r/chia-plotter#434]
Hello,

I test now with a Ubuntu - install runs fine and the plotter seems to work for awhile. But ended with the following error.

I use a 2x2TB NVME Raid 0 for temp1 and temp2, dest is a local mounted samba share with rw rights, I tested wrting a file there. Any ideas?

best regards
Dirk

[P2] max_table_size = 4294975880
[P2] Table 7 scan took 24.715 sec
[P2] Table 7 rewrite took 42.5787 sec, dropped 0 entries (0 %)
[P2] Table 6 scan took 48.9477 sec
[P2] Table 6 rewrite took 96.1373 sec, dropped 581289532 entries (13.5343 %)
[P2] Table 5 scan took 46.1895 sec
[P2] Table 5 rewrite took 91.5503 sec, dropped 761971125 entries (17.741 %)
[P2] Table 4 scan took 45.7535 sec
[P2] Table 4 rewrite took 90.6437 sec, dropped 828797965 entries (19.2971 %)
[P2] Table 3 scan took 45.199 sec
[P2] Table 3 rewrite took 89.2031 sec, dropped 855043064 entries (19.9082 %)
[P2] Table 2 scan took 44.9345 sec
[P2] Table 2 rewrite took 89.1228 sec, dropped 865558506 entries (20.1528 %)
Phase 2 took 761.538 sec
Wrote plot header with 268 bytes
[P3-1] Table 2 took 53.4387 sec, wrote 3429416234 right entries
[P3-2] Table 2 took 43.8635 sec, wrote 3429416234 left entries, 3429416234 final
[P3-1] Table 3 took 87.7298 sec, wrote 3439880410 right entries
[P3-2] Table 3 took 45.4429 sec, wrote 3439880410 left entries, 3439880410 final
[P3-1] Table 4 took 87.8947 sec, wrote 3466132445 right entries
[P3-2] Table 4 took 46.2859 sec, wrote 3466132445 left entries, 3466132445 final
[P3-1] Table 5 took 89.3434 sec, wrote 3533004755 right entries
[P3-2] Table 5 took 47.1018 sec, wrote 3533004755 left entries, 3533004755 final
terminate called after throwing an instance of 'std::runtime_error'
  what():  thread failed with: position out of bounds (3532980223 + max(24374,24533))
Abgebrochen (Speicherabzug geschrieben)

**Comment by madMAx43v3r** [comment]
usually caused by RAM issues

**Comment by nerle** [comment]
Although I used all new components including RAM: you are right! Changed RAM and all is working fine now. Thank you very much for the plotter and your support!

Dirk, also from Germany :)
