### ISSUE TITLE
-n 4 >> only doing 1 plot

### ISSUE THREAD

**Issue by cojarbi** [madMAx43v3r/chia-plotter#439]
Started ./build/chia_plot  —n 4 -r 20 -u 64 -t /mnt/md0/ -d /mnt/md1/

Expecting:  rollover process until reach 4 plots

Result: stoped at 1 plot

**Comment by ataa** [comment]
use `-n 4` instead of `—n 4`

**Comment by madMAx43v3r** [comment]
good catch lol

**Comment by cojarbi** [comment]
I guess most are using default or infinite
