### ISSUE TITLE
Copy to .... failed with: fwrite() failed

### ISSUE THREAD

**Issue by imabbassayed** [madMAx43v3r/chia-plotter#440]
I have been running the platter for few days now but since yesterday i'm facing this issue !
Copy to ... plot failed with: fwrite() failed
What might the cause?

**Comment by madMAx43v3r** [comment]
destination drive full, or in case of network share failed network connection

**Comment by Hardcore-fs** [comment]
I've see this as well on linux....
Maybe there is a memory or file pointer leak...
something that continually crashes with this bug, after a restart of the system ... cleans right up.
but yes..  full drives or offline drives will do it as well, but neither of these are my issue...

**Comment by madMAx43v3r** [comment]
```
while(true) {
	const auto num_bytes = fread(buffer.data(), 1, buffer.size(), src);
	if(fwrite(buffer.data(), 1, num_bytes, dst) != num_bytes) {
		throw std::runtime_error("fwrite() failed");
	}
	if(num_bytes < buffer.size()) {
		break;
	}
}
```
There's not much to go wrong here, except some underlying issue where it cannot write to disk.

**Comment by madMAx43v3r** [comment]
@Hardcore-fs If you use USB attached drives, that's probably your culprit.

**Comment by imabbassayed** [comment]
@madMAx43v3r @Hardcore-fs  Thanks for the quick response.
The issue was the mounted drive being full.
