### ISSUE TITLE
Zombie proccess kept open after plot job is complete

### ISSUE THREAD

**Issue by delucca** [madMAx43v3r/chia-plotter#442]
Hi everyone 😄 

I've coded a [Madmax integration with Swar's plot manager](https://github.com/swar/Swar-Chia-Plot-Manager/pull/1198). The integration is working smoothly, but for some reason, we're facing an issue with zombie processes while using Madmax's plotter.

Since madmax's plotter launches the phase 5 (copy to HDD) in a new thread as default, when you create a new plot with `-n 1` for some reason the plotter is creating a zombie process. It may happen because the original plot process is different than the copy proccess.

Creating a zombie process would not be an issue, since it doesn't consume any resources, and the OS would take them away as soon as it notices it. But, Swar's plot manager (and I think maybe all plot managers) can have some issues with it, since they usually monitor the plotting process by checking the process name. Since the zombie process is named `[<original_proccess_name>] <defunct>`, the plot manager sees that process and thinks it is a running plot.

This issue is particularly annoying when you use a config like the following:
```
max_concurrent: 1
```
(or whatever your plot manager does to manage max concurrent plots)

When you do so, if a zombie process appear, the plot manager would simply think it is a running plot until it is cleaned by the OS

## Possible fix

I think a possible way to do so is by adding a conditional while creating the copy process. If `-n` is not provided or equals `1`, that should not launch a new process for a copy.

I see that as a proper way to do so, since if you're creating a single plot there is no reason to try to parallelize that step.

## Possible workarounds

We could code a logic inside the Swar plotter to ignore the Zombie proccess. But I sincerely think that this is a pretty ugly way to handle that, since that could lead to potentially other issues.

**Comment by madMAx43v3r** [comment]
It's not creating a new process... just another thread.

**Comment by madMAx43v3r** [comment]
See: https://askubuntu.com/questions/201303/what-is-a-defunct-process-and-why-doesnt-it-get-killed

> From your output we see a defunct, which means this child process has either completed its task or has been corrupted or killed. Its parent process is still running and has not noticed its dead child.

**Comment by madMAx43v3r** [comment]
It looks more like swar is not noticing that the chia_plot process has finished and thus it's stuck in <defunct>.

**Comment by delucca** [comment]
> It looks more like swar is not noticing that the chia_plot process has finished and thus it's stuck in defunct.

Thanks for the quick answer. I'm going to take a look at it. I don't know why Swar is not killing them properly. Probably a specific option is missing while launching the process.

Thanks anyway!
