### ISSUE TITLE
Add plot creation time in minutes

### ISSUE THREAD

**Issue by victorarthur** [madMAx43v3r/chia-plotter#447]
Could you please add a minutes measure next to the second just for quicker comparison?

ex.: `Total plot creation time was 2554.12 sec [42.57 minutes].`

**Comment by madMAx43v3r** [comment]
good idea lol

**Comment by smerchkz** [comment]
up) 

it seems that the feature is most needed, otherwise the calculator is already in the liver

lately I began to think in seconds and understand it a lot or a little)

**Comment by VertiHydro** [comment]
You better believe my mental arithmetic skills have been getting good... I can now recite pretty much any multiple of sixty because of this project

**Comment by madMAx43v3r** [comment]
done ;)
