### ISSUE TITLE
stop plotting on phase 1 with no error massage need help..

### ISSUE THREAD

**Issue by EFE2106** [madMAx43v3r/chia-plotter#449]
![problem](https://user-images.githubusercontent.com/85854630/121910652-b47e3f00-cd37-11eb-86a4-81cf11227495.png)

 I have 2 different m2 C:\ is too slow but plotting with it no problem(takes 2.5 hours) , however D:\ faster m2 (could do once in 50 min)  stucks on phase 1

my computer specs:
ryzen 7 3700x
b550 E motherboard
32 gb ram
samsung 980 pro 1tb

**Comment by scerbera** [comment]
Ran out of disk space, mem problem, oc too high. Start with those.

**Comment by EFE2106** [comment]
Disk space 900gb I think more than enough
mem porblem how can I check it ? (I use Ramcahce is it problem ?)
OC setting I made lowest still same

**Comment by QuarK02** [comment]
Same problem here
Any idea?
Xeon 12/24
256Gb ram (140 Ramdisk)
NVMe 1TB
