### ISSUE TITLE
keep getting "thread failed with: fopen() failed" error

### ISSUE THREAD

**Issue by twashington** [madMAx43v3r/chia-plotter#476]
I have the set up below and keep getting the "thread failed with: fopen() failed" error (full output below). chia_plot has read & write access to both temp drives. There's no SMART errors for the U.2 temp drive. The U.2 drive worked with no problem when I was running this program in Windows 10. The error even occurs when not using a 2nd temp drive (ramdisk), so it's not that. The same model U.2 drive is working without issue in another plotting machine with essentially the same hardware setup. Any ideas how to solve?

dual XEON E5-2651 v2 1.8 GHz 24c/48t
176 GB RAM
Dell Express Flash 1.6 TB NVMe (rebranded Samsung XS1715)
128 GB ramdisk (via tmpfs)
Ubuntu 20.04.2

```
Multi-threaded pipelined Chia k32 plotter - f495816
Final Directory: /mnt/u2green/
Number of Plots: infinite
Crafting plot 1 out of -1
Process ID: 11035
Number of Threads: 48
Number of Buckets: 2^7 (128)
Pool Public Key:   xxxxx
Farmer Public Key: xxxxx
Working Directory:   /mnt/u2green/
Working Directory 2: /mnt/ramdisk/
Plot Name: plot-k32-2021-06-14-19-46-xxxxx
[P1] Table 1 took 14.9819 sec
[P1] Table 2 took 152.971 sec, found 4295018388 matches
[P1] Table 3 took 179.724 sec, found 4294925745 matches
[P1] Table 4 took 218.128 sec, found 4294875042 matches
[P1] Table 5 took 215.692 sec, found 4294689364 matches
[P1] Table 6 took 208.46 sec, found 4294357457 matches
[P1] Table 7 took 165.345 sec, found 4293676360 matches
Phase 1 took 1155.33 sec
[P2] max_table_size = 4295018388
[P2] Table 7 scan took 12.8262 sec
[P2] Table 7 rewrite took 58.3852 sec, dropped 0 entries (0 %)
[P2] Table 6 scan took 38.0498 sec
[P2] Table 6 rewrite took 53.4809 sec, dropped 581355582 entries (13.5377 %)
[P2] Table 5 scan took 36.7685 sec
[P2] Table 5 rewrite took 55.6588 sec, dropped 762055630 entries (17.7441 %)
[P2] Table 4 scan took 32.4061 sec
[P2] Table 4 rewrite took 54.9468 sec, dropped 828906726 entries (19.2999 %)
[P2] Table 3 scan took 37.0746 sec
[P2] Table 3 rewrite took 57.9332 sec, dropped 855097660 entries (19.9095 %)
[P2] Table 2 scan took 36.5062 sec
[P2] Table 2 rewrite took 55.7784 sec, dropped 865645624 entries (20.1546 %)
Phase 2 took 567.484 sec
Wrote plot header with 268 bytes
terminate called after throwing an instance of 'std::runtime_error'
  what():  thread failed with: fopen() failed
```

**Comment by joelrb** [comment]
Same.

terminate called after throwing an instance of 'std::runtime_error'
  what():  thread failed with: input not sorted
Aborted (core dumped)

**Comment by mbruehl-ger** [comment]
Same. 
With old settings but after  a pull and rebuild  last night.

**Comment by cepheiden** [comment]
Same here. fresh pulled from github. 

dual xeon 4667v2 , 384gb RAM.

**Comment by madMAx43v3r** [comment]
> Same.
> 
> terminate called after throwing an instance of 'std::runtime_error'
> what(): thread failed with: input not sorted
> Aborted (core dumped)

That's not the same, that's probably unstable RAM...

**Comment by madMAx43v3r** [comment]
Ok try latest master, I might have miscalculated something in 89819ce189b81d7f965d27043949b52c8f53a562

**Comment by Hardcore-fs** [comment]
there is something else going on...
if it were that simple it would not be fixed by a re-boot.
I'm sure something is leaking someplace.....

**Comment by lookasiamrose** [comment]
Thank you, i jumped on this thread just now after getting this error and you manage to fix something just minutes ago :) Thats so perfect! It's like Christmas gift!

**Comment by twashington** [comment]
> Ok try latest master, I might have miscalculated something in [89819ce](https://github.com/madMAx43v3r/chia-plotter/commit/89819ce189b81d7f965d27043949b52c8f53a562)

Yup, the latest version as of 2 hours ago resolved this issue for me. Thanks!

**Comment by actuallymentor** [comment]
Not sure if it is a regression, but I am receiving this on an Ubuntu box with a `110G` ramdisk:

```shell
terminate called after throwing an instance of 'std::runtime_error'
  what():  thread failed with: fopen() failed
```
