### ISSUE TITLE
[Windows] Transfer speed after copying a plot to the destination directory always reported as 0 MB/s

### ISSUE THREAD

**Issue by elforesto** [madMAx43v3r/chia-plotter#484]
This is an issue unique to the Windows build. When a plot has completed copying to the destination directory, the message showing that it has finished always shows an average speed of 0 MB/s. This does not affect the Linux build which correctly reports the average speed.

**Comment by madMAx43v3r** [comment]
yes, because windows does a copy inside the `rename()` function, there's nothing I can do about it... except maybe some hack that if it finishes in less than 3 sec it was probably renamed and not copied...

**Comment by elforesto** [comment]
If you have the plot size and the time it took to transfer (which is reported correctly), it seems like it should be pretty easy to figure out the average transfer speed. Or does that require reworking the logic in that section of code?

**Comment by madMAx43v3r** [comment]
if the file was just renamed because final dir is on the same filesystem as tmp dir, then you'll get some crazy high number. But yeah maybe that's better than 0...

**Comment by madMAx43v3r** [comment]
should be fixed now
