### ISSUE TITLE
Add final destination copy

### ISSUE THREAD

**Issue by madMAx43v3r** [madMAx43v3r/chia-plotter#49]

**Comment by madMAx43v3r** [comment]
Yes, just to have better overview I filter by issues created by me.

**Comment by polkadotbabe** [comment]
Yes, like chia's plotter, a  -d /whatever/farming/dir/ would be great!

**Comment by delucca** [comment]
Looking forward for this!

**Comment by gimebreak** [comment]
really looking forward to that

**Comment by madMAx43v3r** [comment]
I've tested it once, it works. For now it doesn't detect if final dir is same block device as tmp dir though...

**Comment by madMAx43v3r** [comment]
It's merged
