### ISSUE TITLE
Start next run before complete copy

### ISSUE THREAD

**Issue by Baatezu** [madMAx43v3r/chia-plotter#499]
Hi, start next plot before fully complete copy to external HDD, and it's the slow whole process.
It's "hold" more space on temp folder

**Comment by Xuhnroo** [comment]
This would be really great to have.  I noticed that when I start my very first plot and it finishes, it goes to the next plot but when it tries to go to the third plot. It's stuck still copying the very first plot. If my transfer speed was faster, it would be fine though. Not sure why it's so slow on ubuntu but okay on windows.
![won't start next one](https://user-images.githubusercontent.com/79745542/122135728-a5b28d80-ce06-11eb-9554-93e6d5d681e4.jpg)

**Comment by Dartellum** [comment]
> Hi, start next plot before fully complete copy to external HDD, and it's the slow whole process.
> 
> It's "hold" more space on temp folder

Did you not search here or read the documentation? It does start next run while copying.

**Comment by stepgoku** [comment]
I Have this problem too

**Comment by Baatezu** [comment]
> > Hi, start next plot before fully complete copy to external HDD, and it's the slow whole process.
> > It's "hold" more space on temp folder
> 
> Did you not search here or read the documentation? It does start next run while copying.

No, didn't find any information

**Comment by jacy33** [comment]
> > Hi, start next plot before fully complete copy to external HDD, and it's the slow whole process.
> > It's "hold" more space on temp folder
> 
> Did you not search here or read the documentation? It does start next run while copying.

It does, but not the 3rd one. It can hold one copy in the process and one copy in the queue, but not two in the queue while processing one. I believe they're asking for such a feature.

**Comment by madMAx43v3r** [comment]
> But then again, there has to be a limit. Otherwise, sooner or later your temp is gonna be filled with all the plots being in the queue to be transferred and your whole plotter would crash.

this

**Comment by Baatezu** [comment]
when it copy its take ~160mbs (around 10min) and 52 min for the total plot create when it is plotting with copy its take a total for plotting 72 and copy speed 44mbs (45+min), and i think the problem can be with a small SSD when not enough time to hold one plot + new temp (not sure need check didn't have small SSD)
