### ISSUE TITLE
Ubuntu 20.04 crash without error

### ISSUE THREAD

**Issue by diegotanel** [madMAx43v3r/chia-plotter#500]
Hello.

I have a problem with the Mad Max plotter. I've been testing it for 6 days and it always fails.
Crashes without registration error and in any phase. Also I tested with many combinations of parameters.
I have the lastest commit from github.

I have 3 PCs for plots. 
Specs:
Ubuntu 20.04
32 Gb mem
Intel I5 10400 (6c/12Th)
Tmp drive: 2x1 TB NVMe WD 750 black (RAID 0)
Dst drive: HDD 10 TB Seagate

Logs

PC 1:
[P4] Finished writing C2 table
Phase 4 took 63.1196 sec, final plot size is 108820004972 bytes
Total plot creation time was 2761.72 sec (46.0287 min)
Started copy to /media/dtanel/hdd1plot/plot-k32-2021-06-15-17-42-ce5581aa1b3d7cefbff21e297d515f6f3f66529abd288df0abf2d4>Crafting plot 5 out of 6
Process ID: 27037
Number of Threads: 10
Number of Buckets: 2^7 (128)
Pool Public Key:   928a308d319b9144c66258e504afc5513e0af5da995b4a805fe1a2dca092e37d162d4402e95ac9cf06701d1dfc2654a6
Farmer Public Key: 8f81d7a136514c4e2445573387623c3bf13c7610d963e39815ecb0bda98c5ffc95e627ab3e642f155d0f85c4ca12e1f8
Working Directory:   /mnt/ssdtemp/
Working Directory 2: /mnt/ssdtemp/
Plot Name: plot-k32-2021-06-15-18-28-9cfc1805abf1ef8eb3377fdc389c03912b0647f4e40e56645bd79f1ed2a7d552
[P1] Table 1 took 23.6587 sec
[P1] Table 2 took 198.889 sec, found 4295039052 matches

PC 2:
Number of Plots: 2
Crafting plot 1 out of 2
Process ID: 3252846
Number of Threads: 12
Number of Buckets: 2^7 (128)
Pool Public Key:   928a308d319b9144c66258e504afc5513e0af5da995b4a805fe1a2dca092e37d162d4402e95ac9cf06701d1dfc2654a6
Farmer Public Key: 8f81d7a136514c4e2445573387623c3bf13c7610d963e39815ecb0bda98c5ffc95e627ab3e642f155d0f85c4ca12e1f8
Working Directory:   /mnt/ssdtemp/
Working Directory 2: /mnt/ssdtemp/
Plot Name: plot-k32-2021-06-15-18-00-7544723d5d6dbebafff23b862445a2768805cb1d6c8b33cc7f9f8f4db3497f07
[P1] Table 1 took 20.3757 sec
[P1] Table 2 took 187.388 sec, found 4295043619 matches
[P1] Table 3 took 216.747 sec, found 4295123903 matches
[P1] Table 4 took 265.005 sec, found 4295096255 matches
[P1] Table 5 took 260.14 sec, found 4295125307 matches
[P1] Table 6 took 249.603 sec, found 4295090098 matches
[P1] Table 7 took 195.129 sec, found 4294939112 matches
Phase 1 took 1394.51 sec
[P2] max_table_size = 4295125307
[P2] Table 7 scan took 15.5494 sec
[P2] Table 7 rewrite took 32.9628 sec, dropped 0 entries (0 %)
[P2] Table 6 scan took 39.874 sec
[P2] Table 6 rewrite took 67.0465 sec, dropped 581374701 entries (13.5358 %)
[P2] Table 5 scan took 38.4818 sec
[P2] Table 5 rewrite took 63.9578 sec, dropped 762078716 entries (17.7429 %)
[P2] Table 4 scan took 38.0322 sec
[P2] Table 4 rewrite took 63.7838 sec, dropped 828922210 entries (19.2993 %)
[P2] Table 3 scan took 37.7558 sec
[P2] Table 3 rewrite took 62.6074 sec, dropped 855189544 entries (19.9107 %)
[P2] Table 2 scan took 37.6382 sec
[P2] Table 2 rewrite took 63.1996 sec, dropped 865585616 entries (20.1531 %)
Phase 2 took 568.038 sec
Wrote plot header with 268 bytes
[P3-1] Table 2 took 51.7436 sec, wrote 3429458003 right entries
[P3-2] Table 2 took 44.3415 sec, wrote 3429458003 left entries, 3429458003 final
[P3-1] Table 3 took 67.7006 sec, wrote 3439934359 right entries
[P3-2] Table 3 took 46.3265 sec, wrote 3439934359 left entries, 3439934359 final

PC 3:
Crafting plot 5 out of 6
Process ID: 61559
Number of Threads: 10
Number of Buckets: 2^8 (256)
Pool Public Key:   928a308d319b9144c66258e504afc5513e0af5da995b4a805fe1a2dca092e37d162d4402e95ac9cf06701d1dfc2654a6
Farmer Public Key: 8f81d7a136514c4e2445573387623c3bf13c7610d963e39815ecb0bda98c5ffc95e627ab3e642f155d0f85c4ca12e1f8
Working Directory:   /mnt/ssdtemp/
Working Directory 2: /mnt/ssdtemp/
Plot Name: plot-k32-2021-06-15-18-31-3c67e66c7b417e01e54c1cdbacc9e1ff4805e5171c68839ad2fb73949841f204
[P1] Table 1 took 24.6473 sec

Can you help me?
Thank you

**Comment by OsvaldoGDelRio** [comment]
Y leave some threads for the system and farming if you doing in the same PC?

i have a 8core i7 , i just use 14 threads

**Comment by 69chargr** [comment]
I've been having the same problem in Ubuntu. I had to back off my CPU overclock and I also switched my nvme RAID 0 to ext4, I don't think it liked XFS. 13 plots into a 90 plot run and so far no freezes.

**Comment by diegotanel** [comment]
@69chargr , thank you for your response. 
My RAID 0 is ext4.
Maybe the crash is related to the CPU configuration? I have all the stock values. I don't OC my CPU.
What test can I take? Or how can the error be logged?
Thank you

**Comment by 69chargr** [comment]
That's beyond my ability. For all I know this could crash after my next reboot but for now it's working. I know my setup despises 256 bucket size. Crashes 100% of the time. 128 is much more stable. I'm doing P1 on the raid 0 array and ramdisk for the rest. Never crashes in P2 thru P4 so I know it's something with the NVMe array. Both drives pass all standard tests individually.

**Comment by MrMorcego** [comment]
On ubuntu 20.04 madmax stops working between **P1 Table 3** and **P1 Table 4**. It "kills" the process. Any solution for the problem?

**Comment by rsulym** [comment]
> On ubuntu 20.04 madmax stops working between **P1 Table 3** and **P1 Table 4**. It "kills" the process. Any solution for the problem?

same here

**Comment by diegotanel** [comment]
Does anyone have any solutions?

**Comment by madMAx43v3r** [comment]
if it gets killed, you ran out of RAM

**Comment by diegotanel** [comment]
I tried with 2 TH and 128 buckets
Crafting plot 2 out of 6
Process ID: 34337
Number of Threads: 2
Number of Buckets: 2^7 (128)
[P2] Table 4 scan took 71.1961 sec
[P2] Table 4 rewrite took 167.015 sec, dropped 828948930 entries (19.3 %)
[P2] Table 3 scan took 71.5442 sec
[P2] Table 3 rewrite took 166.475 sec, dropped 855128835 entries (19.9096 %)
[P2] Table 2 scan took 71.7522 sec
dtanel@chia-rig1:~/chia-plotter$

**Comment by vmallet** [comment]
Same here, on an older machine with 2x Xeon 5410 (old!), Ubuntu 20.04.
 
However it gets killed because of an invalid opcode (as found from dmesg):
"[39678.126371] traps: chia_plot[3512] trap invalid opcode ip:55e0702a51a8 sp:7ffc3a423380 error:0 in chia_plot[55e070267000+17a000]"

**Comment by diegotanel** [comment]
> if it gets killed, you ran out of RAM

Hello @madMAx43v3r . 
First, thank you for you plotter development!

I´m monitoring the PC and have a lot of free memory when plotting.

<img width="454" alt="Total memory" src="https://user-images.githubusercontent.com/1225566/122443107-a3227600-cf75-11eb-9865-1510d7ae6adf.png">

<img width="445" alt="RAM Used" src="https://user-images.githubusercontent.com/1225566/122443145-a9b0ed80-cf75-11eb-9131-f616b2c5111f.png">

**Comment by diegotanel** [comment]
Hello @madMAx43v3r 

I found the problem and have no relation to the memories.
When I ran chia_plotter mad max, I added the ampersand sign to do the background process. Like this:
./build/chia_plot -p  $$$ -f $$$ -n -1 -r 12 -t /mnt/ssdtemp/ -d /media/dtanel/hdd1plot/ >> $(date '+%Y-%m-%d_%H_%M_%S').log **&**
And with that, the process dies at random. I don't know why, but that's the problem.
I appreciate for your help.
Thank you.

**Comment by rsulym** [comment]
i have same issue here, but i'm running via screen command, e.g. screen -d -m -S chiaX bash -c 'plot here| tee <log>'
some processes went fine, some got sporadically killed after Phase 2
@diegotanel did you managed your issue?

**Comment by diegotanel** [comment]
Hello @rsulym.
I´m using Screen o tmux, and I had no problems again.

**Comment by rsulym** [comment]
Hi @diegotanel 
could you pls give your full string? i have to try, maybe some argument did the trick.

**Comment by diegotanel** [comment]
You must have the uuid package installed.
This is my script:

cat chia_plotter_startup.sh
#!/bin/bash
export POOLKEY="$$$"; \
export FARMERKEY="$$$"; \
~/chia-plotter/build/chia_plot \
--poolkey=$POOLKEY \
--farmerkey=$FARMERKEY \
--tmpdir=/mnt/ssdtemp/ \
--finaldir=/media/dtanel/hdd3plot/ \
--count=60 \
--threads=10 \
--buckets=7 \
 2>&1 | tee ~/chia-plotter/log/$(date '+%Y-%m-%d_%H_%M_%S')-$(uuid).log;

**Comment by rsulym** [comment]
@diegotanel thanks, but how exactly do you run your script in background?

**Comment by diegotanel** [comment]
1. tmux
2. ./chia_plotter_startup.sh
