### ISSUE TITLE
thread failed with: fwrite() failed

### ISSUE THREAD

**Issue by joehuchina** [madMAx43v3r/chia-plotter#53]
Config: 

root@fullnode-178:/mnt/plotter/chia-plotter-master/build# lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          56
On-line CPU(s) list:             0-55
Thread(s) per core:              1
Core(s) per socket:              2
Socket(s):                       28
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           79
Model name:                      Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
Stepping:                        1
CPU MHz:                         2399.998
BogoMIPS:                        4799.99
Hypervisor vendor:               VMware
Virtualization type:             full
L1d cache:                       896 KiB
L1i cache:                       896 KiB
L2 cache:                        7 MiB
L3 cache:                        980 MiB
NUMA node0 CPU(s):               0-27
NUMA node1 CPU(s):               28-55

#temp  disk size
/dev/sdb1       215G  1.6G  214G   1% /mnt/temp
#RAM  disk size 
tmpfs           119G     0  119G   0% /mnt/ram

#  ** insteaded my key
root@fullnode-178:/mnt/plotter/chia-plotter-master/build# ./chia_plot    ** **   /mnt/temp/ /mnt/ram/  40  7

d[P1] Table 1 took 18.2994 sec
[P1] Table 2 took 113.407 sec, found 4295018656 matches
[P1] Lost 51548 matches due to 32-bit overflow.
[P1] Table 3 took 138.035 sec, found 4294994683 matches
[P1] Lost 27160 matches due to 32-bit overflow.
[P1] Table 4 took 161.754 sec, found 4295049757 matches
[P1] Lost 83006 matches due to 32-bit overflow.
[P1] Table 5 took 152.327 sec, found 4295069366 matches
[P1] Lost 102254 matches due to 32-bit overflow.
[P1] Table 6 took 157.915 sec, found 4295102891 matches
[P1] Lost 135102 matches due to 32-bit overflow.
[P1] Table 7 took 128.309 sec, found 4295063551 matches
Phase 1 took 870.071 sec
[P2] max_table_size = 4295102891
[P2] Table 7 scan took 10.7147 sec
[P2] Table 7 rewrite took 46.0822 sec, dropped 0 entries (0 %)
[P2] Table 6 scan took 26.1113 sec
[P2] Table 6 rewrite took 31.4663 sec, dropped 581375586 entries (13.5358 %)
[P2] Table 5 scan took 25.4418 sec
[P2] Table 5 rewrite took 29.9749 sec, dropped 762020496 entries (17.7418 %)
[P2] Table 4 scan took 25.6755 sec
[P2] Table 4 rewrite took 29.6732 sec, dropped 828927576 entries (19.2996 %)
[P2] Table 3 scan took 28.4565 sec
[P2] Table 3 rewrite took 29.3028 sec, dropped 855090576 entries (19.909 %)
[P2] Table 2 scan took 29.123 sec
terminate called after throwing an instance of 'std::runtime_error'
  what():  thread failed with: thread failed with: fwrite() failed
Aborted (core dumped)

What's the fwirite() mean , how can i fix it

**Comment by xydrine** [comment]
Try updating your branch to the latest master.

**Comment by madMAx43v3r** [comment]
`/dev/sdb1 215G 1.6G 214G 1% /mnt/temp`

Does that mean only 215G free?

**Comment by joehuchina** [comment]
Yes Solved after exepand  /mnt/temp  to 250GB  .    Other question ,  where to set the dir  for  final  .plot file.  Currently i found  it was in /mnt/temp/  after job done.

**Comment by joehuchina** [comment]
> `/dev/sdb1 215G 1.6G 214G 1% /mnt/temp`
> 
> Does that mean only 215G free? You might need a bit more...

Yes Solved after exepand /mnt/temp to 250GB . Other question , where to set the dir for final .plot file. Currently i found it was in /mnt/temp/ after job done.

**Comment by VertiHydro** [comment]
> > `/dev/sdb1 215G 1.6G 214G 1% /mnt/temp`
> > Does that mean only 215G free? You might need a bit more...
> 
> Yes Solved after exepand /mnt/temp to 250GB . Other question , where to set the dir for final .plot file. Currently i found it was in /mnt/temp/ after job done.

"final dir" is not implemented yet - should be coming soon though! You can track progress here: #49
