### ISSUE TITLE
"Crafting plot X out of X" showing on Intel CPU but not AMD

### ISSUE THREAD

**Issue by maxchock** [madMAx43v3r/chia-plotter#546]
Hi, I have 3 PC for plotting, 1 intel i5 and 2 AMD FX8350. On intel machine, it will always show "Crafting plot X out of XX" but on both of the AMD machine, none of them will show this. 3 of them all using same version of Linux mint 20.1.

**Comment by number435398** [comment]
I have 2 intel and 1 amd plotting.  All 3 show the plot x out of xx no problem. Did you select the AMD to do "-1" or "infinite"?

**Comment by ataa** [comment]
> it will always show "Crafting plot X out of XX" but on both of the AMD machine, none of them will show this.

You are using the older version on the AMD machines, check for the number after "`Multi-threaded pipelined Chia k32 plotter - `" and compare it on all machine.

On mine, it's "`Multi-threaded pipelined Chia k32 plotter - 9e7902c`"

**Comment by Dartellum** [comment]
Latest is https://github.com/madMAx43v3r/chia-plotter/commit/9e649ae71532e068b1c58a4187a396bce866eeb0

**Comment by maxchock** [comment]
Oh ya.  My bad. I actually install all of them on the same day, I guess it got updated before the Intel machine.

Thanks.

> > it will always show "Crafting plot X out of XX" but on both of the AMD machine, none of them will show this.
> 
> You are using the older version on the AMD machines, check the number after "`Multi-threaded pipelined Chia k32 plotter - `" and compare it on all machine.
> 
> On mine, it's "`Multi-threaded pipelined Chia k32 plotter - 9e7902c`"
