### ISSUE TITLE
Set temp to 5TB  SSD and temp2 to 110G ram

### ISSUE THREAD

**Issue by joehuchina** [madMAx43v3r/chia-plotter#56]
Can i set the temp folder larger to store more final plot file ?  
Would it still possible to arrange the 75% work to 110G  ram space  if i did this ?

**Comment by VertiHydro** [comment]
Yes - what problem did you think you might have?

**Comment by VertiHydro** [comment]
@joehuchina - feel free to close this issue unless there's anything else you'd like to ask.
