### ISSUE TITLE
System Crash on Ubuntu 20.04.2 LTS

### ISSUE THREAD

**Issue by Xefier** [madMAx43v3r/chia-plotter#560]
System
E5 2699 v3
64GB RAM
Temp Drive = x2 2TB SSD in RAID 0

Tried the following settings but it always crashes eventually in phase 1 within the first 6 tables
Number of threads = 30, 36 
Number of buckets = 128, 256

There is no error message or anything, the whole system freezes and I have to force shut it down

I have been plotting with the regular plotter for over a month now
Also looked into whether it's an SSD overheating issue but the temp was 44 Celsius last time it crashed

**Comment by cyperbg** [comment]
First update to the latesdt version of the plotter
You don't need that many threads. Try with 20 and definitely use 512 buckets.

**Comment by Xefier** [comment]
It worked on x2 HDDs with 36 threads and 128 buckets so the problem is with the SSDs.
My CPU has 36 threads (18 physical cores) so why wouldn't I use them all? Also 512 buckets doesn't make sense cause it uses less RAM but more I/O and even at 128 it's barely using any of my RAM and I will be doubling my RAM capacity to 128GB soon so I can do a RAM disk and have SAS drive hardware on the way and I might sell the SSDs since Mad Max is crashing on them.

**Comment by Xefier** [comment]
Also the regular plotter works fine, I can do 8 in parallel on my x2 2TB RAID0 SSDs

**Comment by Xefier** [comment]
I actually got a crash using the old plotter when using those same SSDs so I've switched to RAM Disk + HDD until my SATA drives show up

**Comment by Xefier** [comment]
Turns out the issue was caused by my SSDs in RAID0 being formatted with XFS.
Once I used Ext4 it no longer crashed the system.
