### ISSUE TITLE
add a directory for finished plot

### ISSUE THREAD

**Issue by inabon** [madMAx43v3r/chia-plotter#564]
Hi there:
We have a NAS where we store all plots and plotters that use your script to send to it. We can map a network drive to the plotting box and use it as final directory no issues as expected but, when your script starts to copy to that directory it is copying from the one that it starts to plot at thus slowing down transfer process. Would it be to hard to make it a 4 directory scheme:
plottingdir1
plottingdir2
completeplotdir
finaldirectory

The idea is to move the complete plot in the plotter machine away from the very busy plotting dir so it can be moved to anywhere without compromising plotting IO and transfer IO.

If you point us in the right direction we could help adding the feature and contributing.

cheers

**Comment by VertiHydro** [comment]
> Hi there:
> We have a NAS where we store all plots and plotters that use your script to send to it. We can map a network drive to the plotting box and use it as final directory no issues as expected but, when your script starts to copy to that directory it is copying from the one that it starts to plot at thus slowing down transfer process. Would it be to hard to make it a 4 directory scheme:
> plottingdir1
> plottingdir2
> completeplotdir
> finaldirectory
> 
> The idea is to move the complete plot in the plotter machine away from the very busy plotting dir so it can be moved to anywhere without compromising plotting IO and transfer IO.
> 
> If you point us in the right direction we could help adding the feature and contributing.
> 
> cheers

I'm afraid this is far from the first time somebody has asked for this. The general feeling is that this feature will not be included into the plotter to avoid overcomplication. That _may_ change at a later date, but for now the best idea is just to write an external script that watches for new files in your completeplotdir and automatically moves them to your finalfirectory.

**Comment by inabon** [comment]
oh ok nevermind then thanks.
