### ISSUE TITLE
Yes - what problem did you think you might have?

### ISSUE THREAD

**Issue by joehuchina** [madMAx43v3r/chia-plotter#57]
Yes - what problem did you think you might have?

_Originally posted by @VertiHydro in https://github.com/madMAx43v3r/chia-plotter/issues/56#issuecomment-857460692_

I thought the total file size is 330GB.   Temp folder could not be too large.  that's my misunderstood

**Comment by VertiHydro** [comment]
Ohhh haha yeah no you can make the temp folder as large as you want. It just has to be at least ~210gb if you are using ramdisk, and ~320 if just using ssd.

**Comment by VertiHydro** [comment]
@joehuchina if that answers your question, feel free to close issues #56 and #57.
