### ISSUE TITLE
Error after upgrading to default = 256 bucket size

### ISSUE THREAD

**Issue by brianwfreeman** [madMAx43v3r/chia-plotter#579]
I am running this on Ubuntu Desktop on a 64 core Threadripper and 256GB of RAM and a 128GB RAMdisk.

I get error:

[P1] Table 1 took 6.82463 sec
terminate called after throwing an instance of 'std::runtime_error'
  what():  thread failed with: input not sorted
Aborted (core dumped)

My command was: ./chia_plot -n 50 -r 64 -t /media/brian/1.5TBOptane/ -2 /mnt/ramdisk/ -d '/media/brian/Seagate Backup Plus Drive4/'

This didn't happen prior to my upgrade of chia-plotter.

**Comment by brianwfreeman** [comment]
![Screenshot from 2021-06-19 07-53-00](https://user-images.githubusercontent.com/17950149/122646362-96b42f80-d0d3-11eb-9541-40796033e031.png)

**Comment by brianwfreeman** [comment]
Here is another error that looks different without using RAMdisk
![Screenshot from 2021-06-19 07-58-27](https://user-images.githubusercontent.com/17950149/122646485-3671bd80-d0d4-11eb-88df-df9f2cc97fe0.png)

**Comment by brianwfreeman** [comment]
I may have found the issue. I deleted chia-plotter and re-installed.  When compiling the Build, I get the following error:
![Screenshot from 2021-06-19 08-33-23](https://user-images.githubusercontent.com/17950149/122647444-1abce600-d0d9-11eb-8f51-185ed33e6e50.png)

**Comment by madMAx43v3r** [comment]
unstable RAM or CPU

**Comment by brianwfreeman** [comment]
You are correct MadMax. Unstable RAM. It is fixed now.

Thank you for your work on this amazing project!!

**Comment by stefanel96** [comment]
@brianwfreeman can have a conversation somewhere, I think I am so close to fixing it, but I need some help?
