### ISSUE TITLE
Build Error Ubuntu Desktop 20.04

### ISSUE THREAD

**Issue by brianwfreeman** [madMAx43v3r/chia-plotter#582]
```
[100%] Built target test_phase_1
corrupted size vs. prev_size in fastbins
/tmp/ccmSV9NJ.s: Assembler messages:
/tmp/ccmSV9NJ.s: Internal error (Aborted).
Please report this bug.
make[2]: *** [CMakeFiles/chia_plot.dir/build.make:63: CMakeFiles/chia_plot.dir/src/chia_plot.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:406: CMakeFiles/chia_plot.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by brianwfreeman** [comment]
![Screenshot from 2021-06-19 09-18-14](https://user-images.githubusercontent.com/17950149/122648729-5490eb00-d0df-11eb-9d91-4bed4992837d.png)

**Comment by number435398** [comment]
I'd say start over again and double check you are following all the steps specified on the page or post all text from all steps up to the error, that may help. There doesn't appear to be anything there that properly references the source of your error.

**Comment by brianwfreeman** [comment]
I will close this as an issue because I think it was a BIOS RAM setting issue for me.
