### ISSUE TITLE
Plotter randomly crashes sometimes

### ISSUE THREAD

**Issue by funnycubeguy** [madMAx43v3r/chia-plotter#587]
Sometimes the plotter works and other times it crashes ending with the error below.

> [P1] Table 1 took 12.5863 sec
> [P1] Table 2 took 91.4754 sec, found 4294987732 matches
> [P1] Table 3 took 113.272 sec, found 4294994144 matches
> [P1] Table 4 took 138.587 sec, found 4295002305 matches
> [P1] Table 5 took 134.025 sec, found 4295031184 matches
> [P1] Table 6 took 128.737 sec, found 4295113872 matches
> [P1] Table 7 took 95.7562 sec, found 4295137959 matches
> Phase 1 took 714.463 sec
> [P2] max_table_size = 4295137959
> [P2] Table 7 scan took 16.8981 sec
> [P2] Table 7 rewrite took 42.6332 sec, dropped 0 entries (0 %)
> [P2] Table 6 scan took 29.963 sec
> [P2] Table 6 rewrite took 51.6299 sec, dropped 581369350 entries (13.5356 %)
> [P2] Table 5 scan took 27.7986 sec
> chia_plot: /home/plotter/chia-plotter/include/chia/bitfield_index.hpp:45: std::pair<long unsigned int, long unsigned int> bitfield_index::lookup(uint64_t, uint64_t) const: Assertion `bitfield_.get(pos) && bitfield_.get(pos + offset)' failed.
> Aborted

Debian 10 64bit buster
ryzen 3900x

> lscpu | grep popcnt
> Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate sme ssbd mba sev ibpb stibp vmmcall sev_es fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca

**Comment by dendisuhubdy** [comment]
happens to me too @funnycubeguy

**Comment by funnycubeguy** [comment]
> happens to me too @funnycubeguy

it is caused by overclocked ram. try disabling xmp or adding voltage to dram

**Comment by stefanel96** [comment]
@funnycubeguy hey, how much voltage did you add, because if I add small amount - error still pops up, if I add bigger - whole system crashes? I've been incrementing voltage by 0.005 of course?

**Comment by ascandal** [comment]
These random crashes started for me after pulling from master and rebuilding. This didn't happen on previous "versions". However I'm having a hard time determining the previous commit version that was working with out crashing. My RAM is already set to auto and if anything under clocked in the bios.

No idea how to adjust voltage for RAM as suggested in comment above.

ubuntu 20.04, AMD Ryzen threadripper 3970x
