### ISSUE TITLE
Taproot changes needed

### ISSUE THREAD

**Issue by leotancredi** [madMAx43v3r/chia-plotter#588]
Per [this tweet](https://twitter.com/bramcohen/status/1404973519931281412?s=20) it seems this alternative plotter would need to implement [this PR](https://github.com/Chia-Network/chia-blockchain/pull/6692/) ASAP to create plots compatible with chia's taproot.

**Comment by madMAx43v3r** [comment]
See #529
ASAP right, once they've merged it into their master maybe
