### ISSUE TITLE
Use BLAKE3 submodule with latest code

### ISSUE THREAD

**Issue by madMAx43v3r** [madMAx43v3r/chia-plotter#59]
https://github.com/BLAKE3-team/BLAKE3

**Comment by madMAx43v3r** [comment]
https://github.com/madMAx43v3r/chia-plotter/issues/70#issuecomment-857664855

**Comment by AndyRPH** [comment]
Does this take into account the blake3 version that uses NEON for ARM cpus that support it like the apple M1?  I don't see it listed in the CMakeLists.txt .
