### ISSUE TITLE
Passing variables to tmpdir and finaldir

### ISSUE THREAD

**Issue by clearfrost** [madMAx43v3r/chia-plotter#592]
Calling the plotter from a bash script with these variables:
`TEMPDIR=/mnt/tmp/`
`DESTDIR=/mnt/dst/`

`./chia_plot --tmpdir ${TMPDIR} --finaldir ${DESTDIR} (rest of command here)`
gives this error:

`Invalid tmpdir: --finaldir (needs trailing '/' or '\')`

Only a problem when using variables.
Notice also that error message mixes tmpdir and finaldir.

**Comment by carlfarrington** [comment]
I don't think it is mixing tmpdir and finaldir. As far as it is concerned, you have specified '--finaldir' as the input to the tmpdir option.
Essentially your variables have disappeared / turned blank.

**Comment by carlfarrington** [comment]
Upon closer examination, it's because you created a variable called TEMPDIR (with an E in its name), but you specified ${TMPDIR} without an E

**Comment by clearfrost** [comment]
You're absolutely right, how embarrassing. Sorry to waste your time.
