### ISSUE TITLE
mad MAx

### ISSUE THREAD

**Issue by chiabro23** [madMAx43v3r/chia-plotter#613]
madmax plotter windows makes 2-3 plots then it waits until it is transferred to the hdd and that sarting again can someone help me Please

**Comment by chiabro23** [comment]
I start with 20 plots the first 2-3 plots it does without waiting after the 3 plot it waits until it is transferred to the hdd at the beginning everything went well why does this happen to me now

**Comment by asukahan** [comment]
Maybe the queue of transferring is full? increase the speed of transferring and try again.

**Comment by madMAx43v3r** [comment]
yeah it waits until previous copy is finished

**Comment by chiabro23** [comment]
how can i increase the transfer speed do you have an idea
