### ISSUE TITLE
[Cosmetic] Align -u, --buckets arg with official plotter

### ISSUE THREAD

**Issue by Forusim** [madMAx43v3r/chia-plotter#63]
First of all, thank you for implementing the arguments as drop in replacement for official plotter. 
However in official chia plotter for -u the default value is 128, which probably is internally transferred to 2⁷ as you did.
For consistency sake please adopt -u arg to the official way, so people may not accidentally crank up their buckets.

**Comment by madMAx43v3r** [comment]
Yeah I noticed... but there is a check now, you cannot set it to 128 anymore haha.

**Comment by madMAx43v3r** [comment]
It's aligned, see 8581ad8f34d33091279d2e8c850c2fc2b4f4e4bb
However if you specify a value <16 it's like before: 2^x
So it's backwards compatible to those who didn't get the memo.
