### ISSUE TITLE
uint128_t error

### ISSUE THREAD

**Issue by Uly41** [madMAx43v3r/chia-plotter#64]
just compiling for windows via mingw64+gcc 10.3.0.
system has no way to understand uint128_t.
and of course not recognize the include uint128_t.h in include/chia/util.hpp

**Comment by madMAx43v3r** [comment]
There's a lib for it in `chiapos`, I can include it here too... ToDo

**Comment by grayfallstown** [comment]
@Uly41 can you please post the steps taken so far to compile it? I always end up with libsodium problems on windows.
