### ISSUE TITLE
128 GB of ram (110 ramdisk) is suddenly not enough

### ISSUE THREAD

**Issue by kastermight** [madMAx43v3r/chia-plotter#646]
So, I've been plotting on a 8c/8t machine using 110GB ramdisk (out of 128GB total) just fine. But now, when I use a very similar setup but with 24c/48t CPU, suddenly during the creation of table 3 on phase 1 entire ram gets used and the whole machine freezes until the process quits. Is it the number of cores that makes it to use more ram now?

**Comment by kastermight** [comment]
I can't take a screenshot right before the rig freezes but it's something like 25GB. I don't think that's a normal ram usage for the plotter is it?

**Comment by kastermight** [comment]
Actually I could manage to take some screenshots this time
![Screenshot from 2021-06-23 00-49-36](https://user-images.githubusercontent.com/2565943/123060671-ceff8a80-d3bf-11eb-9b40-203153f47731.png)
![Screenshot from 2021-06-23 01-09-11](https://user-images.githubusercontent.com/2565943/123060676-cf982100-d3bf-11eb-818a-0a5f1e6defd2.png)

**Comment by we-sell-bags** [comment]
it's a parallel plotter......
you use more cores , it uses more ram....

i'd track the size of your swap file as you run the plotter......

bet its eating the  swap... then killing the system.

**Comment by kastermight** [comment]
Ugh... I'm an idiot. It says right there on the main page - 0.5GB per thread. Case closed.
