### ISSUE TITLE
Fater Plotting Ryzen 9 5900 24 threads  2x samsung ssd 980 pro 2 tb  64Gb Ram

### ISSUE THREAD

**Issue by chiabro23** [madMAx43v3r/chia-plotter#647]
Ryzen 9 5900 24 threads

2x samsung ssd 980 pro 2 tb

64Gb Ram

I come to 31 min do you have a better setting for me?

**Comment by Ujang360** [comment]
Ryzen's have CCD (or CCX or Core Complex) architecture, you need to use `taskset` if using linux or other CPU core pinning methods in Windows.

For example, I have Ryzen 9 5950, which has 2 CCX (CCX 0 -> Core 0,1,2,3,4,5,6,7, CCX 1 -> Core 8,9,10,11,12,13,14,15), so I ran the `chia_plot` like this:

```bash
taskset -c 0,1,2,3,4,5,6,7 chia_plot ...
```

and

```bash
taskset -c 8,9,10,11,12,13,14,15 chia_plot ...
```

Also, for the temp drive, don't forget to mount it with `discard` and `noatime`, format it with no journaling for `ext4` or `-m crc=0` for `xfs`.

### Note

You didn't specify more information like your OS, partition type (RAID or no-RAID), so YMMV and goodluck

**Comment by chiabro23** [comment]
thx for the information but i using mad max for windows do you have any idea for windows
