### ISSUE TITLE
[NOT AN ISSUE] emmm..stupid question..how to run?

### ISSUE THREAD

**Issue by madmmmax** [madMAx43v3r/chia-plotter#66]
root@Ubuntu20LTS59x:/mnt/source/chia-plotter/build# lmb
total 94M
-rwxr-xr-x  1 root root  2M 6月   9 18:44 check_phase_1
-rwxr-xr-x  1 root root 43M 6月   9 18:44 chia_plot
-rw-r--r--  1 root root  1M 6月   9 18:44 CMakeCache.txt
drwxr-xr-x 16 root root  1M 6月   9 18:44 CMakeFiles
-rw-r--r--  1 root root  1M 6月   9 18:44 cmake_install.cmake
drwxr-xr-x  5 root root  1M 6月   9 18:44 _deps
drwxr-xr-x  3 root root  1M 6月   9 18:44 lib
-rw-r--r--  1 root root  1M 6月   9 18:44 libblake3.a
-rw-r--r--  1 root root  7M 6月   9 18:44 libbls.a
-rw-r--r--  1 root root  1M 6月   9 18:44 libchia_plotter.a
-rw-r--r--  1 root root  1M 6月   9 18:44 libfse.a
-rw-r--r--  1 root root  1M 6月   9 18:44 Makefile
drwxr-xr-x  2 root root  1M 6月   9 18:44 object_blstmp
drwxr-xr-x  2 root root  1M 6月   9 18:44 object_gmp
drwxr-xr-x  2 root root  1M 6月   9 18:44 object_relic_s
drwxr-xr-x  2 root root  1M 6月   9 18:44 object_sodium
-rwxr-xr-x  1 root root  1M 6月   9 18:44 test_copy
-rwxr-xr-x  1 root root  3M 6月   9 18:44 test_disk_sort
-rwxr-xr-x  1 root root 20M 6月   9 18:44 test_phase_1
-rwxr-xr-x  1 root root  5M 6月   9 18:44 test_phase_2
-rwxr-xr-x  1 root root 12M 6月   9 18:44 test_phase_3
-rwxr-xr-x  1 root root  4M 6月   9 18:44 test_phase_4
root@Ubuntu20LTS59x:/mnt/source/chia-plotter/build# chia_plot
chia_plot: command not found
root@Ubuntu20LTS59x:/mnt/source/chia-plotter/build# 

**Can someone help me with this?
Thanks**

**Comment by grayfallstown** [comment]
`./chia_plot` not `chia_plot`

**Comment by madmmmax** [comment]
> `./chia_plot` not `chia_plot`

hahahahaha, thanks man, I cant help with laughting at myself
