### ISSUE TITLE
Portable plot support

### ISSUE THREAD

**Issue by digitalscream** [madMAx43v3r/chia-plotter#67]
This isn't an immediate request, just a placeholder in case anyone wants to talk about it. Lots of chatter on various Discords about it, so...worth asking the question.

So, Mr Max, do you have any visibility of a timescale between the release of portable plot functionality to mainnet and it being integrated into this plotter?

**Comment by madMAx43v3r** [comment]
Once I know what it entails I can make an estimate. Do you have any info on how it's implemented?

**Comment by digitalscream** [comment]
I don't, I'm afraid - I'm a developer, but not with Chia (or anything at this level, to be honest, so I wouldn't be of any use). I guess, really, I just wanted to see if it was on your radar. 

I've done a lot of dicking around with your plotter, though, and found some interesting ways to optimise its usage on cheaper older systems with only spinning disks. It's actually been quite fun, which is all I can hope for with almost zero chance of a block win these days, so thank you for that :)

**Comment by RamonRobben** [comment]
@madMAx43v3r I am not a Python developer but perhaps you can take a look [here](https://github.com/Chia-Network/chia-blockchain/blob/pools.2021-may-25/chia/plotting/create_plots.py) It has some references in the create_plots.py file to pools. But as far as I can see no major implementation details other than a using a pool key.

**Comment by madMAx43v3r** [comment]
@RamonRobben That code hasn't been changed for a while, at least not in that pool branch. Pool Key we already have, if that's all we need...

Well, there is also this "pool contract puzzle", which I don't currently support, maybe that'll be used for actual pools...

**Comment by RamonRobben** [comment]
@madMAx43v3r True but I saw a reference to pool_key and pool_puzzles which are new to me. And I thought maybe someone smarter can find other links to how those pool puzzles work and how they are solved. Which they might be able to reverse engineer or something idk xD

**Comment by digitalscream** [comment]
> Well, there is also this "pool contract puzzle", which I don't currently support, maybe that'll be used for actual pools...

I watched a bit of the "pools for developers" stream a week or so ago - from what I saw, the contract puzzles are definitely a core part of the pools design. Didn't fully understand the whole thing, though.

**Comment by madMAx43v3r** [comment]
Yeah that makes sense, because with the pool public key the plots would be hardcoded to a specific pool.

**Comment by PeratX** [comment]
A new algorithm for plot id (one parameter for chiapos), you can implement it in a easy way once it comes online.

**Comment by madMAx43v3r** [comment]
And a different memo content I suppose?

**Comment by PeratX** [comment]
> And a different memo content I suppose?

Yes. current plot id is genereted by pool id and some random stuff, portable plot replaces or add one parameter in that process (maybe the pool NFT address)

**Comment by madMAx43v3r** [comment]
[https://github.com/Chia-Network/chia-blockchain/wiki/Chia-Keys-Architecture#plot-ids]()

**Comment by madMAx43v3r** [comment]
#529

**Comment by digitalscream** [comment]
Top work, sir :)

**Comment by HEROFreeman** [comment]
respect :)
