### ISSUE TITLE
[BUG] -d argument is not optional

### ISSUE THREAD

**Issue by mist0706** [madMAx43v3r/chia-plotter#68]
Am running the plotter compiled at:

> mist@fp-plotty1:~/chia-plotter$ git rev-parse --short HEAD
> 9eec7e7

When running the command 
./chia_plot -p 8665fca93ad0fdd35181f98d1481af5566f0c52a6cf2d9ef7aacafc0569a8d73fe2bce115646b4d9c2f2797d7dd5af5e -f b8d85fe185959f9b72a75996987e11437ae164731abac9dab3d939352259dcf2d05f4f1019f830b01f259b13065291f2 -t /drive1/ -2 /tmp/ramdisk/ -r 16

This is the output:
> Failed to write to <finaldir> directory: ''

Seems like it expects the -d argument even when not specified.

**Comment by VertiHydro** [comment]
Working fine for me - have you tried placing the arguments in the order that they're listed in in the readme? It's the only thing that's different from your command to mine. Not that that should make any difference.

**Comment by mist0706** [comment]
maybe it has been fixed in a later commit?

**Comment by madMAx43v3r** [comment]
fixed now, in caace4decd31f6f8d85528c6337497f9875ed578

**Comment by madMAx43v3r** [comment]
@mist0706 it also does a rename now, if `finaldir` is same block device as `tmpdir`

**Comment by mist0706** [comment]
That's amazing! Good work and thanks for taking the time to add my suggestion :)
