### ISSUE TITLE
Option to create plot in final destination dir

### ISSUE THREAD

**Issue by madMAx43v3r** [madMAx43v3r/chia-plotter#688]

**Comment by Dartellum** [comment]
The final destination most likely is slow as it could go to a USB drive. I started looking up kernel level copying and did find some examples. I found copy_file_range(2), https://man7.org/linux/man-pages/man2/copy_file_range.2.html that keeps the copy in kernel and does not transfer in and out of user space. Found this as well:
```
Since version 4.14 of Linux kernel, vfs_read and vfs_write functions are no longer exported for use in modules. Instead, functions exclusively for kernel's file access are provided:

# Read the file from the kernel space.
ssize_t kernel_read(struct file *file, void *buf, size_t count, loff_t *pos);

# Write the file from the kernel space.
ssize_t kernel_write(struct file *file, const void *buf, size_t count,
            loff_t *pos);
```
from https://stackoverflow.com/questions/1184274/read-write-files-within-a-linux-kernel-module.

**Comment by madMAx43v3r** [comment]
i think those can only be used by kernel code
