### ISSUE TITLE
[BUG] function BitsGeneric assert failed

### ISSUE THREAD

**Issue by draven-chen** [madMAx43v3r/chia-plotter#69]
[P1] Table 1 took 12.6873 sec
[P1] Table 2 took 98.4281 sec, found 4295062840 matches
[P1] Lost 95320 matches due to 32-bit overflow.
[P1] Table 3 took 147.542 sec, found 4295039682 matches
[P1] Lost 71757 matches due to 32-bit overflow.
[P1] Table 4 took 188.549 sec, found 4295045757 matches
[P1] Lost 77760 matches due to 32-bit overflow.
[P1] Table 5 took 186.191 sec, found 4294945006 matches
chia_plot: /home/draven/chia-plotter/chia-plotter/include/chia/bits.hpp:137: void BitsGeneric<T>::InitBitsGeneric(uint64_t, uint32_t) [with T = SmallVector; uint64_t = long unsigned int; uint32_t = unsigned int]: Assertion `size == 64 || value == (value & ((1ULL << size) - 1))' failed.
Aborted (core dumped)

**Comment by madMAx43v3r** [comment]
oh boy, unstable RAM?

**Comment by draven-chen** [comment]
> oh boy, unstable RAM?

thanks, i tried to remove difference speed DRAM, this problem solved.
