### ISSUE TITLE
Plots created with mad max plotter 0.0.6 unsigned at h pool 

### ISSUE THREAD

**Issue by Wolverine0984** [madMAx43v3r/chia-plotter#694]
Hello . I've got problems with my plots created by mad max 0.0.6 .they don't be able to sign on hpool .seems that something is wrong with my keys . I try out different Pool publik keys and farmer keys I bound everything on hpool it shows the right capacity but my plots still unsigned after 2 days. Any ideas?

**Comment by pwagma** [comment]
You probably mixed the pk and the fk

**Comment by Wolverine0984** [comment]
Thank you  but I checked them 3 times i change to Linux now and try it again

**Comment by nophr** [comment]
Hi @Wolverine0984 ,

I am having the same issues as you. My plots by madmax are not being recognised by hpool. It is showing up in the "Online Miner" correctly but my contribution and signed plots do not include plots by madmax.

I noticed that when you use the hpool app to get signature (the pk and fk start with 0x) does 0x matters?

**Comment by Wolverine0984** [comment]
Hi@nophr. Yes I think that's the problem ,I try to use the pk and fk from hpool plotter .wen you try to execute madmax plotter with the keys show there it says invalid pk or fk  key must have 48 bytes .the original chia keys seems to be different from the keys shown up by hpool plotter .

**Comment by nophr** [comment]
Did you manage to fix the problem? I don't like the feeling of re-plotting everything again :( my pk and fk key are correct and they give no error on hpool miner (hpool miner recognised them fine) but it is not showing up contribution power.

**Comment by nophr** [comment]
I read a few things on hpool. Everyone seem to see a drop in contribution from their online miner power today. So I don't this is madmax issues.

**Comment by Wolverine0984** [comment]
Unfortunately not. I set up all on Ubuntu 20.04 and plot right now the first one.

**Comment by Wolverine0984** [comment]
Ok that's possibl hpool Is getting some issue too to sign in .maybe it's hpool  .i already plot on Ubuntu so I try anyway.

**Comment by nophr** [comment]
@Wolverine0984 does your new plot gets recognised in hpool?

**Comment by Wolverine0984** [comment]
I don't know yet .I think I'm finish at evening if it works I will tell you. sorry chia is not my only child I have to Care for.

**Comment by Wolverine0984** [comment]
Looks like hpool is badly slow to show up my new plots I still can see the plots they can't sync for days .it's about 7 hours ago wenn i deleted them .so I still wait ...

**Comment by Wolverine0984** [comment]
I think I solve the problem.my new plots are signed at hpool now. I start again from zero.i deleted the hpool plotter and chia Blockchain .Download all again and install. After that I start chia gui and first delete All keys then set my mnemonic passphrase .then search in the cli for the pk and fk . copy them into a textfile.then start hpool plotter and set the same mnemonic.check the keys they look similar except from

**Comment by Wolverine0984** [comment]
0 x .then go to bind the new signature to hpool . After a few hours waiting  the plots be made by madmax show as signed now .I don't know exactly what I made wrong the first time .I think it was the binding process or the h pool plotter client .

**Comment by nophr** [comment]
@Wolverine0984 , I managed to fix my issues by restarting the miner a couple of times and enable "multithread directory loading" in the miner app. The total to look through all my directories was taking more than 5 seconds.

I keep plotting with the original chia keys (without 0x)
