### ISSUE TITLE
fix gcc11 incompatibility

### ISSUE THREAD

**Issue by carlfarrington** [madMAx43v3r/chia-plotter#70]
The gcc-11 incompatibility appears to be due to bugs in the code (blake2 ?).
Will this be fixed?
Apparently it's pure luck that it works at all in older versions of gcc - see this [thread](https://bugzilla.redhat.com/show_bug.cgi?id=1937076).

**Comment by madMAx43v3r** [comment]
I know, I didn't write the code...
I'll update to latest BLAKE3 code later today, maybe that'll fix it..

**Comment by carlfarrington** [comment]
I got it built on fedora 34 with gcc11 just now. i'm not sure if it will actually work though since I'm not a C++ programmer!

dnf install gmp-static sodium-static (otherwised ar: unknown file type with dynamic library)
after failed build, in chia-plotter/build/_deps/relic-src/src/md/blake2.h
changed line 64:
`typedef struct ALIGNME( 64 ) __blake2s_state`
and line 89:
`typedef struct ALIGNME( 64 ) __blake2b_state`

**Comment by carlfarrington** [comment]
Seems to be plotting OK so far..
`(venv) build/chia_plot <key> <key> /mnt/adata512gb/ /mnt/wdsn7501tb/ 6
Number of Threads: 6
Number of Sort Buckets: 2^7 (128)
Pool Public Key:   <key>
Farmer Public Key: <key>
Working Directory:   /mnt/adata512gb/
Working Directory 2: /mnt/wdsn7501tb/
Plot Name: plot-k32-2021-06-09-13-59-13ce64358f09a1715f36960b1eaa249fdcc2d95d58a216a1177b47744cf2aaea
[P1] Table 1 took 31.8713 sec
[P1] Table 2 took 280.82 sec, found 4294980960 matches
[P1] Lost 13597 matches due to 32-bit overflow.
[P1] Table 3 took 349.768 sec, found 4295063853 matches
[P1] Lost 95799 matches due to 32-bit overflow.
[P1] Table 4 took 390.185 sec, found 4295057114 matches
[P1] Lost 89920 matches due to 32-bit overflow.
[P1] Table 5 took 384.097 sec, found 4295063060 matches
[P1] Lost 95381 matches due to 32-bit overflow.
[P1] Table 6 took 370.428 sec, found 4295147579 matches`

**Comment by madMAx43v3r** [comment]
looks good so far, but check the plot later with `ProofOfSpace check -f *.plot` to make sure it's legit

**Comment by carlfarrington** [comment]
Yes it works fine. Verified with ProofOfSpace check

> Proof verification suceeded. k = 32
Total success: 997/1000, 99.7%.
(venv) Proof verification suceeded. k = 32
Total success: 997/1000, 99.7%.

**Comment by madMAx43v3r** [comment]
great, in that case I'll fork the BLAKE3 repo and apply your patch

**Comment by madMAx43v3r** [comment]
Ah this is about `build/_deps/relic-src/src/md/blake2.h`, I can't patch that...

**Comment by hardhub** [comment]
> 
> 
> I know, I didn't write the code...
> I'll update to latest BLAKE3 code later today, maybe that'll fix it..

No, still relies on blake2.h

`chia-plotter/build/_deps/relic-src/src/md/blake2.h:101:5: error: size of array element is not a multiple of its alignment`

**Comment by hardhub** [comment]
> 
> 
> I got it built on Fedora 34 with gcc11 just now. i'm not sure if it will actually work though since I'm not a C++ programmer!
> 
> dnf install gmp-static sodium-static (otherwised ar: unknown file type with dynamic library)
> after failed build, in chia-plotter/build/_deps/relic-src/src/md/blake2.h
> changed line 64:
> `typedef struct ALIGNME( 64 ) __blake2s_state`
> and line 89:
> `typedef struct ALIGNME( 64 ) __blake2b_state`

Yes it solves the issue. Now I can build it for Fedora.
