### ISSUE TITLE
Always killed after [P3-1] Table 6 

### ISSUE THREAD

**Issue by joelrb** [madMAx43v3r/chia-plotter#708]
I been experiencing lately this issue.

Always killed after [P3-1] Table 6.

Ubuntu 20.04
Intel Xeon E5-2680V2 (10 cores / 20 Threads)
64GB Memory
SSDs for temp 1 and 2

**Comment by madMAx43v3r** [comment]
some other processes eating your RAM ?

**Comment by joelrb** [comment]
> some other processes eating your RAM ?

This is only plotting machine. Only plotter running and the system monitor. Minimal Ubuntu installation, so no other processes.

I'll monitor the progress now and check memory usage.

**Comment by joelrb** [comment]
Killed again after [P3-1] Table 4. I wasn't able to look at the monitor before it happened.
You think this is memory-related?

**Comment by ataa** [comment]
If you know the approximate time of kill, check /var/log/syslog around that time, there should be a reason of kill logged there.
I faced the same issue on Minimal 21.04 with 16GB ram and swapoff, increasing the bucket size solved it for me. 
Try `cat /var/log/syslog* | grep 'Killed process'`
Or `cat /var/log/syslog* | grep 'Out of memory: Killed`

here is my log entry:
`990x kernel: [ 5835.426265] Out of memory: Killed process 12657 (chia_plot)  file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:30436kB oom_score_adj:0`

**Comment by joelrb** [comment]
> If you know the approximate time of kill, check /var/log/syslog around that time, there should be a reason of kill logged there.
> I faced the same issue on Minimal 21.04 with 16GB ram and swapoff, increasing the bucket size solved it for me.
> Try `cat /var/log/syslog* | grep 'Killed process'`
> Or `cat /var/log/syslog* | grep 'Out of memory: Killed'`
> 
> here is my log entry:
> `990x kernel: [ 5835.426265] Out of memory: Killed process 12657 (chia_plot) file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:30436kB oom_score_adj:0`

Thanks I'll check it. Indeed -u 512 helped.

**Comment by antonmakarenko** [comment]
```
[P3-1] Table 3 took 75.5504 sec, wrote 3439940484 right entries
./plot.sh: line 4:   991 Segmentation fault      (core dumped) ~/chia-plotter/build/chia_plot -n $1 -r 12 -u 512 -v 128 -t /mnt/u/tmp/ -2 /mnt/t/tmp/ -d /mnt/j/plots/ -p $POOL_KEY -f $FARMER_KEY 2>&1
```
Version 17fd63377d429187633979c4d8a21d0abc09a90a
Ubuntu 20.04.2 LTS under Windows 10 WSL v1
16 GB RAM, swap off.

Could not find anything in `/var/log` that would provide more clues
I'm going to try to increase `-v` buckets to 256

**Comment by ataa** [comment]
> 991 Segmentation fault      (core dumped) ~/chia-plotter/build/chia_plot

Run a Memtest on your machine, Also unstable overclock/voltages may cause SEGFAULT.

**Comment by antonmakarenko** [comment]
> Run a Memtest on your machine, Also unstable overclock/voltages may cause SEGFAULT.
Got my memory at 2133 no overclock whatsoever. It seems like indeed it is running out of memory, just not properly reporting under WSL. After running a day at `-v 256` didn't experience it anymore.

The only I'd recommend as far as this plotter code changes, is to report errors more verbosely, or perhaps add an option for more verbosity.
