### ISSUE TITLE
Question: Does parallel plotting makes sense in this plotter?

### ISSUE THREAD

**Issue by delucca** [madMAx43v3r/chia-plotter#71]
Hi !

First and foremost, I've run a few tests yesterday with your plotter. The speed is impressive! My rig takes ~6h to plot using Chia default plotter, and with your library, it took only 1h10min (6x faster).

Anyway, during my tests yesterday I tried two scenarios:
- Serial plotting
- Parallel plotting

While serial plotting, it took 1h10min, but while parallel plotting (with proper stagger minutes) it took 3h30min (running 3/4 plots at the same time)

So, my question is, since we assume this plotter optimizes the resource usage. Does it make sense to try to parallel plot? In my simple test scenario, it seems that while parallel plotting the plot time increased at the same rate. So, IMHO, it seems that we optimize the plotting so much that parallel plotting doesn't make sense.

I would like to know your opinion regarding this.

**Comment by mist0706** [comment]
Short answer: No

Here is the CPU usage graph for one of my 5950x rigs:
![image](https://user-images.githubusercontent.com/10143260/121354614-54e6f480-c92f-11eb-86be-43ea5932f7ee.png)

What we can deduct from it is that phase1 is already very optimized cpu wise, it uses up pretty much the entire CPU. 
Phase 2 also uses most of the cpu however at intervals
Phase 3/4 are the least cpu intensive tasks.

The only way i can see to squeeze out a tiny bit more performance is to start a new plot as soon as phase 3 is done. This will only net you about 60s of parallelism in my case. You might be able to launch a plot when phase2 is done but you'll have issues with CPU context switching which might render it meaningless.

**Comment by delucca** [comment]
Great answer! Thanks @mist0706 

That was exactly what I was expecting. I was not able to gather formal results regarding CPU usage yet, but my feeling was exactly that.

IMHO the only way we could parallelize to improve performance would be by implementing MPI or another parallel API to distribute CPU work across multiple nodes.

Quick question, have you installed Prometheus to gather metrics regarding your rigs? That is a pretty good idea :)

**Comment by madMAx43v3r** [comment]
Yeah overlapping phase 1 and 3 is your best bet, how much you'll gain depends on your `tmpdir` disk speed.

**Comment by delucca** [comment]
In any case, given the amazing performance this plotter have, I really think that the effort to find the exact stagger time to overlap phase 1 and 3 don't pay off.

I've done that with chia default plotter, and it is pretty hard to find the exact time.

**Comment by madMAx43v3r** [comment]
It'll be an option in the plotter itself (at some point), to run 2 or 3 in parallel staggered.

**Comment by delucca** [comment]
Well, if the plotter itself can do that, it would be pretty amazing!

**Comment by digitalscream** [comment]
Short answer: It depends.

Long answer: On my dual E5-2450 machine, the fastest I can get with my available hardware is sub-2hr plots, using all 16 cores, SAS RAID0 for tmp1 and NVMe for tmp2. That works out at 12-13 plots per day.

However, restricting it to 4 cores per plot process, with 4 x 4 disk SAS RAID0 arrays arranged in tmp1/tmp2 pairs, and using taskset to force each process to only run on the physical and logical cores of half of each physical CPU, I can run 4 of these plotters in parallel at ~2h50m per plot, thus netting 32+ plots per day.

It's about balancing your hardware more than getting the absolute fastest single-plot time.

**Comment by 69chargr** [comment]
I'm going to try the overlap manually today and see what I can manage. The move to a permanent drive is going to slow this process down I believe to the point we are still at break even or worse compared to pechy combined + Swar. Just my guess though.

**Comment by digitalscream** [comment]
> I'm going to try the overlap manually today and see what I can manage. The move to a permanent drive is going to slow this process down I believe to the point we are still at break even or worse compared to pechy combined + Swar. Just my guess though.

For what it's worth, I wrote a quick bash script which loops the above config, but also spins the destination move into a separate process so the next plot can start immediately. It's not the most efficient way to do it, and it does slow down the start of the next plot, but overall it's faster.

**Comment by delucca** [comment]
Well, you could easily create 2 bash scripts:

1. Launches the plotter WIHTOUT settings the `-d` param to keep the final plot in the temp memory
2. Listens to the temp dir and move everything ending with `plot` (without any other extension at the end) to the final dir

That would not slow down the start of the next plot

**Comment by madMAx43v3r** [comment]
The final destination copy runs parallel to the next plot, if you do more than 1 via `-n`.

**Comment by delucca** [comment]
> The final destination copy runs parallel to the next plot, if you do more than 1 via `-n`.

Amazing,

Man, you're a genius hahaha

So, no need to two bash scripts!

**Comment by digitalscream** [comment]
> That would not slow down the start of the next plot

It would still slow it down to a certain degree, if you're not using a ramdisk, because disk bandwidth is limited. Remember, this plotter isn't _only_ useful to people with insane amounts of available memory ;)

> The final destination copy runs parallel to the next plot, if you do more than 1 via `-n`.

Fair play, sir - I'm still using a slightly older version.

**Comment by madMAx43v3r** [comment]
Lol the plotter already does everything in parallel, would be stupid not to do the copy in parallel also ;)

**Comment by winkee01** [comment]
does it make things faster if I apply a raid0 with 2 ssd?

**Comment by digitalscream** [comment]
> does it make things faster if I apply a raid0 with 2 ssd?

Depends entirely on your system. The best way to find out is to try it :)

**Comment by madMAx43v3r** [comment]
if you don't use RAM and CPU is fast, probably yes

**Comment by MarcusArthur** [comment]
> does it make things faster if I apply a raid0 with 2 ssd?

I have 4x 1TB NVMEs in a RAID 0 config (totally overkill I know) and I'm able to get about 3000 seconds/finished plot.

**Comment by winkee01** [comment]
> > does it make things faster if I apply a raid0 with 2 ssd?
> 
> I have 4x 1TB NVMEs in a RAID 0 config (totally overkill I know) and I'm able to get about 3000 seconds/finished plot.

As a comparison, how much time will it take if no raid 0 is applied?

**Comment by mist0706** [comment]
I've done testing on the nvme raid0. Beyond 3000mb/s raid doesn't give any benefits. A single 3000mb/s nvme is as quick as two of the same in raid
