### ISSUE TITLE
Writing Operation on a Different Drive

### ISSUE THREAD

**Issue by NoanKa** [madMAx43v3r/chia-plotter#747]
I'm trying to create plots using two ssds as temp1 and temp2 drives. My operating system is on a different device (USB). It gives me the "Failed to write to tmpdir directory" error. I made a temp directory on my usb and started and it works fine. Is it not possible to use the disk without the os for writing operation?

**Comment by Dartellum** [comment]
You can use disks other than ones with OS. Make sure you have permission to the drives level you are trying to write. For me, I had mounted a drive with root, Linux, and needed to change the permission so I could write to it.

**Comment by madMAx43v3r** [comment]
yes check permissions

**Comment by NoanKa** [comment]
> You can use disks other than ones with OS. Make sure you have permission to the drives level you are trying to write. For me, I had mounted a drive with root, Linux, and needed to change the permission so I could write to it.

I changed the ownership of the drives instead but it worked. Thanks

**Comment by 2B4Saken876** [comment]
I had all kinds of grief with this. Very new to linux/Ubuntu. 
Changing permissions with this got rid of my Failed to write problem.
$ sudo apt-get install nautilus
$ sudo nautilus
Just set drives to root and gave read write to everything.
Very noob approach but now all working.
