### ISSUE TITLE
Any plan to support Official Pooling Protocol?

### ISSUE THREAD

**Issue by mapleaj** [madMAx43v3r/chia-plotter#759]
Wish  support Official Pooling Protocol

**Comment by VertiHydro** [comment]
Please... I'm begging you... check existing issues before making a new one...
See https://github.com/madMAx43v3r/chia-plotter/pull/529 - the plotter already supports the pool protocol as long as you use the pool-puzzles branch

**Comment by AlexeyBoiler** [comment]
The stable version 1.2.0 with pool support has already been released. When are you planning to implement it in madMAx?

**Comment by reubes** [comment]
Current main branch now already includes support for pools with -c option

**Comment by AlexeyBoiler** [comment]
Thanks, you can close, I think)
