### ISSUE TITLE
Can't start Plots without the -p option

### ISSUE THREAD

**Issue by ManuMTS** [madMAx43v3r/chia-plotter#783]
I'm running ubuntu 20.04. When trying to run the plotter with options -c and -f (for making pool plots) the plotter complains it also wants an option -p. When giving a pool key the plots aren't recognized in the chia gui though.

**Comment by madMAx43v3r** [comment]
make sure to recompile after updating via git

**Comment by ManuMTS** [comment]
Hey thank you that worked out.
