### ISSUE TITLE
Ryzen 9 5950x 

### ISSUE THREAD

**Issue by Phidan** [madMAx43v3r/chia-plotter#792]
Hi everyone 
I am have some issues while ploting in Widows with Ryzen 9, 16 core, 32 threads, RAM 64 GB , 2x 2 TB M2 SSD MVne  Time per plots vary from 33 to 41 minutes. What is the best setup and how many plots can I get per day?

**Comment by Phidan** [comment]
.

**Comment by noskoski** [comment]
I have a Ryzen 9 5900x 12 cores/ 24 threads with 16GB RAM, and 2x 500 GB WD sn750, my plots are faster even with less 4 cores. 
![image](https://user-images.githubusercontent.com/34073151/125489759-8ee94cab-c0b7-4bf5-ae34-08ab6a71af98.png)
