### ISSUE TITLE
Is it possible to plot  with 60GB tmpfs (tmpdir2) by descrease the number of bucket?

### ISSUE THREAD

**Issue by navyfeng** [madMAx43v3r/chia-plotter#805]
Or modify other options  ?

**Comment by VertiHydro** [comment]
You can plot with 60GB, you just can't use ramdisk/tmpfs. You can only use tmpfs if you have 128GB.

**Comment by madMAx43v3r** [comment]
Nope...

**Comment by navyfeng** [comment]
Thanks  @VertiHydro  @madMAx43v3r
