### ISSUE TITLE
Caught exception "Argument '?' failed to parse"

### ISSUE THREAD

**Issue by laosika** [madMAx43v3r/chia-plotter#808]
Any idea why i can not start the manager? Already tried restarting/installing everything
![Unbenannt](https://user-images.githubusercontent.com/87328805/125322095-abd05700-e33d-11eb-96b6-d787d55becdb.PNG)

**Comment by VertiHydro** [comment]
> Any idea why i can not start the manager? Already tried restarting/installing everything
> ![Unbenannt](https://user-images.githubusercontent.com/87328805/125322095-abd05700-e33d-11eb-96b6-d787d55becdb.PNG)

yes - why did you type `-n ?` - what is the question mark for? -n should be the number of plots to create.  If you want infinite plots, set it to -1.

**Comment by laosika** [comment]
Thank you - i am such an idiot :-)
