### ISSUE TITLE
valid args for -K / --rmulti2

### ISSUE THREAD

**Issue by wallentx** [madMAx43v3r/chia-plotter#809]
I'm guessing valid args for this are either `1` or `2`?
Or maybe not.. I passed `30` to it just for testing, and during
> [P2] Table 7 scan
> [P2] Table 7 rewrite

it appeared to only be using 1 thread.. and I just looked back and it seems to be using all 48 cores..
Trying to figure out what the best setting is for this for my setup.

### Phase 2 times
Prior to merging https://github.com/madMAx43v3r/chia-plotter/pull/670: `430.402`s
-K 2: `544.311`s
-K 30: `482.178`s

**Comment by josinaldobarbosa** [comment]
30 is too high a value, 2 is twice as many threads put in the -r argument, the way it is in the code is `num_threads * g_thread_multi`

**Comment by josinaldobarbosa** [comment]
-K 1 = same as -r (today has little load in phase 2)
-K 2 = double the -r
-K 3 = triple of -r
...
at a certain point, the number of threads becomes a bottleneck that will take more time, you have to test to see how far this limit is compensated on your hardware

**Comment by madMAx43v3r** [comment]
1 or 2 makes most sense, it multiplies the -r value

**Comment by gryan315** [comment]
From my testing with a dual xeon 2678v3 system, phase 2 performs best at -r 48, and phase 3 does best at -r 24 with phase 1 about the same for both. Phase 3 is the dominant factor, so my previous fastest time was 24 minutes at -r 32 (best balance of phase 2 and 3).

Now with -r 24 -K 2 I get the best of both, and my plot creation time got reduced by just over a minute.

**Comment by josinaldobarbosa** [comment]
I tried it with a value of 2 and I didn't get any difference

**Comment by wallentx** [comment]
> From my testing with a dual xeon 2678v3 system, phase 2 performs best at -r 48, and phase 3 does best at -r 24 with phase 1 about the same for both. Phase 3 is the dominant factor, so my previous fastest time was 24 minutes at -r 32 (best balance of phase 2 and 3).
> 
> Now with -r 24 -K 2 I get the best of both, and my plot creation time got reduced by just over a minute.

I appreciate it. It also looks like you've been doing a lot of testing and benchmarking. I stumbled across https://github.com/sharkdp/hyperfine , and it's been a treasure.

`hyperfine -r 2 -P threads 20 48 '~/bin/chia_plot -c $SCK -f $FPK -n 1 -r {threads} -u 256 -v 256 -t /mnt/ssdarray1/ -2 /mnt/ssdarray2/ -d /mnt/ssdarray1/'`

A command like the above results in this (if you chose to output as md) https://gist.github.com/3b430d7cac9260a56a7435a5fbecc309

**Comment by Armageus** [comment]
@stotiks - appreciate you may be busy, but do you know when this option will be added to the Windows build?

**Comment by Armageus** [comment]
> @stotiks - appreciate you may be busy, but do you know when this option will be added to the Windows build?

Even just some working instructions on how to build for Windows from Source would be ideal, then I'd look at making changes myself
