### ISSUE TITLE
974d6e5 commit - slower speed

### ISSUE THREAD

**Issue by Dartellum** [madMAx43v3r/chia-plotter#810]
I updated to the latest to test out the -K option earlier today and restarted my plotting. Phase 1 took 13481 seconds compared to 9098 seconds. I cannot wait until I can order the enterprise SSDs. I set -K 2. But, that is not used until phase 2.

**Comment by madMAx43v3r** [comment]
It can't be caused by the new setting...

**Comment by Dartellum** [comment]
> It can't be caused by the new setting...

Right, that should not slow it down. I will see if the next plot is back to my normal time. I will leave this open until tomorrow.

**Comment by Dartellum** [comment]
Okay, speeds are back to where they were before. 🤷‍♂️
