### ISSUE TITLE
How much SSD write when RAM disk is enabled

### ISSUE THREAD

**Issue by niconiconi** [madMAx43v3r/chia-plotter#829]
so basically with this parameter: `-t ssd_path -2 ramdisk_path -f ssd_path`

Assuming ramdisk has 120GB space.

How much SSD write per plot?

**Comment by Jacek-ghub** [comment]
Crystal Disk Info gives you exact data about TBW to a given SSD.  Just run it first, then run one plot, and go back to Crystal Disk Info.

**Comment by niconiconi** [comment]
> Crystal Disk Info gives you exact data about TBW to a given SSD. Just run it first, then run one plot, and go back to Crystal Disk Info.

I have other applications run on that SSD, so it's not accurate.

**Comment by wavepacket0** [comment]
assuming that a plot requires 1.3Tib (about 1.43TB) of written data and 75% of writes are on tmp2, I would assume that you save about 1.07TB of writes by using a ramdisk. However I cannot test since my ram is just 32G. By the way, even with less ram, you can use programs like PrimoCache to have a consistent benefit, for me it's around 26% of saved writes with 21G ram

**Comment by RenarYnosX** [comment]
> 
> 
> assuming that a plot requires 1.3Tib (about 1.43TB) of written data and 75% of writes are on tmp2, I would assume that you save about 1.07TB of writes by using a ramdisk. However I cannot test since my ram is just 32G. By the way, even with less ram, you can use programs like PrimoCache to have a consistent benefit, for me it's around 26% of saved writes with 21G ram

Hardly believe that temp2 takes 75% writes. putting slow HDD on temp2 didnt expands plot time so much as for temp1
And why -t and -2 work opposite -t is temp2 and -2 is temp1!? 
Strange...

**Comment by ChazyTheBest** [comment]
@RenarYnosX Huh? What are you talking about?
```
  -t, --tmpdir arg     Temporary directory, needs ~220 GiB (default = $PWD)
  -2, --tmpdir2 arg    Temporary directory 2, needs ~110 GiB [RAM] (default = <tmpdir>)
```

**Comment by mk01** [comment]
@niconiconi 

with tmp/tmp2 split, tmp takes in total ~370G of io sent to storage device.
