### ISSUE TITLE
Final file won't rename if not enough space was encountered during copying, process keeps the file locked preventing manual renaming

### ISSUE THREAD

**Issue by bart-sz** [madMAx43v3r/chia-plotter#831]
The destination HDD did not have enough space to accept the final file (my mistake). The plotter re-attempted copying several times until I freed up enough space to fit it in (and then some).

After the file had eventually been copied, it retained the _.plot.tmp_ file extension, which chia_plot.exe wouldn't rename back to _.tmp_ extension itself as expected, however it wouldn't let me rename manually either. A system prompt appeared saying the file was in use by chia_plot.exe (Resource Monitor showed it wasn't being read or written to, however the file appeared locked).

The following message was displayed a few times in Powershell when there wasn't enough space:
`Copy to e:\plot-k32-2021-07-15-**************.plot failed with: fwrite() failed`

The standard message after freeing up some space and finishing copying:
`Copy to e:\plot-k32-2021-07-15-***************.plot finished, took 4590.13 sec, 22.6124 MB/s avg.`

**Comment by bart-sz** [comment]
The file lock is released after all N plots have been completed and the chia_plot.exe process quits.

**Comment by Mirkic7** [comment]
This is due to issue I already posted in bug #816

**Comment by bart-sz** [comment]
Agreed @Mirkic7 - can confirm the source file was not deleted here as per #816
