### ISSUE TITLE
Why can't plotter write to a shared network drive/folder?

### ISSUE THREAD

**Issue by joelrb** [madMAx43v3r/chia-plotter#835]
I get error using shared network drive as final dir. 

Plotter is Ubuntu and writing to another Ubuntu shared drive (smb://IPAddress/folder) as final dir.

Plotter says cannot write to drive. I can write. I can copy/paste anything to the shared folder.

**Comment by diaconom** [comment]
Did you try to mount your  smb share and use the mounted drive as your destination?

sudo mount -t cifs //<ip_address>/<export_share> /mnt/<local_share>

**Comment by joelrb** [comment]
> Did you try to mount your smb share and use the mounted drive as your destination?
> 
> sudo mount -t cifs //<ip_address>/<export_share> /mnt/<local_share>

Ohh how odd. Still need to be mounted huh? Why can't it be like windows and mac, sigh.

I will try.

**Comment by bdelgado1995** [comment]
I'm writing ok from one Ubuntu to another. You can see if the remote drive is mounted by running 'df'. I have had to first (one-time thing) chown [username] /mnt/samba_dir (for example) on the plotting machine to be able to write to the remote samba share.
