### ISSUE TITLE
use -c plotting, the GUI shows Failed to open (invalid plots)

### ISSUE THREAD

**Issue by mapleaj** [madMAx43v3r/chia-plotter#837]
I tried twice,both invalid plots, I used -f farmer key  and -c contract address

**Comment by me12345ghru** [comment]
The Art of Tantric Sacred Sex

Barbara Hart

**Comment by VertiHydro** [comment]
huh?

**Comment by mapleaj** [comment]
no one happend this problem like me?I also used  'chia plots check -g ***.plots' to check plots,it can not checked any one plots exists.

**Comment by wavepacket0** [comment]
OG plots (old format, no pooling): -f farmer_key -p poolkey 
NFT plots (new format, native pooling): -f farmer_key -c nft_contract_address

**Comment by mapleaj** [comment]
> OG plots (old format, no pooling): -f farmer_key -p poolkey
> NFT plots (new format, native pooling): -f farmer_key -c nft_contract_address
> 
> you first need to create a NFT singleton with the chia gui (and you need at least 1mojo for that). once done, copy your NFT contract address and use it with madmax

I tried OG and NFT,no one worked. 

<html>
<body>
<div class="MuiBox-root jss3268 Card__StyledCardTitle-sc-g4st3-0 bPKmnx" style="box-sizing: inherit; padding: 16px; color: rgb(255, 255, 255); font-family: Roboto; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.14994px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="MuiBox-root jss3269 Flex__StyledGapBox-sc-2jumy6-0 fdhGJg" style="box-sizing: inherit; display: flex; flex-wrap: wrap; align-items: center;"><div class="MuiBox-root jss3270" style="box-sizing: inherit; flex-grow: 1;"><h5 class="MuiTypography-root MuiTypography-h5" style="box-sizing: inherit; margin: 0px; font-size: 1.5rem; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 400; line-height: 1.334; letter-spacing: 0em;">Failed to open (invalid plots)</h5></div></div></div><div class="MuiCardContent-root" style="box-sizing: inherit; padding: 16px 16px 24px; color: rgb(255, 255, 255); font-family: Roboto; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.14994px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="MuiBox-root jss3271 Flex__StyledGapBox-sc-2jumy6-0 dywIxa" style="box-sizing: inherit; display: flex; flex-direction: column;"><div class="MuiBox-root jss3272 Flex__StyledGapBox-sc-2jumy6-0 lbqHkv" style="box-sizing: inherit; display: flex; flex-direction: column;"><h6 class="MuiTypography-root MuiTypography-body2" style="box-sizing: inherit; margin: 0px 0px 16px; font-size: 0.875rem; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 400; line-height: 1.43; letter-spacing: 0.01071em;">These plots are invalid, you may want to delete them.</h6><div class="MuiPaper-root MuiTableContainer-root MuiPaper-elevation1 MuiPaper-rounded" style="box-sizing: inherit; color: rgb(255, 255, 255); transition: box-shadow 300ms cubic-bezier(0.4, 0, 0.2, 1) 0ms; background-color: rgb(66, 66, 66); border-radius: 4px; box-shadow: rgba(0, 0, 0, 0.2) 0px 2px 1px -1px, rgba(0, 0, 0, 0.14) 0px 1px 1px 0px, rgba(0, 0, 0, 0.12) 0px 1px 3px 0px; width: 912px; overflow-x: auto;">

Filename | Action
-- | --
D:\chia\plot-k32-2021-07-16-00-26-89e604bdd1bd144d94617438de231cb36d44dc86d9c750e3b7bfa12faa9764de.plot |  
D:\chia\plot-k32-2021-07-16-12-17-d51894ac991cf964d5210406a4bffdff8426311df924219bca8c55c326c11f07.plot |  
D:\chia\plot-k32-2021-07-16-14-34-227de94e64123978cf8c62be899342495d7db44aac7e7c14a6547e4cc4b057a1.plot |  
D:\chia\plot-k32-2021-07-16-16-33-565c37189e948af9da79e50203051c09a9c95ebe6a22d9ff6d04376b3736026a.plot

</div></div></div></div>
</body>
</html>

**Comment by mapleaj** [comment]
> OG plots (old format, no pooling): -f farmer_key -p poolkey
> NFT plots (new format, native pooling): -f farmer_key -c nft_contract_address
> 
> you first need to create a NFT singleton with the chia gui (and you need at least 1mojo for that). once done, copy your NFT contract address and use it with madmax

Before I updated to the lastest version,it's worked very well,AMD 5800X took 1800s finish one plot.But now even OG version was invalid.

**Comment by wavepacket0** [comment]
Are you sure farmer & contract keys are right? I'm on jul8 version and everything is working fine

**Comment by mapleaj** [comment]
> Are you sure farmer & contract keys are right? I'm on jul8 version and everything is working fine

It's seems ploting path can not include non English characters,I am reploting now.
