### ISSUE TITLE
Can't compile on Arch - no static gmp & sodium

### ISSUE THREAD

**Issue by wallentx** [madMAx43v3r/chia-plotter#85]
Arch only provides dynamic libs for libgmp and libsodium, which I think is causing this to fail, even with the workaround listed here - https://github.com/madMAx43v3r/chia-plotter/issues/70

Attempted on both gcc-10 and 11

**Comment by lukeomatik** [comment]
I confirm.

```
[ 95%] Built target test_disk_sort
[ 95%] Building CXX object CMakeFiles/check_phase_1.dir/test/check_phase_1.cpp.o
[ 96%] Linking CXX executable test_phase_4
[ 96%] Built target test_phase_4
/usr/bin/ar: /usr/lib/libgmp.so: file format not recognized
make[2]: *** [lib/bls-signatures/src/CMakeFiles/combined_custom.dir/build.make:73: lib/bls-signatures/src/CMakeFiles/combined_custom] Error 1
make[1]: *** [CMakeFiles/Makefile2:477: lib/bls-signatures/src/CMakeFiles/combined_custom.dir/all] Error 2
```

**Comment by xorinox** [comment]
Issue is /usr/bin/ar     aims to extract   /usr/lib/libgmp.so    which isn't possible.   When for example static versions of libs sodium and gmp are installed   then you would find the lib files with ending .a   for example  /usr/lib64/libgmp.a

**Comment by lukeomatik** [comment]
> Issue is /usr/bin/ar aims to extract /usr/lib/libgmp.so which isn't possible. When for example static versions of libs sodium and gmp are installed then you would find the lib files with ending .a for example /usr/lib64/libgmp.a

Installed both static version plus modification mentioned in https://github.com/madMAx43v3r/chia-plotter/issues/70#issuecomment-857664855.

Managed to compile it but seems it doesnt work.
It closes itself after 
```
Final Directory: ./ws/
Number of Plots: 20
Number of Threads: 4
Number of Sort Buckets: 2^7 (128)
```

**Comment by delucca** [comment]
> Arch only provides dynamic libs for libgmp and libsodium, which I think is causing this to fail, even with the workaround listed here - #70
> 
> Attempted on both gcc-10 and 11

Arch has libgmp-static and libsodium-static libs. You can install them with `yay` (instead of `pacman`).

**Comment by delucca** [comment]
> > Arch only provides dynamic libs for libgmp and libsodium, which I think is causing this to fail, even with the workaround listed here - #70
> > Attempted on both gcc-10 and 11
> 
> Arch has libgmp-static and libsodium-static libs. You can install them with `yay` (instead of `pacman`).

For the record: https://aur.archlinux.org/packages/libsodium-static/ and https://aur.archlinux.org/packages/libgmp-static/

**Comment by madMAx43v3r** [comment]
should be fixed now
