### ISSUE TITLE
Ubuntu 20.04: Compile error

### ISSUE THREAD

**Issue by mist0706** [madMAx43v3r/chia-plotter#9]
`[ 99%] Built target test_phase_2
In file included from /home/mist/chia-plotter/lib/bls-signatures/src/bls.hpp:18,
                 from /home/mist/chia-plotter/src/chia_plot.cpp:13:
/home/mist/chia-plotter/lib/bls-signatures/src/privatekey.hpp:21:10: fatal error: gmp.h: No such file or directory
   21 | #include <gmp.h>
      |          ^~~~~~~
compilation terminated.`

libsodium installed and running these versions:

> mist@fp-plotty5:~/chia-plotter$ cmake --version
> cmake version 3.16.3
> 
> CMake suite maintained and supported by Kitware (kitware.com/cmake).
> mist@fp-plotty5:~/chia-plotter$ gcc --version
> gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
> Copyright (C) 2019 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

I did do the git submodule update --init ahead, unsure why i would be getting a missing key error?

**Comment by fermosan** [comment]
try: apt-get install  libgmp3-dev 
then recompile.

**Comment by mist0706** [comment]
Excellent! That solved it :)

[100%] Linking CXX executable chia_plot
[100%] Built target chia_plot
