### ISSUE TITLE
Feature Request: Add a way to temporarily pause the plotter

### ISSUE THREAD

**Issue by DeflateAwning** [madMAx43v3r/chia-plotter#928]
I know about Ctrl+C to cancel after the current plot, but it would be great if there were a way to pause the program mid-way without losing the current plot.

This would be useful for when I want to set the plotter to go for a while, but I need to use my computer quickly but don't want it to be painfully slow.

**Comment by wallentx** [comment]
On Linux you can use
To pause:  kill -SIGSTOP [pid]
To resume:  kill -SIGCONT [pid]

As spooky as it sounds, those commands neither kill, not stop the process. Pause and resume.

**Comment by DeflateAwning** [comment]
Amazing! Is there a way to do this on Windows?

This should be more prominent in the documentation, imo. This is such a useful feature!

**Comment by wallentx** [comment]
> This should be more prominent in the documentation, imo. This is such a useful feature!

Unfortunately, this is not possible in Windows (afaik), which is why a Pause/Resume feature wasn't implemented into the Chia GUI- per Hoffman (I think in Keybase, months ago).

**Comment by altendky** [comment]
https://www.howtogeek.com/199976/how-to-pause-or-resume-a-windows-application-using-process-explorer/ says you can do it with ProcessExplorer and the Python psutil package [says it works with Windows](https://psutil.readthedocs.io/en/latest/#psutil.Process.suspend).  I don't know if there's a builtin way in the Windows UI or not.

**Comment by wallentx** [comment]
If someone with windows wants to test this and see if it is able to complete a plot that is also valid, please update us here!

**Comment by GT-CK** [comment]
For Linux CLI Ctrl-z works to suspend and using fg to resume.
For Windows you can use the Resource Monitor to select the plotter processes, right click and select suspend. You can right click and select resume to continue (not tested on this plotter, but used successfully on many other applications)
