### ISSUE TITLE
what is the exactly usage of -w --waitforcopy

### ISSUE THREAD

**Issue by QiangTang666** [madMAx43v3r/chia-plotter#947]
Hi:

First I would like to thank the creator for this great tools. It saved me from the plotting hell.

I recently update the madmax plotter but find every time the plotting finished, the plotter is waiting for the plot copied to the destination and then start the next plotting job.  I saw a new parameter added and tried -w false or -w 0 but the plotter seems have the same behaviour.  May I ask anyone give me a example to use the -w parameter, please? thank you indeed

Happy plotting and happy farming

Kind regards

**Comment by kvizena** [comment]
When a plot is done it is a .tmp file and being copied to the -d location, -w pauses the plotter until the copy is completed. This is useful if you are using ramdisk's or several other use cases, like overrunning the destination storage location. I have used it for PCI bus contention, network i/o normalization, and to slow down the plotters when I am waiting on more disks.

In my case I can generate a couple of hundred plots a day, I run a 40gb network, and on my fast plotters I have to set this flag or it will hit swap, and slow to a crawl if the network is saturated when the plotters drift to the same copy periods. Having seven machines copying 110gb files to two destinations slows things to a crawl.

I try and use the -w to keep the finish times not synced. It does help me, marginally.

**Comment by QiangTang666** [comment]
After cleaning the 

> When a plot is done it is a .tmp file and being copied to the -d location, -w pauses the plotter until the copy is completed. This is useful if you are using ramdisk's or several other use cases, like overrunning the destination storage location. I have used it for PCI bus contention, network i/o normalization, and to slow down the plotters when I am waiting on more disks.
> 
> In my case I can generate a couple of hundred plots a day, I run a 40gb network, and on my fast plotters I have to set this flag or it will hit swap, and slow to a crawl if the network is saturated when the plotters drift to the same copy periods. Having seven machines copying 110gb files to two destinations slows things to a crawl.
> 
> I try and use the -w to keep the finish times not synced. It does help me, marginally.

Thank you for the reply. I am actually want to know how to use the -w parameter because no matter I use it or not, my plotter always wait the copy finished and then start a new job.

**Comment by QiangTang666** [comment]
After I cleaned my old version plotter and compile from the fresh, the problem solved. If the left the -w parameter in the command, the plotter will continue to start a new job during copying the plot to my hard drive.
