### ISSUE TITLE
Add GitHub commit hash to log output

### ISSUE THREAD

**Issue by AndyRPH** [madMAx43v3r/chia-plotter#95]
Pechy's fork of the chia plotter outputs the commit hash of the version of the plotter running.  Can that be added to this plotter too? 

With how much work is going into this plotter, it'd be nice to see something similar to identify what specific version is being utilized, short of implementing actual an actual version numbering system.

**Comment by fermosan** [comment]
@AndyRPH  it's done. you may close the issue.
