### ISSUE TITLE
Option 'directout' not working

### ISSUE THREAD

**Issue by magu5026** [madMAx43v3r/chia-plotter#967]
Hi there,
it seems that the parameter 'directout' does not work.
I didn't find any handling (setter) of this parameter in the source code either. (im not good at c)

Sincerely, magu

**Comment by madMAx43v3r** [comment]
You can see here: https://github.com/madMAx43v3r/chia-plotter/blob/18cad340858f0dbcc8dafd0bda1ce1af0fe58c65/src/chia_plot.cpp#L495

If enabled it will use `final_dir` for plot creation. I think I tested it.

**Comment by magu5026** [comment]
i've tried the following:
 -D / --directout and  -D true / --directout true
but the plot was always created in `tmp_dir` first.
it seems that you didn't read the param at the beginning
so `directout` is always:
https://github.com/madMAx43v3r/chia-plotter/blob/18cad340858f0dbcc8dafd0bda1ce1af0fe58c65/src/chia_plot.cpp#L241

**Comment by madMAx43v3r** [comment]
I just tested again, it works as expected. Can you post full command line?

You just need `-D` without any value.

**Comment by madMAx43v3r** [comment]
The parameter is read here: https://github.com/madMAx43v3r/chia-plotter/blob/18cad340858f0dbcc8dafd0bda1ce1af0fe58c65/src/chia_plot.cpp#L258

**Comment by magu5026** [comment]
i double checked my settings and now it works
thx and closed
