### ISSUE TITLE
Chia build make problem

### ISSUE THREAD

**Issue by gigilio** [madMAx43v3r/chia-plotter#973]
![Screenshot_20211113-235509_AnyDesk](https://user-images.githubusercontent.com/74119825/141661406-7c7c9c08-4f98-4521-845f-6c3bc1776554.jpg)

**Comment by madMAx43v3r** [comment]
Those are just warnings in a dependency, not my node..

**Comment by lebedevilya** [comment]
I have the same problem when i'm trying to install madmax using chia 1.2.11. Also tried to install it manually using readme and the problem persists. Any suggestions?

**Comment by madMAx43v3r** [comment]
What's the problem exactly? Warnings don't prevent it from compiling.

**Comment by lebedevilya** [comment]
This is correct, i was confused because of these warnings, just needed to wait for some time and the build was completed successfully

**Comment by madMAx43v3r** [comment]
Ok, yeah the binary takes a while.
