### ISSUE TITLE
madmax randomly stops

### ISSUE THREAD

**Issue by RichardRozehnal** [madMAx43v3r/chia-plotter#974]
The terminal where madmax is running will close itself after a random time. Sometimes after half an hour, sometimes after 3 hours, etc. I'm plotting with a 110GB RAM disk. I have a 128GB RAM and Ryzen 9 5900x, Fedora linux.

**Comment by madMAx43v3r** [comment]
Most likely running out of RAM.. make sure other processes are not eating up RAM over time.
