### ISSUE TITLE
"thread failed with: fopen() failed" error based ssd used for tmpdir1

### ISSUE THREAD

**Issue by ryanswilson59** [madMAx43v3r/chia-plotter#977]
I get the aforementioned error when using this SSD.
Intel DC S3700 Series Taylorsville SSDSC2BA400G301 2.5" 400GB SATA III MLC Internal Solid State Drive (SSD)
However when I use a more generic SSD the computer plots just fine. 
I am using ramdisk and have a Xeon E5-2680 2.5Ghz 12 core.

**Comment by madMAx43v3r** [comment]
Hm do you have write permission on the filesystem?

**Comment by ryanswilson59** [comment]
Yes, I formatted it as fat32 so that it would be mounted without read/write permissions. Currently has 29G of temp files written to it.

**Comment by madMAx43v3r** [comment]
FAT32 is not a good choice anyways. Is this windows? If yes try NTFS, otherwise ext4.

**Comment by ryanswilson59** [comment]
It is linux, but yeah Ill report back how ntfs goes.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ryanswilson59** [comment]
Interesting, switching to NTFS it no longer crashes (I am using linux). However it is considerably slower than using the other SSD, I am guessing that is just because it has worse I/O performance of the drive.
